<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/access_or_group_permission_assignment.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.AccessOrGroupPermissionAssignment</code>
 */
class AccessOrGroupPermissionAssignment extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string access_id = 504426029 [json_name = "access_id"];</code>
     */
    protected $access_id = '';
    /**
     * Generated from protobuf field <code>string access_type = 495496908 [json_name = "access_type"];</code>
     */
    protected $access_type = '';
    /**
     * Generated from protobuf field <code>string assignment_name = 307750079 [json_name = "assignment_name"];</code>
     */
    protected $assignment_name = '';
    /**
     * Generated from protobuf field <code>string assignment_type = 307951982 [json_name = "assignment_type"];</code>
     */
    protected $assignment_type = '';
    /**
     * Generated from protobuf field <code>string group_id = 506361563 [json_name = "group_id"];</code>
     */
    protected $group_id = '';
    /**
     * Generated from protobuf field <code>map<string, .akeyless_grpc.StringArray> sub_claims = 185133421 [json_name = "sub_claims"];</code>
     */
    private $sub_claims;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $access_id
     *     @type string $access_type
     *     @type string $assignment_name
     *     @type string $assignment_type
     *     @type string $group_id
     *     @type array|\Google\Protobuf\Internal\MapField $sub_claims
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\AccessOrGroupPermissionAssignment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string access_id = 504426029 [json_name = "access_id"];</code>
     * @return string
     */
    public function getAccessId()
    {
        return $this->access_id;
    }

    /**
     * Generated from protobuf field <code>string access_id = 504426029 [json_name = "access_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccessId($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string access_type = 495496908 [json_name = "access_type"];</code>
     * @return string
     */
    public function getAccessType()
    {
        return $this->access_type;
    }

    /**
     * Generated from protobuf field <code>string access_type = 495496908 [json_name = "access_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccessType($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string assignment_name = 307750079 [json_name = "assignment_name"];</code>
     * @return string
     */
    public function getAssignmentName()
    {
        return $this->assignment_name;
    }

    /**
     * Generated from protobuf field <code>string assignment_name = 307750079 [json_name = "assignment_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setAssignmentName($var)
    {
        GPBUtil::checkString($var, True);
        $this->assignment_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string assignment_type = 307951982 [json_name = "assignment_type"];</code>
     * @return string
     */
    public function getAssignmentType()
    {
        return $this->assignment_type;
    }

    /**
     * Generated from protobuf field <code>string assignment_type = 307951982 [json_name = "assignment_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setAssignmentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->assignment_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string group_id = 506361563 [json_name = "group_id"];</code>
     * @return string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * Generated from protobuf field <code>string group_id = 506361563 [json_name = "group_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .akeyless_grpc.StringArray> sub_claims = 185133421 [json_name = "sub_claims"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSubClaims()
    {
        return $this->sub_claims;
    }

    /**
     * Generated from protobuf field <code>map<string, .akeyless_grpc.StringArray> sub_claims = 185133421 [json_name = "sub_claims"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSubClaims($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\StringArray::class);
        $this->sub_claims = $arr;

        return $this;
    }

}

