<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/auth_output.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.AuthOutput</code>
 */
class AuthOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.akeyless_grpc.SystemAccessCredentialsReplyObj creds = 94925029 [json_name = "creds"];</code>
     */
    protected $creds = null;
    /**
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     */
    protected $token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Akeyless\gRPC\SystemAccessCredentialsReplyObj $creds
     *     @type string $token
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\AuthOutput::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.SystemAccessCredentialsReplyObj creds = 94925029 [json_name = "creds"];</code>
     * @return \Akeyless\gRPC\SystemAccessCredentialsReplyObj|null
     */
    public function getCreds()
    {
        return $this->creds;
    }

    public function hasCreds()
    {
        return isset($this->creds);
    }

    public function clearCreds()
    {
        unset($this->creds);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.SystemAccessCredentialsReplyObj creds = 94925029 [json_name = "creds"];</code>
     * @param \Akeyless\gRPC\SystemAccessCredentialsReplyObj $var
     * @return $this
     */
    public function setCreds($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\SystemAccessCredentialsReplyObj::class);
        $this->creds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

}

