<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/auth.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.Auth</code>
 */
class Auth extends \Google\Protobuf\Internal\Message
{
    /**
     * Access ID
     *
     * Generated from protobuf field <code>string access_id = 504474079 [json_name = "access-id"];</code>
     */
    protected $access_id = '';
    /**
     * Access key (relevant only for access-type=access_key)
     *
     * Generated from protobuf field <code>string access_key = 69437836 [json_name = "access-key"];</code>
     */
    protected $access_key = '';
    /**
     * Access Type (access_key/password/saml/ldap/k8s/azure_ad/oidc/aws_iam/universal_identity/jwt/gcp/cert)
     *
     * Generated from protobuf field <code>string access_type = 4802047 [json_name = "access-type"];</code>
     */
    protected $access_type = '';
    /**
     * Account id (relevant only for access-type=password where the email address is associated with more than one account)
     *
     * Generated from protobuf field <code>string account_id = 266510150 [json_name = "account-id"];</code>
     */
    protected $account_id = '';
    /**
     * Email (relevant only for access-type=password)
     *
     * Generated from protobuf field <code>string admin_email = 514823268 [json_name = "admin-email"];</code>
     */
    protected $admin_email = '';
    /**
     * Password (relevant only for access-type=password)
     *
     * Generated from protobuf field <code>string admin_password = 147358556 [json_name = "admin-password"];</code>
     */
    protected $admin_password = '';
    /**
     * Certificate data encoded in base64. Used if file was not provided. (relevant only for access-type=cert)
     *
     * Generated from protobuf field <code>string cert_data = 378585679 [json_name = "cert-data"];</code>
     */
    protected $cert_data = '';
    /**
     * The cloud identity (relevant only for access-type=azure_ad,aws_iam,gcp)
     *
     * Generated from protobuf field <code>string cloud_id = 20852661 [json_name = "cloud-id"];</code>
     */
    protected $cloud_id = '';
    /**
     * Generated from protobuf field <code>bool debug = 95458899 [json_name = "debug"];</code>
     */
    protected $debug = false;
    /**
     * Gateway URL for the K8S/OAUTH2 authenticated (relevant only for access-type=k8s/oauth2)
     *
     * Generated from protobuf field <code>string gateway_url = 436486554 [json_name = "gateway-url"];</code>
     */
    protected $gateway_url = '';
    /**
     * GCP JWT audience
     *
     * Generated from protobuf field <code>string gcp_audience = 147155812 [json_name = "gcp-audience"];</code>
     */
    protected $gcp_audience = '';
    /**
     * Set output format to JSON
     *
     * Generated from protobuf field <code>bool json = 3271912 [json_name = "json"];</code>
     */
    protected $json = false;
    /**
     * The Json Web Token (relevant only for access-type=jwt/oidc)
     *
     * Generated from protobuf field <code>string jwt = 105671 [json_name = "jwt"];</code>
     */
    protected $jwt = '';
    /**
     * The K8S Auth config name (relevant only for access-type=k8s)
     *
     * Generated from protobuf field <code>string k8s_auth_config_name = 152509339 [json_name = "k8s-auth-config-name"];</code>
     */
    protected $k8s_auth_config_name = '';
    /**
     * The K8S service account token. (relevant only for access-type=k8s)
     *
     * Generated from protobuf field <code>string k8s_service_account_token = 84004969 [json_name = "k8s-service-account-token"];</code>
     */
    protected $k8s_service_account_token = '';
    /**
     * Private key data encoded in base64. Used if file was not provided.(relevant only for access-type=cert)
     *
     * Generated from protobuf field <code>string key_data = 454465112 [json_name = "key-data"];</code>
     */
    protected $key_data = '';
    /**
     * LDAP password (relevant only for access-type=ldap)
     *
     * Generated from protobuf field <code>string ldap_password = 425950260 [json_name = "ldap_password"];</code>
     */
    protected $ldap_password = '';
    /**
     * LDAP username (relevant only for access-type=ldap)
     *
     * Generated from protobuf field <code>string ldap_username = 519878034 [json_name = "ldap_username"];</code>
     */
    protected $ldap_username = '';
    /**
     * The type of the OCI configuration to use [instance/apikey/resource] (relevant only for access-type=oci)
     *
     * Generated from protobuf field <code>string oci_auth_type = 74705531 [json_name = "oci-auth-type"];</code>
     */
    protected $oci_auth_type = '';
    /**
     * A list of Oracle Cloud IDs groups (relevant only for access-type=oci)
     *
     * Generated from protobuf field <code>repeated string oci_group_ocid = 376141772 [json_name = "oci-group-ocid"];</code>
     */
    private $oci_group_ocid;
    /**
     * The universal_identity token (relevant only for access-type=universal_identity)
     *
     * Generated from protobuf field <code>string uid_token = 247175864 [json_name = "uid_token"];</code>
     */
    protected $uid_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $access_id
     *           Access ID
     *     @type string $access_key
     *           Access key (relevant only for access-type=access_key)
     *     @type string $access_type
     *           Access Type (access_key/password/saml/ldap/k8s/azure_ad/oidc/aws_iam/universal_identity/jwt/gcp/cert)
     *     @type string $account_id
     *           Account id (relevant only for access-type=password where the email address is associated with more than one account)
     *     @type string $admin_email
     *           Email (relevant only for access-type=password)
     *     @type string $admin_password
     *           Password (relevant only for access-type=password)
     *     @type string $cert_data
     *           Certificate data encoded in base64. Used if file was not provided. (relevant only for access-type=cert)
     *     @type string $cloud_id
     *           The cloud identity (relevant only for access-type=azure_ad,aws_iam,gcp)
     *     @type bool $debug
     *     @type string $gateway_url
     *           Gateway URL for the K8S/OAUTH2 authenticated (relevant only for access-type=k8s/oauth2)
     *     @type string $gcp_audience
     *           GCP JWT audience
     *     @type bool $json
     *           Set output format to JSON
     *     @type string $jwt
     *           The Json Web Token (relevant only for access-type=jwt/oidc)
     *     @type string $k8s_auth_config_name
     *           The K8S Auth config name (relevant only for access-type=k8s)
     *     @type string $k8s_service_account_token
     *           The K8S service account token. (relevant only for access-type=k8s)
     *     @type string $key_data
     *           Private key data encoded in base64. Used if file was not provided.(relevant only for access-type=cert)
     *     @type string $ldap_password
     *           LDAP password (relevant only for access-type=ldap)
     *     @type string $ldap_username
     *           LDAP username (relevant only for access-type=ldap)
     *     @type string $oci_auth_type
     *           The type of the OCI configuration to use [instance/apikey/resource] (relevant only for access-type=oci)
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $oci_group_ocid
     *           A list of Oracle Cloud IDs groups (relevant only for access-type=oci)
     *     @type string $uid_token
     *           The universal_identity token (relevant only for access-type=universal_identity)
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\Auth::initOnce();
        parent::__construct($data);
    }

    /**
     * Access ID
     *
     * Generated from protobuf field <code>string access_id = 504474079 [json_name = "access-id"];</code>
     * @return string
     */
    public function getAccessId()
    {
        return $this->access_id;
    }

    /**
     * Access ID
     *
     * Generated from protobuf field <code>string access_id = 504474079 [json_name = "access-id"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccessId($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_id = $var;

        return $this;
    }

    /**
     * Access key (relevant only for access-type=access_key)
     *
     * Generated from protobuf field <code>string access_key = 69437836 [json_name = "access-key"];</code>
     * @return string
     */
    public function getAccessKey()
    {
        return $this->access_key;
    }

    /**
     * Access key (relevant only for access-type=access_key)
     *
     * Generated from protobuf field <code>string access_key = 69437836 [json_name = "access-key"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccessKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_key = $var;

        return $this;
    }

    /**
     * Access Type (access_key/password/saml/ldap/k8s/azure_ad/oidc/aws_iam/universal_identity/jwt/gcp/cert)
     *
     * Generated from protobuf field <code>string access_type = 4802047 [json_name = "access-type"];</code>
     * @return string
     */
    public function getAccessType()
    {
        return $this->access_type;
    }

    /**
     * Access Type (access_key/password/saml/ldap/k8s/azure_ad/oidc/aws_iam/universal_identity/jwt/gcp/cert)
     *
     * Generated from protobuf field <code>string access_type = 4802047 [json_name = "access-type"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccessType($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_type = $var;

        return $this;
    }

    /**
     * Account id (relevant only for access-type=password where the email address is associated with more than one account)
     *
     * Generated from protobuf field <code>string account_id = 266510150 [json_name = "account-id"];</code>
     * @return string
     */
    public function getAccountId()
    {
        return $this->account_id;
    }

    /**
     * Account id (relevant only for access-type=password where the email address is associated with more than one account)
     *
     * Generated from protobuf field <code>string account_id = 266510150 [json_name = "account-id"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccountId($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_id = $var;

        return $this;
    }

    /**
     * Email (relevant only for access-type=password)
     *
     * Generated from protobuf field <code>string admin_email = 514823268 [json_name = "admin-email"];</code>
     * @return string
     */
    public function getAdminEmail()
    {
        return $this->admin_email;
    }

    /**
     * Email (relevant only for access-type=password)
     *
     * Generated from protobuf field <code>string admin_email = 514823268 [json_name = "admin-email"];</code>
     * @param string $var
     * @return $this
     */
    public function setAdminEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->admin_email = $var;

        return $this;
    }

    /**
     * Password (relevant only for access-type=password)
     *
     * Generated from protobuf field <code>string admin_password = 147358556 [json_name = "admin-password"];</code>
     * @return string
     */
    public function getAdminPassword()
    {
        return $this->admin_password;
    }

    /**
     * Password (relevant only for access-type=password)
     *
     * Generated from protobuf field <code>string admin_password = 147358556 [json_name = "admin-password"];</code>
     * @param string $var
     * @return $this
     */
    public function setAdminPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->admin_password = $var;

        return $this;
    }

    /**
     * Certificate data encoded in base64. Used if file was not provided. (relevant only for access-type=cert)
     *
     * Generated from protobuf field <code>string cert_data = 378585679 [json_name = "cert-data"];</code>
     * @return string
     */
    public function getCertData()
    {
        return $this->cert_data;
    }

    /**
     * Certificate data encoded in base64. Used if file was not provided. (relevant only for access-type=cert)
     *
     * Generated from protobuf field <code>string cert_data = 378585679 [json_name = "cert-data"];</code>
     * @param string $var
     * @return $this
     */
    public function setCertData($var)
    {
        GPBUtil::checkString($var, True);
        $this->cert_data = $var;

        return $this;
    }

    /**
     * The cloud identity (relevant only for access-type=azure_ad,aws_iam,gcp)
     *
     * Generated from protobuf field <code>string cloud_id = 20852661 [json_name = "cloud-id"];</code>
     * @return string
     */
    public function getCloudId()
    {
        return $this->cloud_id;
    }

    /**
     * The cloud identity (relevant only for access-type=azure_ad,aws_iam,gcp)
     *
     * Generated from protobuf field <code>string cloud_id = 20852661 [json_name = "cloud-id"];</code>
     * @param string $var
     * @return $this
     */
    public function setCloudId($var)
    {
        GPBUtil::checkString($var, True);
        $this->cloud_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool debug = 95458899 [json_name = "debug"];</code>
     * @return bool
     */
    public function getDebug()
    {
        return $this->debug;
    }

    /**
     * Generated from protobuf field <code>bool debug = 95458899 [json_name = "debug"];</code>
     * @param bool $var
     * @return $this
     */
    public function setDebug($var)
    {
        GPBUtil::checkBool($var);
        $this->debug = $var;

        return $this;
    }

    /**
     * Gateway URL for the K8S/OAUTH2 authenticated (relevant only for access-type=k8s/oauth2)
     *
     * Generated from protobuf field <code>string gateway_url = 436486554 [json_name = "gateway-url"];</code>
     * @return string
     */
    public function getGatewayUrl()
    {
        return $this->gateway_url;
    }

    /**
     * Gateway URL for the K8S/OAUTH2 authenticated (relevant only for access-type=k8s/oauth2)
     *
     * Generated from protobuf field <code>string gateway_url = 436486554 [json_name = "gateway-url"];</code>
     * @param string $var
     * @return $this
     */
    public function setGatewayUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->gateway_url = $var;

        return $this;
    }

    /**
     * GCP JWT audience
     *
     * Generated from protobuf field <code>string gcp_audience = 147155812 [json_name = "gcp-audience"];</code>
     * @return string
     */
    public function getGcpAudience()
    {
        return $this->gcp_audience;
    }

    /**
     * GCP JWT audience
     *
     * Generated from protobuf field <code>string gcp_audience = 147155812 [json_name = "gcp-audience"];</code>
     * @param string $var
     * @return $this
     */
    public function setGcpAudience($var)
    {
        GPBUtil::checkString($var, True);
        $this->gcp_audience = $var;

        return $this;
    }

    /**
     * Set output format to JSON
     *
     * Generated from protobuf field <code>bool json = 3271912 [json_name = "json"];</code>
     * @return bool
     */
    public function getJson()
    {
        return $this->json;
    }

    /**
     * Set output format to JSON
     *
     * Generated from protobuf field <code>bool json = 3271912 [json_name = "json"];</code>
     * @param bool $var
     * @return $this
     */
    public function setJson($var)
    {
        GPBUtil::checkBool($var);
        $this->json = $var;

        return $this;
    }

    /**
     * The Json Web Token (relevant only for access-type=jwt/oidc)
     *
     * Generated from protobuf field <code>string jwt = 105671 [json_name = "jwt"];</code>
     * @return string
     */
    public function getJwt()
    {
        return $this->jwt;
    }

    /**
     * The Json Web Token (relevant only for access-type=jwt/oidc)
     *
     * Generated from protobuf field <code>string jwt = 105671 [json_name = "jwt"];</code>
     * @param string $var
     * @return $this
     */
    public function setJwt($var)
    {
        GPBUtil::checkString($var, True);
        $this->jwt = $var;

        return $this;
    }

    /**
     * The K8S Auth config name (relevant only for access-type=k8s)
     *
     * Generated from protobuf field <code>string k8s_auth_config_name = 152509339 [json_name = "k8s-auth-config-name"];</code>
     * @return string
     */
    public function getK8SAuthConfigName()
    {
        return $this->k8s_auth_config_name;
    }

    /**
     * The K8S Auth config name (relevant only for access-type=k8s)
     *
     * Generated from protobuf field <code>string k8s_auth_config_name = 152509339 [json_name = "k8s-auth-config-name"];</code>
     * @param string $var
     * @return $this
     */
    public function setK8SAuthConfigName($var)
    {
        GPBUtil::checkString($var, True);
        $this->k8s_auth_config_name = $var;

        return $this;
    }

    /**
     * The K8S service account token. (relevant only for access-type=k8s)
     *
     * Generated from protobuf field <code>string k8s_service_account_token = 84004969 [json_name = "k8s-service-account-token"];</code>
     * @return string
     */
    public function getK8SServiceAccountToken()
    {
        return $this->k8s_service_account_token;
    }

    /**
     * The K8S service account token. (relevant only for access-type=k8s)
     *
     * Generated from protobuf field <code>string k8s_service_account_token = 84004969 [json_name = "k8s-service-account-token"];</code>
     * @param string $var
     * @return $this
     */
    public function setK8SServiceAccountToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->k8s_service_account_token = $var;

        return $this;
    }

    /**
     * Private key data encoded in base64. Used if file was not provided.(relevant only for access-type=cert)
     *
     * Generated from protobuf field <code>string key_data = 454465112 [json_name = "key-data"];</code>
     * @return string
     */
    public function getKeyData()
    {
        return $this->key_data;
    }

    /**
     * Private key data encoded in base64. Used if file was not provided.(relevant only for access-type=cert)
     *
     * Generated from protobuf field <code>string key_data = 454465112 [json_name = "key-data"];</code>
     * @param string $var
     * @return $this
     */
    public function setKeyData($var)
    {
        GPBUtil::checkString($var, True);
        $this->key_data = $var;

        return $this;
    }

    /**
     * LDAP password (relevant only for access-type=ldap)
     *
     * Generated from protobuf field <code>string ldap_password = 425950260 [json_name = "ldap_password"];</code>
     * @return string
     */
    public function getLdapPassword()
    {
        return $this->ldap_password;
    }

    /**
     * LDAP password (relevant only for access-type=ldap)
     *
     * Generated from protobuf field <code>string ldap_password = 425950260 [json_name = "ldap_password"];</code>
     * @param string $var
     * @return $this
     */
    public function setLdapPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->ldap_password = $var;

        return $this;
    }

    /**
     * LDAP username (relevant only for access-type=ldap)
     *
     * Generated from protobuf field <code>string ldap_username = 519878034 [json_name = "ldap_username"];</code>
     * @return string
     */
    public function getLdapUsername()
    {
        return $this->ldap_username;
    }

    /**
     * LDAP username (relevant only for access-type=ldap)
     *
     * Generated from protobuf field <code>string ldap_username = 519878034 [json_name = "ldap_username"];</code>
     * @param string $var
     * @return $this
     */
    public function setLdapUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->ldap_username = $var;

        return $this;
    }

    /**
     * The type of the OCI configuration to use [instance/apikey/resource] (relevant only for access-type=oci)
     *
     * Generated from protobuf field <code>string oci_auth_type = 74705531 [json_name = "oci-auth-type"];</code>
     * @return string
     */
    public function getOciAuthType()
    {
        return $this->oci_auth_type;
    }

    /**
     * The type of the OCI configuration to use [instance/apikey/resource] (relevant only for access-type=oci)
     *
     * Generated from protobuf field <code>string oci_auth_type = 74705531 [json_name = "oci-auth-type"];</code>
     * @param string $var
     * @return $this
     */
    public function setOciAuthType($var)
    {
        GPBUtil::checkString($var, True);
        $this->oci_auth_type = $var;

        return $this;
    }

    /**
     * A list of Oracle Cloud IDs groups (relevant only for access-type=oci)
     *
     * Generated from protobuf field <code>repeated string oci_group_ocid = 376141772 [json_name = "oci-group-ocid"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOciGroupOcid()
    {
        return $this->oci_group_ocid;
    }

    /**
     * A list of Oracle Cloud IDs groups (relevant only for access-type=oci)
     *
     * Generated from protobuf field <code>repeated string oci_group_ocid = 376141772 [json_name = "oci-group-ocid"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOciGroupOcid($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->oci_group_ocid = $arr;

        return $this;
    }

    /**
     * The universal_identity token (relevant only for access-type=universal_identity)
     *
     * Generated from protobuf field <code>string uid_token = 247175864 [json_name = "uid_token"];</code>
     * @return string
     */
    public function getUidToken()
    {
        return $this->uid_token;
    }

    /**
     * The universal_identity token (relevant only for access-type=universal_identity)
     *
     * Generated from protobuf field <code>string uid_token = 247175864 [json_name = "uid_token"];</code>
     * @param string $var
     * @return $this
     */
    public function setUidToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->uid_token = $var;

        return $this;
    }

}

