<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/bastion_list_entry.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.BastionListEntry</code>
 */
class BastionListEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string access_id = 504426029 [json_name = "access_id"];</code>
     */
    protected $access_id = '';
    /**
     * Generated from protobuf field <code>repeated string allowed_access_ids = 123902894 [json_name = "allowed_access_ids"];</code>
     */
    private $allowed_access_ids;
    /**
     * Generated from protobuf field <code>repeated string allowed_urls = 334862053 [json_name = "allowed_urls"];</code>
     */
    private $allowed_urls;
    /**
     * Generated from protobuf field <code>map<string, .akeyless_grpc.StringArray> allowed_urls_per_instance = 334566886 [json_name = "allowed_urls_per_instance"];</code>
     */
    private $allowed_urls_per_instance;
    /**
     * Generated from protobuf field <code>string cluster_name = 481210961 [json_name = "cluster_name"];</code>
     */
    protected $cluster_name = '';
    /**
     * Generated from protobuf field <code>string display_name = 4473835 [json_name = "display_name"];</code>
     */
    protected $display_name = '';
    /**
     * Generated from protobuf field <code>string last_report = 382847744 [json_name = "last_report"];</code>
     */
    protected $last_report = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $access_id
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $allowed_access_ids
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $allowed_urls
     *     @type array|\Google\Protobuf\Internal\MapField $allowed_urls_per_instance
     *     @type string $cluster_name
     *     @type string $display_name
     *     @type string $last_report
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\BastionListEntry::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string access_id = 504426029 [json_name = "access_id"];</code>
     * @return string
     */
    public function getAccessId()
    {
        return $this->access_id;
    }

    /**
     * Generated from protobuf field <code>string access_id = 504426029 [json_name = "access_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccessId($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string allowed_access_ids = 123902894 [json_name = "allowed_access_ids"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllowedAccessIds()
    {
        return $this->allowed_access_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string allowed_access_ids = 123902894 [json_name = "allowed_access_ids"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllowedAccessIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->allowed_access_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string allowed_urls = 334862053 [json_name = "allowed_urls"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllowedUrls()
    {
        return $this->allowed_urls;
    }

    /**
     * Generated from protobuf field <code>repeated string allowed_urls = 334862053 [json_name = "allowed_urls"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllowedUrls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->allowed_urls = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .akeyless_grpc.StringArray> allowed_urls_per_instance = 334566886 [json_name = "allowed_urls_per_instance"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAllowedUrlsPerInstance()
    {
        return $this->allowed_urls_per_instance;
    }

    /**
     * Generated from protobuf field <code>map<string, .akeyless_grpc.StringArray> allowed_urls_per_instance = 334566886 [json_name = "allowed_urls_per_instance"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAllowedUrlsPerInstance($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\StringArray::class);
        $this->allowed_urls_per_instance = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cluster_name = 481210961 [json_name = "cluster_name"];</code>
     * @return string
     */
    public function getClusterName()
    {
        return $this->cluster_name;
    }

    /**
     * Generated from protobuf field <code>string cluster_name = 481210961 [json_name = "cluster_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setClusterName($var)
    {
        GPBUtil::checkString($var, True);
        $this->cluster_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string display_name = 4473835 [json_name = "display_name"];</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * Generated from protobuf field <code>string display_name = 4473835 [json_name = "display_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_report = 382847744 [json_name = "last_report"];</code>
     * @return string
     */
    public function getLastReport()
    {
        return $this->last_report;
    }

    /**
     * Generated from protobuf field <code>string last_report = 382847744 [json_name = "last_report"];</code>
     * @param string $var
     * @return $this
     */
    public function setLastReport($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_report = $var;

        return $this;
    }

}

