<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/certificate_info.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.CertificateInfo</code>
 */
class CertificateInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated int64 ext_key_usage = 197199965 [json_name = "ExtKeyUsage"];</code>
     */
    private $ext_key_usage;
    /**
     * KeyUsage represents the set of actions that are valid for a given key. It's a bitmap of the KeyUsage* constants.
     *
     * Generated from protobuf field <code>int64 key_usage = 19625635 [json_name = "KeyUsage"];</code>
     */
    protected $key_usage = 0;
    /**
     * Generated from protobuf field <code>repeated string crl_distribution_points = 30610022 [json_name = "crl_distribution_points"];</code>
     */
    private $crl_distribution_points;
    /**
     * Generated from protobuf field <code>repeated string dns_names = 113148750 [json_name = "dns_names"];</code>
     */
    private $dns_names;
    /**
     * Generated from protobuf field <code>repeated string email_addresses = 228659522 [json_name = "email_addresses"];</code>
     */
    private $email_addresses;
    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.Extension extensions = 198808559 [json_name = "extensions"];</code>
     */
    private $extensions;
    /**
     * Generated from protobuf field <code>repeated string ip_addresses = 122453643 [json_name = "ip_addresses"];</code>
     */
    private $ip_addresses;
    /**
     * Generated from protobuf field <code>bool is_ca = 100490131 [json_name = "is_ca"];</code>
     */
    protected $is_ca = false;
    /**
     * Generated from protobuf field <code>.akeyless_grpc.Name issuer = 105418057 [json_name = "issuer"];</code>
     */
    protected $issuer = null;
    /**
     * Generated from protobuf field <code>repeated string issuing_certificate_url = 108425183 [json_name = "issuing_certificate_url"];</code>
     */
    private $issuing_certificate_url;
    /**
     * Generated from protobuf field <code>int64 key_size = 501095905 [json_name = "key_size"];</code>
     */
    protected $key_size = 0;
    /**
     * Generated from protobuf field <code>string not_after = 26995 [json_name = "not_after"];</code>
     */
    protected $not_after = '';
    /**
     * Generated from protobuf field <code>string not_before = 508735895 [json_name = "not_before"];</code>
     */
    protected $not_before = '';
    /**
     * Generated from protobuf field <code>repeated string ocsp_server = 532419570 [json_name = "ocsp_server"];</code>
     */
    private $ocsp_server;
    /**
     * Generated from protobuf field <code>string public_key_algorithm_name = 270494767 [json_name = "public_key_algorithm_name"];</code>
     */
    protected $public_key_algorithm_name = '';
    /**
     * Generated from protobuf field <code>string serial_number = 312410100 [json_name = "serial_number"];</code>
     */
    protected $serial_number = '';
    /**
     * Generated from protobuf field <code>string sha_1_fingerprint = 318802045 [json_name = "sha_1_fingerprint"];</code>
     */
    protected $sha_1_fingerprint = '';
    /**
     * Generated from protobuf field <code>string sha_256_fingerprint = 325165213 [json_name = "sha_256_fingerprint"];</code>
     */
    protected $sha_256_fingerprint = '';
    /**
     * Generated from protobuf field <code>string signature = 536713401 [json_name = "signature"];</code>
     */
    protected $signature = '';
    /**
     * Generated from protobuf field <code>string signature_algorithm_name = 14992702 [json_name = "signature_algorithm_name"];</code>
     */
    protected $signature_algorithm_name = '';
    /**
     * Generated from protobuf field <code>.akeyless_grpc.Name subject = 257272535 [json_name = "subject"];</code>
     */
    protected $subject = null;
    /**
     * Generated from protobuf field <code>string subject_public_key = 32403582 [json_name = "subject_public_key"];</code>
     */
    protected $subject_public_key = '';
    /**
     * Generated from protobuf field <code>repeated string uris = 3598471 [json_name = "uris"];</code>
     */
    private $uris;
    /**
     * Generated from protobuf field <code>int64 version = 351608024 [json_name = "version"];</code>
     */
    protected $version = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $ext_key_usage
     *     @type int|string $key_usage
     *           KeyUsage represents the set of actions that are valid for a given key. It's a bitmap of the KeyUsage* constants.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $crl_distribution_points
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $dns_names
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $email_addresses
     *     @type array<\Akeyless\gRPC\Extension>|\Google\Protobuf\Internal\RepeatedField $extensions
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $ip_addresses
     *     @type bool $is_ca
     *     @type \Akeyless\gRPC\Name $issuer
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $issuing_certificate_url
     *     @type int|string $key_size
     *     @type string $not_after
     *     @type string $not_before
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $ocsp_server
     *     @type string $public_key_algorithm_name
     *     @type string $serial_number
     *     @type string $sha_1_fingerprint
     *     @type string $sha_256_fingerprint
     *     @type string $signature
     *     @type string $signature_algorithm_name
     *     @type \Akeyless\gRPC\Name $subject
     *     @type string $subject_public_key
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $uris
     *     @type int|string $version
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\CertificateInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated int64 ext_key_usage = 197199965 [json_name = "ExtKeyUsage"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExtKeyUsage()
    {
        return $this->ext_key_usage;
    }

    /**
     * Generated from protobuf field <code>repeated int64 ext_key_usage = 197199965 [json_name = "ExtKeyUsage"];</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExtKeyUsage($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->ext_key_usage = $arr;

        return $this;
    }

    /**
     * KeyUsage represents the set of actions that are valid for a given key. It's a bitmap of the KeyUsage* constants.
     *
     * Generated from protobuf field <code>int64 key_usage = 19625635 [json_name = "KeyUsage"];</code>
     * @return int|string
     */
    public function getKeyUsage()
    {
        return $this->key_usage;
    }

    /**
     * KeyUsage represents the set of actions that are valid for a given key. It's a bitmap of the KeyUsage* constants.
     *
     * Generated from protobuf field <code>int64 key_usage = 19625635 [json_name = "KeyUsage"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setKeyUsage($var)
    {
        GPBUtil::checkInt64($var);
        $this->key_usage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string crl_distribution_points = 30610022 [json_name = "crl_distribution_points"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCrlDistributionPoints()
    {
        return $this->crl_distribution_points;
    }

    /**
     * Generated from protobuf field <code>repeated string crl_distribution_points = 30610022 [json_name = "crl_distribution_points"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCrlDistributionPoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->crl_distribution_points = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string dns_names = 113148750 [json_name = "dns_names"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDnsNames()
    {
        return $this->dns_names;
    }

    /**
     * Generated from protobuf field <code>repeated string dns_names = 113148750 [json_name = "dns_names"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDnsNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->dns_names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string email_addresses = 228659522 [json_name = "email_addresses"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEmailAddresses()
    {
        return $this->email_addresses;
    }

    /**
     * Generated from protobuf field <code>repeated string email_addresses = 228659522 [json_name = "email_addresses"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEmailAddresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->email_addresses = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.Extension extensions = 198808559 [json_name = "extensions"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.Extension extensions = 198808559 [json_name = "extensions"];</code>
     * @param array<\Akeyless\gRPC\Extension>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExtensions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\Extension::class);
        $this->extensions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string ip_addresses = 122453643 [json_name = "ip_addresses"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIpAddresses()
    {
        return $this->ip_addresses;
    }

    /**
     * Generated from protobuf field <code>repeated string ip_addresses = 122453643 [json_name = "ip_addresses"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIpAddresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ip_addresses = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_ca = 100490131 [json_name = "is_ca"];</code>
     * @return bool
     */
    public function getIsCa()
    {
        return $this->is_ca;
    }

    /**
     * Generated from protobuf field <code>bool is_ca = 100490131 [json_name = "is_ca"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCa($var)
    {
        GPBUtil::checkBool($var);
        $this->is_ca = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.Name issuer = 105418057 [json_name = "issuer"];</code>
     * @return \Akeyless\gRPC\Name|null
     */
    public function getIssuer()
    {
        return $this->issuer;
    }

    public function hasIssuer()
    {
        return isset($this->issuer);
    }

    public function clearIssuer()
    {
        unset($this->issuer);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.Name issuer = 105418057 [json_name = "issuer"];</code>
     * @param \Akeyless\gRPC\Name $var
     * @return $this
     */
    public function setIssuer($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\Name::class);
        $this->issuer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string issuing_certificate_url = 108425183 [json_name = "issuing_certificate_url"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIssuingCertificateUrl()
    {
        return $this->issuing_certificate_url;
    }

    /**
     * Generated from protobuf field <code>repeated string issuing_certificate_url = 108425183 [json_name = "issuing_certificate_url"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIssuingCertificateUrl($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->issuing_certificate_url = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 key_size = 501095905 [json_name = "key_size"];</code>
     * @return int|string
     */
    public function getKeySize()
    {
        return $this->key_size;
    }

    /**
     * Generated from protobuf field <code>int64 key_size = 501095905 [json_name = "key_size"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setKeySize($var)
    {
        GPBUtil::checkInt64($var);
        $this->key_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string not_after = 26995 [json_name = "not_after"];</code>
     * @return string
     */
    public function getNotAfter()
    {
        return $this->not_after;
    }

    /**
     * Generated from protobuf field <code>string not_after = 26995 [json_name = "not_after"];</code>
     * @param string $var
     * @return $this
     */
    public function setNotAfter($var)
    {
        GPBUtil::checkString($var, True);
        $this->not_after = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string not_before = 508735895 [json_name = "not_before"];</code>
     * @return string
     */
    public function getNotBefore()
    {
        return $this->not_before;
    }

    /**
     * Generated from protobuf field <code>string not_before = 508735895 [json_name = "not_before"];</code>
     * @param string $var
     * @return $this
     */
    public function setNotBefore($var)
    {
        GPBUtil::checkString($var, True);
        $this->not_before = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string ocsp_server = 532419570 [json_name = "ocsp_server"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOcspServer()
    {
        return $this->ocsp_server;
    }

    /**
     * Generated from protobuf field <code>repeated string ocsp_server = 532419570 [json_name = "ocsp_server"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOcspServer($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ocsp_server = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string public_key_algorithm_name = 270494767 [json_name = "public_key_algorithm_name"];</code>
     * @return string
     */
    public function getPublicKeyAlgorithmName()
    {
        return $this->public_key_algorithm_name;
    }

    /**
     * Generated from protobuf field <code>string public_key_algorithm_name = 270494767 [json_name = "public_key_algorithm_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setPublicKeyAlgorithmName($var)
    {
        GPBUtil::checkString($var, True);
        $this->public_key_algorithm_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string serial_number = 312410100 [json_name = "serial_number"];</code>
     * @return string
     */
    public function getSerialNumber()
    {
        return $this->serial_number;
    }

    /**
     * Generated from protobuf field <code>string serial_number = 312410100 [json_name = "serial_number"];</code>
     * @param string $var
     * @return $this
     */
    public function setSerialNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->serial_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sha_1_fingerprint = 318802045 [json_name = "sha_1_fingerprint"];</code>
     * @return string
     */
    public function getSha1Fingerprint()
    {
        return $this->sha_1_fingerprint;
    }

    /**
     * Generated from protobuf field <code>string sha_1_fingerprint = 318802045 [json_name = "sha_1_fingerprint"];</code>
     * @param string $var
     * @return $this
     */
    public function setSha1Fingerprint($var)
    {
        GPBUtil::checkString($var, True);
        $this->sha_1_fingerprint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sha_256_fingerprint = 325165213 [json_name = "sha_256_fingerprint"];</code>
     * @return string
     */
    public function getSha256Fingerprint()
    {
        return $this->sha_256_fingerprint;
    }

    /**
     * Generated from protobuf field <code>string sha_256_fingerprint = 325165213 [json_name = "sha_256_fingerprint"];</code>
     * @param string $var
     * @return $this
     */
    public function setSha256Fingerprint($var)
    {
        GPBUtil::checkString($var, True);
        $this->sha_256_fingerprint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string signature = 536713401 [json_name = "signature"];</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>string signature = 536713401 [json_name = "signature"];</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, True);
        $this->signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string signature_algorithm_name = 14992702 [json_name = "signature_algorithm_name"];</code>
     * @return string
     */
    public function getSignatureAlgorithmName()
    {
        return $this->signature_algorithm_name;
    }

    /**
     * Generated from protobuf field <code>string signature_algorithm_name = 14992702 [json_name = "signature_algorithm_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setSignatureAlgorithmName($var)
    {
        GPBUtil::checkString($var, True);
        $this->signature_algorithm_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.Name subject = 257272535 [json_name = "subject"];</code>
     * @return \Akeyless\gRPC\Name|null
     */
    public function getSubject()
    {
        return $this->subject;
    }

    public function hasSubject()
    {
        return isset($this->subject);
    }

    public function clearSubject()
    {
        unset($this->subject);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.Name subject = 257272535 [json_name = "subject"];</code>
     * @param \Akeyless\gRPC\Name $var
     * @return $this
     */
    public function setSubject($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\Name::class);
        $this->subject = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subject_public_key = 32403582 [json_name = "subject_public_key"];</code>
     * @return string
     */
    public function getSubjectPublicKey()
    {
        return $this->subject_public_key;
    }

    /**
     * Generated from protobuf field <code>string subject_public_key = 32403582 [json_name = "subject_public_key"];</code>
     * @param string $var
     * @return $this
     */
    public function setSubjectPublicKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject_public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string uris = 3598471 [json_name = "uris"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUris()
    {
        return $this->uris;
    }

    /**
     * Generated from protobuf field <code>repeated string uris = 3598471 [json_name = "uris"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUris($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->uris = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 version = 351608024 [json_name = "version"];</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int64 version = 351608024 [json_name = "version"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->version = $var;

        return $this;
    }

}

