<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/certificate_chain_info.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.CertificateChainInfo</code>
 */
class CertificateChainInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.CertificateInfo certificate_chain = 508056040 [json_name = "certificate_chain"];</code>
     */
    private $certificate_chain;
    /**
     * Generated from protobuf field <code>string certificate_format = 449252258 [json_name = "certificate_format"];</code>
     */
    protected $certificate_format = '';
    /**
     * Generated from protobuf field <code>bool certificate_has_private_key = 326181675 [json_name = "certificate_has_private_key"];</code>
     */
    protected $certificate_has_private_key = false;
    /**
     * Generated from protobuf field <code>string certificate_issuer_gw_cluster_url = 16856697 [json_name = "certificate_issuer_gw_cluster_url"];</code>
     */
    protected $certificate_issuer_gw_cluster_url = '';
    /**
     * Generated from protobuf field <code>int64 certificate_issuer_item_id = 321325594 [json_name = "certificate_issuer_item_id"];</code>
     */
    protected $certificate_issuer_item_id = 0;
    /**
     * Generated from protobuf field <code>string certificate_issuer_name = 385450410 [json_name = "certificate_issuer_name"];</code>
     */
    protected $certificate_issuer_name = '';
    /**
     * Generated from protobuf field <code>string certificate_pem = 380404113 [json_name = "certificate_pem"];</code>
     */
    protected $certificate_pem = '';
    /**
     * Generated from protobuf field <code>string certificate_status = 248192105 [json_name = "certificate_status"];</code>
     */
    protected $certificate_status = '';
    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.CertificateExpirationEvent expiration_events = 290914138 [json_name = "expiration_events"];</code>
     */
    private $expiration_events;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Akeyless\gRPC\CertificateInfo>|\Google\Protobuf\Internal\RepeatedField $certificate_chain
     *     @type string $certificate_format
     *     @type bool $certificate_has_private_key
     *     @type string $certificate_issuer_gw_cluster_url
     *     @type int|string $certificate_issuer_item_id
     *     @type string $certificate_issuer_name
     *     @type string $certificate_pem
     *     @type string $certificate_status
     *     @type array<\Akeyless\gRPC\CertificateExpirationEvent>|\Google\Protobuf\Internal\RepeatedField $expiration_events
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\CertificateChainInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.CertificateInfo certificate_chain = 508056040 [json_name = "certificate_chain"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCertificateChain()
    {
        return $this->certificate_chain;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.CertificateInfo certificate_chain = 508056040 [json_name = "certificate_chain"];</code>
     * @param array<\Akeyless\gRPC\CertificateInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCertificateChain($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\CertificateInfo::class);
        $this->certificate_chain = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string certificate_format = 449252258 [json_name = "certificate_format"];</code>
     * @return string
     */
    public function getCertificateFormat()
    {
        return $this->certificate_format;
    }

    /**
     * Generated from protobuf field <code>string certificate_format = 449252258 [json_name = "certificate_format"];</code>
     * @param string $var
     * @return $this
     */
    public function setCertificateFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->certificate_format = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool certificate_has_private_key = 326181675 [json_name = "certificate_has_private_key"];</code>
     * @return bool
     */
    public function getCertificateHasPrivateKey()
    {
        return $this->certificate_has_private_key;
    }

    /**
     * Generated from protobuf field <code>bool certificate_has_private_key = 326181675 [json_name = "certificate_has_private_key"];</code>
     * @param bool $var
     * @return $this
     */
    public function setCertificateHasPrivateKey($var)
    {
        GPBUtil::checkBool($var);
        $this->certificate_has_private_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string certificate_issuer_gw_cluster_url = 16856697 [json_name = "certificate_issuer_gw_cluster_url"];</code>
     * @return string
     */
    public function getCertificateIssuerGwClusterUrl()
    {
        return $this->certificate_issuer_gw_cluster_url;
    }

    /**
     * Generated from protobuf field <code>string certificate_issuer_gw_cluster_url = 16856697 [json_name = "certificate_issuer_gw_cluster_url"];</code>
     * @param string $var
     * @return $this
     */
    public function setCertificateIssuerGwClusterUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->certificate_issuer_gw_cluster_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 certificate_issuer_item_id = 321325594 [json_name = "certificate_issuer_item_id"];</code>
     * @return int|string
     */
    public function getCertificateIssuerItemId()
    {
        return $this->certificate_issuer_item_id;
    }

    /**
     * Generated from protobuf field <code>int64 certificate_issuer_item_id = 321325594 [json_name = "certificate_issuer_item_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setCertificateIssuerItemId($var)
    {
        GPBUtil::checkInt64($var);
        $this->certificate_issuer_item_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string certificate_issuer_name = 385450410 [json_name = "certificate_issuer_name"];</code>
     * @return string
     */
    public function getCertificateIssuerName()
    {
        return $this->certificate_issuer_name;
    }

    /**
     * Generated from protobuf field <code>string certificate_issuer_name = 385450410 [json_name = "certificate_issuer_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setCertificateIssuerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->certificate_issuer_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string certificate_pem = 380404113 [json_name = "certificate_pem"];</code>
     * @return string
     */
    public function getCertificatePem()
    {
        return $this->certificate_pem;
    }

    /**
     * Generated from protobuf field <code>string certificate_pem = 380404113 [json_name = "certificate_pem"];</code>
     * @param string $var
     * @return $this
     */
    public function setCertificatePem($var)
    {
        GPBUtil::checkString($var, True);
        $this->certificate_pem = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string certificate_status = 248192105 [json_name = "certificate_status"];</code>
     * @return string
     */
    public function getCertificateStatus()
    {
        return $this->certificate_status;
    }

    /**
     * Generated from protobuf field <code>string certificate_status = 248192105 [json_name = "certificate_status"];</code>
     * @param string $var
     * @return $this
     */
    public function setCertificateStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->certificate_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.CertificateExpirationEvent expiration_events = 290914138 [json_name = "expiration_events"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExpirationEvents()
    {
        return $this->expiration_events;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.CertificateExpirationEvent expiration_events = 290914138 [json_name = "expiration_events"];</code>
     * @param array<\Akeyless\gRPC\CertificateExpirationEvent>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExpirationEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\CertificateExpirationEvent::class);
        $this->expiration_events = $arr;

        return $this;
    }

}

