<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/certificate_expiration_event.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.CertificateExpirationEvent</code>
 */
class CertificateExpirationEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 seconds_before = 200608449 [json_name = "seconds_before"];</code>
     */
    protected $seconds_before = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $seconds_before
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\CertificateExpirationEvent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 seconds_before = 200608449 [json_name = "seconds_before"];</code>
     * @return int|string
     */
    public function getSecondsBefore()
    {
        return $this->seconds_before;
    }

    /**
     * Generated from protobuf field <code>int64 seconds_before = 200608449 [json_name = "seconds_before"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setSecondsBefore($var)
    {
        GPBUtil::checkInt64($var);
        $this->seconds_before = $var;

        return $this;
    }

}

