<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/certificate_version_info.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.CertificateVersionInfo</code>
 */
class CertificateVersionInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string not_after = 26995 [json_name = "not_after"];</code>
     */
    protected $not_after = '';
    /**
     * Generated from protobuf field <code>string not_before = 508735895 [json_name = "not_before"];</code>
     */
    protected $not_before = '';
    /**
     * Generated from protobuf field <code>string status = 355610639 [json_name = "status"];</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $not_after
     *     @type string $not_before
     *     @type string $status
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\CertificateVersionInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string not_after = 26995 [json_name = "not_after"];</code>
     * @return string
     */
    public function getNotAfter()
    {
        return $this->not_after;
    }

    /**
     * Generated from protobuf field <code>string not_after = 26995 [json_name = "not_after"];</code>
     * @param string $var
     * @return $this
     */
    public function setNotAfter($var)
    {
        GPBUtil::checkString($var, True);
        $this->not_after = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string not_before = 508735895 [json_name = "not_before"];</code>
     * @return string
     */
    public function getNotBefore()
    {
        return $this->not_before;
    }

    /**
     * Generated from protobuf field <code>string not_before = 508735895 [json_name = "not_before"];</code>
     * @param string $var
     * @return $this
     */
    public function setNotBefore($var)
    {
        GPBUtil::checkString($var, True);
        $this->not_before = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 355610639 [json_name = "status"];</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 355610639 [json_name = "status"];</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

}

