<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/classic_key_details_info.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.ClassicKeyDetailsInfo</code>
 */
class ClassicKeyDetailsInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .akeyless_grpc.StringArray> classic_key_attributes = 225657212 [json_name = "classic_key_attributes"];</code>
     */
    private $classic_key_attributes;
    /**
     * Generated from protobuf field <code>string classic_key_id = 66478265 [json_name = "classic_key_id"];</code>
     */
    protected $classic_key_id = '';
    /**
     * Generated from protobuf field <code>int64 gw_cluster_id = 109299666 [json_name = "gw_cluster_id"];</code>
     */
    protected $gw_cluster_id = 0;
    /**
     * Generated from protobuf field <code>bool has_certificate = 363586705 [json_name = "has_certificate"];</code>
     */
    protected $has_certificate = false;
    /**
     * Generated from protobuf field <code>bool is_provided_by_user = 135257807 [json_name = "is_provided_by_user"];</code>
     */
    protected $is_provided_by_user = false;
    /**
     * Generated from protobuf field <code>bool is_unexportable = 523412318 [json_name = "is_unexportable"];</code>
     */
    protected $is_unexportable = false;
    /**
     * ItemState defines the different states an Item can be in
     *
     * Generated from protobuf field <code>string key_state = 34979154 [json_name = "key_state"];</code>
     */
    protected $key_state = '';
    /**
     * Generated from protobuf field <code>string key_type = 501140762 [json_name = "key_type"];</code>
     */
    protected $key_type = '';
    /**
     * Generated from protobuf field <code>string last_error = 414908644 [json_name = "last_error"];</code>
     */
    protected $last_error = '';
    /**
     * Generated from protobuf field <code>string public_key = 294200204 [json_name = "public_key"];</code>
     */
    protected $public_key = '';
    /**
     * Generated from protobuf field <code>string target_alias_helper = 433485718 [json_name = "target_alias_helper"];</code>
     */
    protected $target_alias_helper = '';
    /**
     * Generated from protobuf field <code>repeated string target_types = 196805557 [json_name = "target_types"];</code>
     */
    private $target_types;
    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.ClassicKeyTargetInfo targets = 464535296 [json_name = "targets"];</code>
     */
    private $targets;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $classic_key_attributes
     *     @type string $classic_key_id
     *     @type int|string $gw_cluster_id
     *     @type bool $has_certificate
     *     @type bool $is_provided_by_user
     *     @type bool $is_unexportable
     *     @type string $key_state
     *           ItemState defines the different states an Item can be in
     *     @type string $key_type
     *     @type string $last_error
     *     @type string $public_key
     *     @type string $target_alias_helper
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $target_types
     *     @type array<\Akeyless\gRPC\ClassicKeyTargetInfo>|\Google\Protobuf\Internal\RepeatedField $targets
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\ClassicKeyDetailsInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .akeyless_grpc.StringArray> classic_key_attributes = 225657212 [json_name = "classic_key_attributes"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getClassicKeyAttributes()
    {
        return $this->classic_key_attributes;
    }

    /**
     * Generated from protobuf field <code>map<string, .akeyless_grpc.StringArray> classic_key_attributes = 225657212 [json_name = "classic_key_attributes"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setClassicKeyAttributes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\StringArray::class);
        $this->classic_key_attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string classic_key_id = 66478265 [json_name = "classic_key_id"];</code>
     * @return string
     */
    public function getClassicKeyId()
    {
        return $this->classic_key_id;
    }

    /**
     * Generated from protobuf field <code>string classic_key_id = 66478265 [json_name = "classic_key_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setClassicKeyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->classic_key_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 gw_cluster_id = 109299666 [json_name = "gw_cluster_id"];</code>
     * @return int|string
     */
    public function getGwClusterId()
    {
        return $this->gw_cluster_id;
    }

    /**
     * Generated from protobuf field <code>int64 gw_cluster_id = 109299666 [json_name = "gw_cluster_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setGwClusterId($var)
    {
        GPBUtil::checkInt64($var);
        $this->gw_cluster_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool has_certificate = 363586705 [json_name = "has_certificate"];</code>
     * @return bool
     */
    public function getHasCertificate()
    {
        return $this->has_certificate;
    }

    /**
     * Generated from protobuf field <code>bool has_certificate = 363586705 [json_name = "has_certificate"];</code>
     * @param bool $var
     * @return $this
     */
    public function setHasCertificate($var)
    {
        GPBUtil::checkBool($var);
        $this->has_certificate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_provided_by_user = 135257807 [json_name = "is_provided_by_user"];</code>
     * @return bool
     */
    public function getIsProvidedByUser()
    {
        return $this->is_provided_by_user;
    }

    /**
     * Generated from protobuf field <code>bool is_provided_by_user = 135257807 [json_name = "is_provided_by_user"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsProvidedByUser($var)
    {
        GPBUtil::checkBool($var);
        $this->is_provided_by_user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_unexportable = 523412318 [json_name = "is_unexportable"];</code>
     * @return bool
     */
    public function getIsUnexportable()
    {
        return $this->is_unexportable;
    }

    /**
     * Generated from protobuf field <code>bool is_unexportable = 523412318 [json_name = "is_unexportable"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsUnexportable($var)
    {
        GPBUtil::checkBool($var);
        $this->is_unexportable = $var;

        return $this;
    }

    /**
     * ItemState defines the different states an Item can be in
     *
     * Generated from protobuf field <code>string key_state = 34979154 [json_name = "key_state"];</code>
     * @return string
     */
    public function getKeyState()
    {
        return $this->key_state;
    }

    /**
     * ItemState defines the different states an Item can be in
     *
     * Generated from protobuf field <code>string key_state = 34979154 [json_name = "key_state"];</code>
     * @param string $var
     * @return $this
     */
    public function setKeyState($var)
    {
        GPBUtil::checkString($var, True);
        $this->key_state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key_type = 501140762 [json_name = "key_type"];</code>
     * @return string
     */
    public function getKeyType()
    {
        return $this->key_type;
    }

    /**
     * Generated from protobuf field <code>string key_type = 501140762 [json_name = "key_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setKeyType($var)
    {
        GPBUtil::checkString($var, True);
        $this->key_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_error = 414908644 [json_name = "last_error"];</code>
     * @return string
     */
    public function getLastError()
    {
        return $this->last_error;
    }

    /**
     * Generated from protobuf field <code>string last_error = 414908644 [json_name = "last_error"];</code>
     * @param string $var
     * @return $this
     */
    public function setLastError($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string public_key = 294200204 [json_name = "public_key"];</code>
     * @return string
     */
    public function getPublicKey()
    {
        return $this->public_key;
    }

    /**
     * Generated from protobuf field <code>string public_key = 294200204 [json_name = "public_key"];</code>
     * @param string $var
     * @return $this
     */
    public function setPublicKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_alias_helper = 433485718 [json_name = "target_alias_helper"];</code>
     * @return string
     */
    public function getTargetAliasHelper()
    {
        return $this->target_alias_helper;
    }

    /**
     * Generated from protobuf field <code>string target_alias_helper = 433485718 [json_name = "target_alias_helper"];</code>
     * @param string $var
     * @return $this
     */
    public function setTargetAliasHelper($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_alias_helper = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string target_types = 196805557 [json_name = "target_types"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTargetTypes()
    {
        return $this->target_types;
    }

    /**
     * Generated from protobuf field <code>repeated string target_types = 196805557 [json_name = "target_types"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTargetTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->target_types = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.ClassicKeyTargetInfo targets = 464535296 [json_name = "targets"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTargets()
    {
        return $this->targets;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.ClassicKeyTargetInfo targets = 464535296 [json_name = "targets"];</code>
     * @param array<\Akeyless\gRPC\ClassicKeyTargetInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTargets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\ClassicKeyTargetInfo::class);
        $this->targets = $arr;

        return $this;
    }

}

