<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/classic_key_status_info.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.ClassicKeyStatusInfo</code>
 */
class ClassicKeyStatusInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string error_date = 25090952 [json_name = "error_date"];</code>
     */
    protected $error_date = '';
    /**
     * Generated from protobuf field <code>string last_error = 414908644 [json_name = "last_error"];</code>
     */
    protected $last_error = '';
    /**
     * ClassicKeyTargetStatus defines status of classic key target
     *
     * Generated from protobuf field <code>string last_status = 424887742 [json_name = "last_status"];</code>
     */
    protected $last_status = '';
    /**
     * Generated from protobuf field <code>int64 version = 351608024 [json_name = "version"];</code>
     */
    protected $version = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $error_date
     *     @type string $last_error
     *     @type string $last_status
     *           ClassicKeyTargetStatus defines status of classic key target
     *     @type int|string $version
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\ClassicKeyStatusInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string error_date = 25090952 [json_name = "error_date"];</code>
     * @return string
     */
    public function getErrorDate()
    {
        return $this->error_date;
    }

    /**
     * Generated from protobuf field <code>string error_date = 25090952 [json_name = "error_date"];</code>
     * @param string $var
     * @return $this
     */
    public function setErrorDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_error = 414908644 [json_name = "last_error"];</code>
     * @return string
     */
    public function getLastError()
    {
        return $this->last_error;
    }

    /**
     * Generated from protobuf field <code>string last_error = 414908644 [json_name = "last_error"];</code>
     * @param string $var
     * @return $this
     */
    public function setLastError($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_error = $var;

        return $this;
    }

    /**
     * ClassicKeyTargetStatus defines status of classic key target
     *
     * Generated from protobuf field <code>string last_status = 424887742 [json_name = "last_status"];</code>
     * @return string
     */
    public function getLastStatus()
    {
        return $this->last_status;
    }

    /**
     * ClassicKeyTargetStatus defines status of classic key target
     *
     * Generated from protobuf field <code>string last_status = 424887742 [json_name = "last_status"];</code>
     * @param string $var
     * @return $this
     */
    public function setLastStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 version = 351608024 [json_name = "version"];</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int64 version = 351608024 [json_name = "version"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->version = $var;

        return $this;
    }

}

