<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/classic_key_target_info.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.ClassicKeyTargetInfo</code>
 */
class ClassicKeyTargetInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.akeyless_grpc.ExternalKmsKeyId external_kms_id = 344724413 [json_name = "external_kms_id"];</code>
     */
    protected $external_kms_id = null;
    /**
     * Generated from protobuf field <code>repeated string key_purpose = 273969983 [json_name = "key_purpose"];</code>
     */
    private $key_purpose;
    /**
     * Generated from protobuf field <code>.akeyless_grpc.ClassicKeyStatusInfo key_status = 526259666 [json_name = "key_status"];</code>
     */
    protected $key_status = null;
    /**
     * Generated from protobuf field <code>string target_assoc_id = 92961677 [json_name = "target_assoc_id"];</code>
     */
    protected $target_assoc_id = '';
    /**
     * Generated from protobuf field <code>string target_type = 473945819 [json_name = "target_type"];</code>
     */
    protected $target_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Akeyless\gRPC\ExternalKmsKeyId $external_kms_id
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $key_purpose
     *     @type \Akeyless\gRPC\ClassicKeyStatusInfo $key_status
     *     @type string $target_assoc_id
     *     @type string $target_type
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\ClassicKeyTargetInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.ExternalKmsKeyId external_kms_id = 344724413 [json_name = "external_kms_id"];</code>
     * @return \Akeyless\gRPC\ExternalKmsKeyId|null
     */
    public function getExternalKmsId()
    {
        return $this->external_kms_id;
    }

    public function hasExternalKmsId()
    {
        return isset($this->external_kms_id);
    }

    public function clearExternalKmsId()
    {
        unset($this->external_kms_id);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.ExternalKmsKeyId external_kms_id = 344724413 [json_name = "external_kms_id"];</code>
     * @param \Akeyless\gRPC\ExternalKmsKeyId $var
     * @return $this
     */
    public function setExternalKmsId($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\ExternalKmsKeyId::class);
        $this->external_kms_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string key_purpose = 273969983 [json_name = "key_purpose"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeyPurpose()
    {
        return $this->key_purpose;
    }

    /**
     * Generated from protobuf field <code>repeated string key_purpose = 273969983 [json_name = "key_purpose"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeyPurpose($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->key_purpose = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.ClassicKeyStatusInfo key_status = 526259666 [json_name = "key_status"];</code>
     * @return \Akeyless\gRPC\ClassicKeyStatusInfo|null
     */
    public function getKeyStatus()
    {
        return $this->key_status;
    }

    public function hasKeyStatus()
    {
        return isset($this->key_status);
    }

    public function clearKeyStatus()
    {
        unset($this->key_status);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.ClassicKeyStatusInfo key_status = 526259666 [json_name = "key_status"];</code>
     * @param \Akeyless\gRPC\ClassicKeyStatusInfo $var
     * @return $this
     */
    public function setKeyStatus($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\ClassicKeyStatusInfo::class);
        $this->key_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_assoc_id = 92961677 [json_name = "target_assoc_id"];</code>
     * @return string
     */
    public function getTargetAssocId()
    {
        return $this->target_assoc_id;
    }

    /**
     * Generated from protobuf field <code>string target_assoc_id = 92961677 [json_name = "target_assoc_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setTargetAssocId($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_assoc_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_type = 473945819 [json_name = "target_type"];</code>
     * @return string
     */
    public function getTargetType()
    {
        return $this->target_type;
    }

    /**
     * Generated from protobuf field <code>string target_type = 473945819 [json_name = "target_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setTargetType($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_type = $var;

        return $this;
    }

}

