<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/create_secret.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.CreateSecret</code>
 */
class CreateSecret extends \Google\Protobuf\Internal\Message
{
    /**
     * for personal password manager
     *
     * Generated from protobuf field <code>string accessibility = 213139122 [json_name = "accessibility"];</code>
     */
    protected $accessibility = '';
    /**
     * Trigger an event when a secret value changed [true/false] (Relevant only for Static Secret)
     *
     * Generated from protobuf field <code>string change_event = 120187333 [json_name = "change-event"];</code>
     */
    protected $change_event = '';
    /**
     * For Password Management use, additional fields
     *
     * Generated from protobuf field <code>map<string, string> custom_field = 176478307 [json_name = "custom-field"];</code>
     */
    private $custom_field;
    /**
     * Protection from accidental deletion of this object [true/false]
     *
     * Generated from protobuf field <code>string delete_protection = 517947888 [json_name = "delete_protection"];</code>
     */
    protected $delete_protection = '';
    /**
     * Description of the object
     *
     * Generated from protobuf field <code>string description = 113933319 [json_name = "description"];</code>
     */
    protected $description = '';
    /**
     * Secret format [text/json] (relevant only for type 'generic')
     *
     * Generated from protobuf field <code>string format = 195037195 [json_name = "format"];</code>
     */
    protected $format = '';
    /**
     * For Password Management use, reflect the website context
     *
     * Generated from protobuf field <code>repeated string inject_url = 419541814 [json_name = "inject-url"];</code>
     */
    private $inject_url;
    /**
     * Set output format to JSON
     *
     * Generated from protobuf field <code>bool json = 3271912 [json_name = "json"];</code>
     */
    protected $json = false;
    /**
     * Set the maximum number of versions, limited by the account settings defaults.
     *
     * Generated from protobuf field <code>string max_versions = 311546653 [json_name = "max-versions"];</code>
     */
    protected $max_versions = '';
    /**
     * Deprecated - use description
     *
     * Generated from protobuf field <code>string metadata = 450004177 [json_name = "metadata"];</code>
     */
    protected $metadata = '';
    /**
     * The provided value is a multiline value (separated by '\\n')
     *
     * Generated from protobuf field <code>bool multiline_value = 204914851 [json_name = "multiline_value"];</code>
     */
    protected $multiline_value = false;
    /**
     * Secret name
     *
     * Generated from protobuf field <code>string name = 3373707 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * For Password Management use, additional fields
     *
     * Generated from protobuf field <code>string password = 143243933 [json_name = "password"];</code>
     */
    protected $password = '';
    /**
     * The name of a key that used to encrypt the secret value (if empty, the account default protectionKey key will be used)
     *
     * Generated from protobuf field <code>string protection_key = 345297913 [json_name = "protection_key"];</code>
     */
    protected $protection_key = '';
    /**
     * Path to the SSH Certificate Issuer for your Akeyless Bastion
     *
     * Generated from protobuf field <code>string secure_access_bastion_issuer = 471808848 [json_name = "secure-access-bastion-issuer"];</code>
     */
    protected $secure_access_bastion_issuer = '';
    /**
     * Enable/Disable secure remote access [true/false]
     *
     * Generated from protobuf field <code>string secure_access_enable = 19968568 [json_name = "secure-access-enable"];</code>
     */
    protected $secure_access_enable = '';
    /**
     * Target servers for connections (In case of Linked Target association, host(s) will inherit Linked Target hosts - Relevant only for Dynamic Secrets/producers)
     *
     * Generated from protobuf field <code>repeated string secure_access_host = 362681116 [json_name = "secure-access-host"];</code>
     */
    private $secure_access_host;
    /**
     * Remote Desktop Username
     *
     * Generated from protobuf field <code>string secure_access_rdp_user = 66068397 [json_name = "secure-access-rdp-user"];</code>
     */
    protected $secure_access_rdp_user = '';
    /**
     * Static-Secret values contains SSH Credentials, either Private Key or Password [password/private-key]
     *
     * Generated from protobuf field <code>string secure_access_ssh_creds = 475656016 [json_name = "secure-access-ssh-creds"];</code>
     */
    protected $secure_access_ssh_creds = '';
    /**
     * Override the SSH username as indicated in SSH Certificate Issuer
     *
     * Generated from protobuf field <code>string secure_access_ssh_user = 396886118 [json_name = "secure-access-ssh-user"];</code>
     */
    protected $secure_access_ssh_user = '';
    /**
     * Destination URL to inject secrets
     *
     * Generated from protobuf field <code>string secure_access_url = 479309214 [json_name = "secure-access-url"];</code>
     */
    protected $secure_access_url = '';
    /**
     * Secure browser via Akeyless Web Access Bastion
     *
     * Generated from protobuf field <code>bool secure_access_web_browsing = 258508398 [json_name = "secure-access-web-browsing"];</code>
     */
    protected $secure_access_web_browsing = false;
    /**
     * Web-Proxy via Akeyless Web Access Bastion
     *
     * Generated from protobuf field <code>bool secure_access_web_proxy = 496161502 [json_name = "secure-access-web-proxy"];</code>
     */
    protected $secure_access_web_proxy = false;
    /**
     * Add tags attached to this object
     *
     * Generated from protobuf field <code>repeated string tags = 3552281 [json_name = "tags"];</code>
     */
    private $tags;
    /**
     * Authentication token (see `/auth` and `/configure`)
     *
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     */
    protected $token = '';
    /**
     * The secret sub type [generic/password]
     *
     * Generated from protobuf field <code>string type = 3575610 [json_name = "type"];</code>
     */
    protected $type = '';
    /**
     * The universal identity token, Required only for universal_identity authentication
     *
     * Generated from protobuf field <code>string uid_token = 468850238 [json_name = "uid-token"];</code>
     */
    protected $uid_token = '';
    /**
     * For Password Management use
     *
     * Generated from protobuf field <code>string username = 265713450 [json_name = "username"];</code>
     */
    protected $username = '';
    /**
     * The secret value (relevant only for type 'generic')
     *
     * Generated from protobuf field <code>string value = 111972721 [json_name = "value"];</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $accessibility
     *           for personal password manager
     *     @type string $change_event
     *           Trigger an event when a secret value changed [true/false] (Relevant only for Static Secret)
     *     @type array|\Google\Protobuf\Internal\MapField $custom_field
     *           For Password Management use, additional fields
     *     @type string $delete_protection
     *           Protection from accidental deletion of this object [true/false]
     *     @type string $description
     *           Description of the object
     *     @type string $format
     *           Secret format [text/json] (relevant only for type 'generic')
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $inject_url
     *           For Password Management use, reflect the website context
     *     @type bool $json
     *           Set output format to JSON
     *     @type string $max_versions
     *           Set the maximum number of versions, limited by the account settings defaults.
     *     @type string $metadata
     *           Deprecated - use description
     *     @type bool $multiline_value
     *           The provided value is a multiline value (separated by '\\n')
     *     @type string $name
     *           Secret name
     *     @type string $password
     *           For Password Management use, additional fields
     *     @type string $protection_key
     *           The name of a key that used to encrypt the secret value (if empty, the account default protectionKey key will be used)
     *     @type string $secure_access_bastion_issuer
     *           Path to the SSH Certificate Issuer for your Akeyless Bastion
     *     @type string $secure_access_enable
     *           Enable/Disable secure remote access [true/false]
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $secure_access_host
     *           Target servers for connections (In case of Linked Target association, host(s) will inherit Linked Target hosts - Relevant only for Dynamic Secrets/producers)
     *     @type string $secure_access_rdp_user
     *           Remote Desktop Username
     *     @type string $secure_access_ssh_creds
     *           Static-Secret values contains SSH Credentials, either Private Key or Password [password/private-key]
     *     @type string $secure_access_ssh_user
     *           Override the SSH username as indicated in SSH Certificate Issuer
     *     @type string $secure_access_url
     *           Destination URL to inject secrets
     *     @type bool $secure_access_web_browsing
     *           Secure browser via Akeyless Web Access Bastion
     *     @type bool $secure_access_web_proxy
     *           Web-Proxy via Akeyless Web Access Bastion
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $tags
     *           Add tags attached to this object
     *     @type string $token
     *           Authentication token (see `/auth` and `/configure`)
     *     @type string $type
     *           The secret sub type [generic/password]
     *     @type string $uid_token
     *           The universal identity token, Required only for universal_identity authentication
     *     @type string $username
     *           For Password Management use
     *     @type string $value
     *           The secret value (relevant only for type 'generic')
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\CreateSecret::initOnce();
        parent::__construct($data);
    }

    /**
     * for personal password manager
     *
     * Generated from protobuf field <code>string accessibility = 213139122 [json_name = "accessibility"];</code>
     * @return string
     */
    public function getAccessibility()
    {
        return $this->accessibility;
    }

    /**
     * for personal password manager
     *
     * Generated from protobuf field <code>string accessibility = 213139122 [json_name = "accessibility"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccessibility($var)
    {
        GPBUtil::checkString($var, True);
        $this->accessibility = $var;

        return $this;
    }

    /**
     * Trigger an event when a secret value changed [true/false] (Relevant only for Static Secret)
     *
     * Generated from protobuf field <code>string change_event = 120187333 [json_name = "change-event"];</code>
     * @return string
     */
    public function getChangeEvent()
    {
        return $this->change_event;
    }

    /**
     * Trigger an event when a secret value changed [true/false] (Relevant only for Static Secret)
     *
     * Generated from protobuf field <code>string change_event = 120187333 [json_name = "change-event"];</code>
     * @param string $var
     * @return $this
     */
    public function setChangeEvent($var)
    {
        GPBUtil::checkString($var, True);
        $this->change_event = $var;

        return $this;
    }

    /**
     * For Password Management use, additional fields
     *
     * Generated from protobuf field <code>map<string, string> custom_field = 176478307 [json_name = "custom-field"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCustomField()
    {
        return $this->custom_field;
    }

    /**
     * For Password Management use, additional fields
     *
     * Generated from protobuf field <code>map<string, string> custom_field = 176478307 [json_name = "custom-field"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCustomField($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->custom_field = $arr;

        return $this;
    }

    /**
     * Protection from accidental deletion of this object [true/false]
     *
     * Generated from protobuf field <code>string delete_protection = 517947888 [json_name = "delete_protection"];</code>
     * @return string
     */
    public function getDeleteProtection()
    {
        return $this->delete_protection;
    }

    /**
     * Protection from accidental deletion of this object [true/false]
     *
     * Generated from protobuf field <code>string delete_protection = 517947888 [json_name = "delete_protection"];</code>
     * @param string $var
     * @return $this
     */
    public function setDeleteProtection($var)
    {
        GPBUtil::checkString($var, True);
        $this->delete_protection = $var;

        return $this;
    }

    /**
     * Description of the object
     *
     * Generated from protobuf field <code>string description = 113933319 [json_name = "description"];</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Description of the object
     *
     * Generated from protobuf field <code>string description = 113933319 [json_name = "description"];</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Secret format [text/json] (relevant only for type 'generic')
     *
     * Generated from protobuf field <code>string format = 195037195 [json_name = "format"];</code>
     * @return string
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * Secret format [text/json] (relevant only for type 'generic')
     *
     * Generated from protobuf field <code>string format = 195037195 [json_name = "format"];</code>
     * @param string $var
     * @return $this
     */
    public function setFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->format = $var;

        return $this;
    }

    /**
     * For Password Management use, reflect the website context
     *
     * Generated from protobuf field <code>repeated string inject_url = 419541814 [json_name = "inject-url"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInjectUrl()
    {
        return $this->inject_url;
    }

    /**
     * For Password Management use, reflect the website context
     *
     * Generated from protobuf field <code>repeated string inject_url = 419541814 [json_name = "inject-url"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInjectUrl($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->inject_url = $arr;

        return $this;
    }

    /**
     * Set output format to JSON
     *
     * Generated from protobuf field <code>bool json = 3271912 [json_name = "json"];</code>
     * @return bool
     */
    public function getJson()
    {
        return $this->json;
    }

    /**
     * Set output format to JSON
     *
     * Generated from protobuf field <code>bool json = 3271912 [json_name = "json"];</code>
     * @param bool $var
     * @return $this
     */
    public function setJson($var)
    {
        GPBUtil::checkBool($var);
        $this->json = $var;

        return $this;
    }

    /**
     * Set the maximum number of versions, limited by the account settings defaults.
     *
     * Generated from protobuf field <code>string max_versions = 311546653 [json_name = "max-versions"];</code>
     * @return string
     */
    public function getMaxVersions()
    {
        return $this->max_versions;
    }

    /**
     * Set the maximum number of versions, limited by the account settings defaults.
     *
     * Generated from protobuf field <code>string max_versions = 311546653 [json_name = "max-versions"];</code>
     * @param string $var
     * @return $this
     */
    public function setMaxVersions($var)
    {
        GPBUtil::checkString($var, True);
        $this->max_versions = $var;

        return $this;
    }

    /**
     * Deprecated - use description
     *
     * Generated from protobuf field <code>string metadata = 450004177 [json_name = "metadata"];</code>
     * @return string
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Deprecated - use description
     *
     * Generated from protobuf field <code>string metadata = 450004177 [json_name = "metadata"];</code>
     * @param string $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkString($var, True);
        $this->metadata = $var;

        return $this;
    }

    /**
     * The provided value is a multiline value (separated by '\\n')
     *
     * Generated from protobuf field <code>bool multiline_value = 204914851 [json_name = "multiline_value"];</code>
     * @return bool
     */
    public function getMultilineValue()
    {
        return $this->multiline_value;
    }

    /**
     * The provided value is a multiline value (separated by '\\n')
     *
     * Generated from protobuf field <code>bool multiline_value = 204914851 [json_name = "multiline_value"];</code>
     * @param bool $var
     * @return $this
     */
    public function setMultilineValue($var)
    {
        GPBUtil::checkBool($var);
        $this->multiline_value = $var;

        return $this;
    }

    /**
     * Secret name
     *
     * Generated from protobuf field <code>string name = 3373707 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Secret name
     *
     * Generated from protobuf field <code>string name = 3373707 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * For Password Management use, additional fields
     *
     * Generated from protobuf field <code>string password = 143243933 [json_name = "password"];</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * For Password Management use, additional fields
     *
     * Generated from protobuf field <code>string password = 143243933 [json_name = "password"];</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * The name of a key that used to encrypt the secret value (if empty, the account default protectionKey key will be used)
     *
     * Generated from protobuf field <code>string protection_key = 345297913 [json_name = "protection_key"];</code>
     * @return string
     */
    public function getProtectionKey()
    {
        return $this->protection_key;
    }

    /**
     * The name of a key that used to encrypt the secret value (if empty, the account default protectionKey key will be used)
     *
     * Generated from protobuf field <code>string protection_key = 345297913 [json_name = "protection_key"];</code>
     * @param string $var
     * @return $this
     */
    public function setProtectionKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->protection_key = $var;

        return $this;
    }

    /**
     * Path to the SSH Certificate Issuer for your Akeyless Bastion
     *
     * Generated from protobuf field <code>string secure_access_bastion_issuer = 471808848 [json_name = "secure-access-bastion-issuer"];</code>
     * @return string
     */
    public function getSecureAccessBastionIssuer()
    {
        return $this->secure_access_bastion_issuer;
    }

    /**
     * Path to the SSH Certificate Issuer for your Akeyless Bastion
     *
     * Generated from protobuf field <code>string secure_access_bastion_issuer = 471808848 [json_name = "secure-access-bastion-issuer"];</code>
     * @param string $var
     * @return $this
     */
    public function setSecureAccessBastionIssuer($var)
    {
        GPBUtil::checkString($var, True);
        $this->secure_access_bastion_issuer = $var;

        return $this;
    }

    /**
     * Enable/Disable secure remote access [true/false]
     *
     * Generated from protobuf field <code>string secure_access_enable = 19968568 [json_name = "secure-access-enable"];</code>
     * @return string
     */
    public function getSecureAccessEnable()
    {
        return $this->secure_access_enable;
    }

    /**
     * Enable/Disable secure remote access [true/false]
     *
     * Generated from protobuf field <code>string secure_access_enable = 19968568 [json_name = "secure-access-enable"];</code>
     * @param string $var
     * @return $this
     */
    public function setSecureAccessEnable($var)
    {
        GPBUtil::checkString($var, True);
        $this->secure_access_enable = $var;

        return $this;
    }

    /**
     * Target servers for connections (In case of Linked Target association, host(s) will inherit Linked Target hosts - Relevant only for Dynamic Secrets/producers)
     *
     * Generated from protobuf field <code>repeated string secure_access_host = 362681116 [json_name = "secure-access-host"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSecureAccessHost()
    {
        return $this->secure_access_host;
    }

    /**
     * Target servers for connections (In case of Linked Target association, host(s) will inherit Linked Target hosts - Relevant only for Dynamic Secrets/producers)
     *
     * Generated from protobuf field <code>repeated string secure_access_host = 362681116 [json_name = "secure-access-host"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSecureAccessHost($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->secure_access_host = $arr;

        return $this;
    }

    /**
     * Remote Desktop Username
     *
     * Generated from protobuf field <code>string secure_access_rdp_user = 66068397 [json_name = "secure-access-rdp-user"];</code>
     * @return string
     */
    public function getSecureAccessRdpUser()
    {
        return $this->secure_access_rdp_user;
    }

    /**
     * Remote Desktop Username
     *
     * Generated from protobuf field <code>string secure_access_rdp_user = 66068397 [json_name = "secure-access-rdp-user"];</code>
     * @param string $var
     * @return $this
     */
    public function setSecureAccessRdpUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->secure_access_rdp_user = $var;

        return $this;
    }

    /**
     * Static-Secret values contains SSH Credentials, either Private Key or Password [password/private-key]
     *
     * Generated from protobuf field <code>string secure_access_ssh_creds = 475656016 [json_name = "secure-access-ssh-creds"];</code>
     * @return string
     */
    public function getSecureAccessSshCreds()
    {
        return $this->secure_access_ssh_creds;
    }

    /**
     * Static-Secret values contains SSH Credentials, either Private Key or Password [password/private-key]
     *
     * Generated from protobuf field <code>string secure_access_ssh_creds = 475656016 [json_name = "secure-access-ssh-creds"];</code>
     * @param string $var
     * @return $this
     */
    public function setSecureAccessSshCreds($var)
    {
        GPBUtil::checkString($var, True);
        $this->secure_access_ssh_creds = $var;

        return $this;
    }

    /**
     * Override the SSH username as indicated in SSH Certificate Issuer
     *
     * Generated from protobuf field <code>string secure_access_ssh_user = 396886118 [json_name = "secure-access-ssh-user"];</code>
     * @return string
     */
    public function getSecureAccessSshUser()
    {
        return $this->secure_access_ssh_user;
    }

    /**
     * Override the SSH username as indicated in SSH Certificate Issuer
     *
     * Generated from protobuf field <code>string secure_access_ssh_user = 396886118 [json_name = "secure-access-ssh-user"];</code>
     * @param string $var
     * @return $this
     */
    public function setSecureAccessSshUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->secure_access_ssh_user = $var;

        return $this;
    }

    /**
     * Destination URL to inject secrets
     *
     * Generated from protobuf field <code>string secure_access_url = 479309214 [json_name = "secure-access-url"];</code>
     * @return string
     */
    public function getSecureAccessUrl()
    {
        return $this->secure_access_url;
    }

    /**
     * Destination URL to inject secrets
     *
     * Generated from protobuf field <code>string secure_access_url = 479309214 [json_name = "secure-access-url"];</code>
     * @param string $var
     * @return $this
     */
    public function setSecureAccessUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->secure_access_url = $var;

        return $this;
    }

    /**
     * Secure browser via Akeyless Web Access Bastion
     *
     * Generated from protobuf field <code>bool secure_access_web_browsing = 258508398 [json_name = "secure-access-web-browsing"];</code>
     * @return bool
     */
    public function getSecureAccessWebBrowsing()
    {
        return $this->secure_access_web_browsing;
    }

    /**
     * Secure browser via Akeyless Web Access Bastion
     *
     * Generated from protobuf field <code>bool secure_access_web_browsing = 258508398 [json_name = "secure-access-web-browsing"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSecureAccessWebBrowsing($var)
    {
        GPBUtil::checkBool($var);
        $this->secure_access_web_browsing = $var;

        return $this;
    }

    /**
     * Web-Proxy via Akeyless Web Access Bastion
     *
     * Generated from protobuf field <code>bool secure_access_web_proxy = 496161502 [json_name = "secure-access-web-proxy"];</code>
     * @return bool
     */
    public function getSecureAccessWebProxy()
    {
        return $this->secure_access_web_proxy;
    }

    /**
     * Web-Proxy via Akeyless Web Access Bastion
     *
     * Generated from protobuf field <code>bool secure_access_web_proxy = 496161502 [json_name = "secure-access-web-proxy"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSecureAccessWebProxy($var)
    {
        GPBUtil::checkBool($var);
        $this->secure_access_web_proxy = $var;

        return $this;
    }

    /**
     * Add tags attached to this object
     *
     * Generated from protobuf field <code>repeated string tags = 3552281 [json_name = "tags"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Add tags attached to this object
     *
     * Generated from protobuf field <code>repeated string tags = 3552281 [json_name = "tags"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

    /**
     * Authentication token (see `/auth` and `/configure`)
     *
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Authentication token (see `/auth` and `/configure`)
     *
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * The secret sub type [generic/password]
     *
     * Generated from protobuf field <code>string type = 3575610 [json_name = "type"];</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * The secret sub type [generic/password]
     *
     * Generated from protobuf field <code>string type = 3575610 [json_name = "type"];</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * The universal identity token, Required only for universal_identity authentication
     *
     * Generated from protobuf field <code>string uid_token = 468850238 [json_name = "uid-token"];</code>
     * @return string
     */
    public function getUidToken()
    {
        return $this->uid_token;
    }

    /**
     * The universal identity token, Required only for universal_identity authentication
     *
     * Generated from protobuf field <code>string uid_token = 468850238 [json_name = "uid-token"];</code>
     * @param string $var
     * @return $this
     */
    public function setUidToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->uid_token = $var;

        return $this;
    }

    /**
     * For Password Management use
     *
     * Generated from protobuf field <code>string username = 265713450 [json_name = "username"];</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * For Password Management use
     *
     * Generated from protobuf field <code>string username = 265713450 [json_name = "username"];</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * The secret value (relevant only for type 'generic')
     *
     * Generated from protobuf field <code>string value = 111972721 [json_name = "value"];</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * The secret value (relevant only for type 'generic')
     *
     * Generated from protobuf field <code>string value = 111972721 [json_name = "value"];</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

}

