<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/delete_item_output.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.DeleteItemOutput</code>
 */
class DeleteItemOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string deletion_date = 519441025 [json_name = "deletion_date"];</code>
     */
    protected $deletion_date = '';
    /**
     * Generated from protobuf field <code>int64 item_id = 505592266 [json_name = "item_id"];</code>
     */
    protected $item_id = 0;
    /**
     * Generated from protobuf field <code>string item_name = 530731980 [json_name = "item_name"];</code>
     */
    protected $item_name = '';
    /**
     * Generated from protobuf field <code>int32 version_deleted = 288318543 [json_name = "version_deleted"];</code>
     */
    protected $version_deleted = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $deletion_date
     *     @type int|string $item_id
     *     @type string $item_name
     *     @type int $version_deleted
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\DeleteItemOutput::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string deletion_date = 519441025 [json_name = "deletion_date"];</code>
     * @return string
     */
    public function getDeletionDate()
    {
        return $this->deletion_date;
    }

    /**
     * Generated from protobuf field <code>string deletion_date = 519441025 [json_name = "deletion_date"];</code>
     * @param string $var
     * @return $this
     */
    public function setDeletionDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->deletion_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 item_id = 505592266 [json_name = "item_id"];</code>
     * @return int|string
     */
    public function getItemId()
    {
        return $this->item_id;
    }

    /**
     * Generated from protobuf field <code>int64 item_id = 505592266 [json_name = "item_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setItemId($var)
    {
        GPBUtil::checkInt64($var);
        $this->item_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string item_name = 530731980 [json_name = "item_name"];</code>
     * @return string
     */
    public function getItemName()
    {
        return $this->item_name;
    }

    /**
     * Generated from protobuf field <code>string item_name = 530731980 [json_name = "item_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setItemName($var)
    {
        GPBUtil::checkString($var, True);
        $this->item_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 version_deleted = 288318543 [json_name = "version_deleted"];</code>
     * @return int
     */
    public function getVersionDeleted()
    {
        return $this->version_deleted;
    }

    /**
     * Generated from protobuf field <code>int32 version_deleted = 288318543 [json_name = "version_deleted"];</code>
     * @param int $var
     * @return $this
     */
    public function setVersionDeleted($var)
    {
        GPBUtil::checkInt32($var);
        $this->version_deleted = $var;

        return $this;
    }

}

