<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/dynamic_secret_producer_info.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.DynamicSecretProducerInfo</code>
 */
class DynamicSecretProducerInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string failure_message = 287723953 [json_name = "failure_message"];</code>
     */
    protected $failure_message = '';
    /**
     * Generated from protobuf field <code>int64 gw_cluster_id = 109299666 [json_name = "gw_cluster_id"];</code>
     */
    protected $gw_cluster_id = 0;
    /**
     * Relevant only for generic k8s producer
     *
     * Generated from protobuf field <code>string k8s_allowed_namespaces = 28957035 [json_name = "k8s_allowed_namespaces"];</code>
     */
    protected $k8s_allowed_namespaces = '';
    /**
     * Relevant only for generic k8s producer
     *
     * Generated from protobuf field <code>bool k8s_dynamic_mode = 199088220 [json_name = "k8s_dynamic_mode"];</code>
     */
    protected $k8s_dynamic_mode = false;
    /**
     * Generated from protobuf field <code>string producer_last_keep_alive = 529802705 [json_name = "producer_last_keep_alive"];</code>
     */
    protected $producer_last_keep_alive = '';
    /**
     * Generated from protobuf field <code>string producer_metadata = 455229758 [json_name = "producer_metadata"];</code>
     */
    protected $producer_metadata = '';
    /**
     * RotationStatus defines types of rotation Status
     *
     * Generated from protobuf field <code>string producer_status = 57062719 [json_name = "producer_status"];</code>
     */
    protected $producer_status = '';
    /**
     * Generated from protobuf field <code>string producer_type = 410149833 [json_name = "producer_type"];</code>
     */
    protected $producer_type = '';
    /**
     * Generated from protobuf field <code>string user_ttl = 266141832 [json_name = "user_ttl"];</code>
     */
    protected $user_ttl = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $failure_message
     *     @type int|string $gw_cluster_id
     *     @type string $k8s_allowed_namespaces
     *           Relevant only for generic k8s producer
     *     @type bool $k8s_dynamic_mode
     *           Relevant only for generic k8s producer
     *     @type string $producer_last_keep_alive
     *     @type string $producer_metadata
     *     @type string $producer_status
     *           RotationStatus defines types of rotation Status
     *     @type string $producer_type
     *     @type string $user_ttl
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\DynamicSecretProducerInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string failure_message = 287723953 [json_name = "failure_message"];</code>
     * @return string
     */
    public function getFailureMessage()
    {
        return $this->failure_message;
    }

    /**
     * Generated from protobuf field <code>string failure_message = 287723953 [json_name = "failure_message"];</code>
     * @param string $var
     * @return $this
     */
    public function setFailureMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->failure_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 gw_cluster_id = 109299666 [json_name = "gw_cluster_id"];</code>
     * @return int|string
     */
    public function getGwClusterId()
    {
        return $this->gw_cluster_id;
    }

    /**
     * Generated from protobuf field <code>int64 gw_cluster_id = 109299666 [json_name = "gw_cluster_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setGwClusterId($var)
    {
        GPBUtil::checkInt64($var);
        $this->gw_cluster_id = $var;

        return $this;
    }

    /**
     * Relevant only for generic k8s producer
     *
     * Generated from protobuf field <code>string k8s_allowed_namespaces = 28957035 [json_name = "k8s_allowed_namespaces"];</code>
     * @return string
     */
    public function getK8SAllowedNamespaces()
    {
        return $this->k8s_allowed_namespaces;
    }

    /**
     * Relevant only for generic k8s producer
     *
     * Generated from protobuf field <code>string k8s_allowed_namespaces = 28957035 [json_name = "k8s_allowed_namespaces"];</code>
     * @param string $var
     * @return $this
     */
    public function setK8SAllowedNamespaces($var)
    {
        GPBUtil::checkString($var, True);
        $this->k8s_allowed_namespaces = $var;

        return $this;
    }

    /**
     * Relevant only for generic k8s producer
     *
     * Generated from protobuf field <code>bool k8s_dynamic_mode = 199088220 [json_name = "k8s_dynamic_mode"];</code>
     * @return bool
     */
    public function getK8SDynamicMode()
    {
        return $this->k8s_dynamic_mode;
    }

    /**
     * Relevant only for generic k8s producer
     *
     * Generated from protobuf field <code>bool k8s_dynamic_mode = 199088220 [json_name = "k8s_dynamic_mode"];</code>
     * @param bool $var
     * @return $this
     */
    public function setK8SDynamicMode($var)
    {
        GPBUtil::checkBool($var);
        $this->k8s_dynamic_mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string producer_last_keep_alive = 529802705 [json_name = "producer_last_keep_alive"];</code>
     * @return string
     */
    public function getProducerLastKeepAlive()
    {
        return $this->producer_last_keep_alive;
    }

    /**
     * Generated from protobuf field <code>string producer_last_keep_alive = 529802705 [json_name = "producer_last_keep_alive"];</code>
     * @param string $var
     * @return $this
     */
    public function setProducerLastKeepAlive($var)
    {
        GPBUtil::checkString($var, True);
        $this->producer_last_keep_alive = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string producer_metadata = 455229758 [json_name = "producer_metadata"];</code>
     * @return string
     */
    public function getProducerMetadata()
    {
        return $this->producer_metadata;
    }

    /**
     * Generated from protobuf field <code>string producer_metadata = 455229758 [json_name = "producer_metadata"];</code>
     * @param string $var
     * @return $this
     */
    public function setProducerMetadata($var)
    {
        GPBUtil::checkString($var, True);
        $this->producer_metadata = $var;

        return $this;
    }

    /**
     * RotationStatus defines types of rotation Status
     *
     * Generated from protobuf field <code>string producer_status = 57062719 [json_name = "producer_status"];</code>
     * @return string
     */
    public function getProducerStatus()
    {
        return $this->producer_status;
    }

    /**
     * RotationStatus defines types of rotation Status
     *
     * Generated from protobuf field <code>string producer_status = 57062719 [json_name = "producer_status"];</code>
     * @param string $var
     * @return $this
     */
    public function setProducerStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->producer_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string producer_type = 410149833 [json_name = "producer_type"];</code>
     * @return string
     */
    public function getProducerType()
    {
        return $this->producer_type;
    }

    /**
     * Generated from protobuf field <code>string producer_type = 410149833 [json_name = "producer_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setProducerType($var)
    {
        GPBUtil::checkString($var, True);
        $this->producer_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_ttl = 266141832 [json_name = "user_ttl"];</code>
     * @return string
     */
    public function getUserTtl()
    {
        return $this->user_ttl;
    }

    /**
     * Generated from protobuf field <code>string user_ttl = 266141832 [json_name = "user_ttl"];</code>
     * @param string $var
     * @return $this
     */
    public function setUserTtl($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_ttl = $var;

        return $this;
    }

}

