<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/external_kms_key_id.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.ExternalKmsKeyId</code>
 */
class ExternalKmsKeyId extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key_id = 60931335 [json_name = "key_id"];</code>
     */
    protected $key_id = '';
    /**
     * Generated from protobuf field <code>string key_reference = 368136856 [json_name = "key_reference"];</code>
     */
    protected $key_reference = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key_id
     *     @type string $key_reference
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\ExternalKmsKeyId::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key_id = 60931335 [json_name = "key_id"];</code>
     * @return string
     */
    public function getKeyId()
    {
        return $this->key_id;
    }

    /**
     * Generated from protobuf field <code>string key_id = 60931335 [json_name = "key_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setKeyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->key_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key_reference = 368136856 [json_name = "key_reference"];</code>
     * @return string
     */
    public function getKeyReference()
    {
        return $this->key_reference;
    }

    /**
     * Generated from protobuf field <code>string key_reference = 368136856 [json_name = "key_reference"];</code>
     * @param string $var
     * @return $this
     */
    public function setKeyReference($var)
    {
        GPBUtil::checkString($var, True);
        $this->key_reference = $var;

        return $this;
    }

}

