<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/extension.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.Extension</code>
 */
class Extension extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool critical = 406182850 [json_name = "Critical"];</code>
     */
    protected $critical = false;
    /**
     * Generated from protobuf field <code>string name = 2420395 [json_name = "Name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string value = 82420049 [json_name = "Value"];</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $critical
     *     @type string $name
     *     @type string $value
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\Extension::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool critical = 406182850 [json_name = "Critical"];</code>
     * @return bool
     */
    public function getCritical()
    {
        return $this->critical;
    }

    /**
     * Generated from protobuf field <code>bool critical = 406182850 [json_name = "Critical"];</code>
     * @param bool $var
     * @return $this
     */
    public function setCritical($var)
    {
        GPBUtil::checkBool($var);
        $this->critical = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2420395 [json_name = "Name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2420395 [json_name = "Name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value = 82420049 [json_name = "Value"];</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 82420049 [json_name = "Value"];</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

}

