<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/get_rotated_secret_value.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.GetRotatedSecretValue</code>
 */
class GetRotatedSecretValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Get rotated secret value of specific Host (relevant only for Linked Target)
     *
     * Generated from protobuf field <code>string host = 3208616 [json_name = "host"];</code>
     */
    protected $host = '';
    /**
     * Retrieve the Secret value without checking the Gateway's cache [true/false]. This flag is only relevant when using the RestAPI
     *
     * Generated from protobuf field <code>string ignore_cache = 459170874 [json_name = "ignore-cache"];</code>
     */
    protected $ignore_cache = '';
    /**
     * Set output format to JSON
     *
     * Generated from protobuf field <code>bool json = 3271912 [json_name = "json"];</code>
     */
    protected $json = false;
    /**
     * Secret name
     *
     * Generated from protobuf field <code>string names = 104585032 [json_name = "names"];</code>
     */
    protected $names = '';
    /**
     * Authentication token (see `/auth` and `/configure`)
     *
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     */
    protected $token = '';
    /**
     * The universal identity token, Required only for universal_identity authentication
     *
     * Generated from protobuf field <code>string uid_token = 468850238 [json_name = "uid-token"];</code>
     */
    protected $uid_token = '';
    /**
     * Secret version
     *
     * Generated from protobuf field <code>int32 version = 351608024 [json_name = "version"];</code>
     */
    protected $version = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $host
     *           Get rotated secret value of specific Host (relevant only for Linked Target)
     *     @type string $ignore_cache
     *           Retrieve the Secret value without checking the Gateway's cache [true/false]. This flag is only relevant when using the RestAPI
     *     @type bool $json
     *           Set output format to JSON
     *     @type string $names
     *           Secret name
     *     @type string $token
     *           Authentication token (see `/auth` and `/configure`)
     *     @type string $uid_token
     *           The universal identity token, Required only for universal_identity authentication
     *     @type int $version
     *           Secret version
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\GetRotatedSecretValue::initOnce();
        parent::__construct($data);
    }

    /**
     * Get rotated secret value of specific Host (relevant only for Linked Target)
     *
     * Generated from protobuf field <code>string host = 3208616 [json_name = "host"];</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Get rotated secret value of specific Host (relevant only for Linked Target)
     *
     * Generated from protobuf field <code>string host = 3208616 [json_name = "host"];</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     * Retrieve the Secret value without checking the Gateway's cache [true/false]. This flag is only relevant when using the RestAPI
     *
     * Generated from protobuf field <code>string ignore_cache = 459170874 [json_name = "ignore-cache"];</code>
     * @return string
     */
    public function getIgnoreCache()
    {
        return $this->ignore_cache;
    }

    /**
     * Retrieve the Secret value without checking the Gateway's cache [true/false]. This flag is only relevant when using the RestAPI
     *
     * Generated from protobuf field <code>string ignore_cache = 459170874 [json_name = "ignore-cache"];</code>
     * @param string $var
     * @return $this
     */
    public function setIgnoreCache($var)
    {
        GPBUtil::checkString($var, True);
        $this->ignore_cache = $var;

        return $this;
    }

    /**
     * Set output format to JSON
     *
     * Generated from protobuf field <code>bool json = 3271912 [json_name = "json"];</code>
     * @return bool
     */
    public function getJson()
    {
        return $this->json;
    }

    /**
     * Set output format to JSON
     *
     * Generated from protobuf field <code>bool json = 3271912 [json_name = "json"];</code>
     * @param bool $var
     * @return $this
     */
    public function setJson($var)
    {
        GPBUtil::checkBool($var);
        $this->json = $var;

        return $this;
    }

    /**
     * Secret name
     *
     * Generated from protobuf field <code>string names = 104585032 [json_name = "names"];</code>
     * @return string
     */
    public function getNames()
    {
        return $this->names;
    }

    /**
     * Secret name
     *
     * Generated from protobuf field <code>string names = 104585032 [json_name = "names"];</code>
     * @param string $var
     * @return $this
     */
    public function setNames($var)
    {
        GPBUtil::checkString($var, True);
        $this->names = $var;

        return $this;
    }

    /**
     * Authentication token (see `/auth` and `/configure`)
     *
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Authentication token (see `/auth` and `/configure`)
     *
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * The universal identity token, Required only for universal_identity authentication
     *
     * Generated from protobuf field <code>string uid_token = 468850238 [json_name = "uid-token"];</code>
     * @return string
     */
    public function getUidToken()
    {
        return $this->uid_token;
    }

    /**
     * The universal identity token, Required only for universal_identity authentication
     *
     * Generated from protobuf field <code>string uid_token = 468850238 [json_name = "uid-token"];</code>
     * @param string $var
     * @return $this
     */
    public function setUidToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->uid_token = $var;

        return $this;
    }

    /**
     * Secret version
     *
     * Generated from protobuf field <code>int32 version = 351608024 [json_name = "version"];</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Secret version
     *
     * Generated from protobuf field <code>int32 version = 351608024 [json_name = "version"];</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

}

