<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/importer_info.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.ImporterInfo</code>
 */
class ImporterInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string external_item_id = 509397331 [json_name = "external_item_id"];</code>
     */
    protected $external_item_id = '';
    /**
     * Generated from protobuf field <code>int64 version = 351608024 [json_name = "version"];</code>
     */
    protected $version = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $external_item_id
     *     @type int|string $version
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\ImporterInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string external_item_id = 509397331 [json_name = "external_item_id"];</code>
     * @return string
     */
    public function getExternalItemId()
    {
        return $this->external_item_id;
    }

    /**
     * Generated from protobuf field <code>string external_item_id = 509397331 [json_name = "external_item_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setExternalItemId($var)
    {
        GPBUtil::checkString($var, True);
        $this->external_item_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 version = 351608024 [json_name = "version"];</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int64 version = 351608024 [json_name = "version"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->version = $var;

        return $this;
    }

}

