<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/item_sra_status.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.ItemSraStatus</code>
 */
class ItemSraStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.akeyless_grpc.MapInt64 count_by_host_info = 465027119 [json_name = "count_by_host_info"];</code>
     */
    protected $count_by_host_info = null;
    /**
     * Generated from protobuf field <code>map<string, .akeyless_grpc.MapInt64> count_info = 498590243 [json_name = "count_info"];</code>
     */
    private $count_info;
    /**
     * Generated from protobuf field <code>repeated string hosts_in_use = 531375521 [json_name = "hosts_in_use"];</code>
     */
    private $hosts_in_use;
    /**
     * Generated from protobuf field <code>bool is_in_use = 183462879 [json_name = "is_in_use"];</code>
     */
    protected $is_in_use = false;
    /**
     * Generated from protobuf field <code>string last_used_item = 423223277 [json_name = "last_used_item"];</code>
     */
    protected $last_used_item = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Akeyless\gRPC\MapInt64 $count_by_host_info
     *     @type array|\Google\Protobuf\Internal\MapField $count_info
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $hosts_in_use
     *     @type bool $is_in_use
     *     @type string $last_used_item
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\ItemSraStatus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.MapInt64 count_by_host_info = 465027119 [json_name = "count_by_host_info"];</code>
     * @return \Akeyless\gRPC\MapInt64|null
     */
    public function getCountByHostInfo()
    {
        return $this->count_by_host_info;
    }

    public function hasCountByHostInfo()
    {
        return isset($this->count_by_host_info);
    }

    public function clearCountByHostInfo()
    {
        unset($this->count_by_host_info);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.MapInt64 count_by_host_info = 465027119 [json_name = "count_by_host_info"];</code>
     * @param \Akeyless\gRPC\MapInt64 $var
     * @return $this
     */
    public function setCountByHostInfo($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\MapInt64::class);
        $this->count_by_host_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .akeyless_grpc.MapInt64> count_info = 498590243 [json_name = "count_info"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCountInfo()
    {
        return $this->count_info;
    }

    /**
     * Generated from protobuf field <code>map<string, .akeyless_grpc.MapInt64> count_info = 498590243 [json_name = "count_info"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCountInfo($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\MapInt64::class);
        $this->count_info = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string hosts_in_use = 531375521 [json_name = "hosts_in_use"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHostsInUse()
    {
        return $this->hosts_in_use;
    }

    /**
     * Generated from protobuf field <code>repeated string hosts_in_use = 531375521 [json_name = "hosts_in_use"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHostsInUse($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->hosts_in_use = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_in_use = 183462879 [json_name = "is_in_use"];</code>
     * @return bool
     */
    public function getIsInUse()
    {
        return $this->is_in_use;
    }

    /**
     * Generated from protobuf field <code>bool is_in_use = 183462879 [json_name = "is_in_use"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsInUse($var)
    {
        GPBUtil::checkBool($var);
        $this->is_in_use = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_used_item = 423223277 [json_name = "last_used_item"];</code>
     * @return string
     */
    public function getLastUsedItem()
    {
        return $this->last_used_item;
    }

    /**
     * Generated from protobuf field <code>string last_used_item = 423223277 [json_name = "last_used_item"];</code>
     * @param string $var
     * @return $this
     */
    public function setLastUsedItem($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_used_item = $var;

        return $this;
    }

}

