<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/item.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.Item</code>
 */
class Item extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string access_date = 495996504 [json_name = "access_date"];</code>
     */
    protected $access_date = '';
    /**
     * Generated from protobuf field <code>string access_date_display = 93370412 [json_name = "access_date_display"];</code>
     */
    protected $access_date_display = '';
    /**
     * Generated from protobuf field <code>string access_request_status = 207523875 [json_name = "access_request_status"];</code>
     */
    protected $access_request_status = '';
    /**
     * Generated from protobuf field <code>bool auto_rotate = 198702615 [json_name = "auto_rotate"];</code>
     */
    protected $auto_rotate = false;
    /**
     * Generated from protobuf field <code>.akeyless_grpc.BastionsList bastion_details = 416847404 [json_name = "bastion_details"];</code>
     */
    protected $bastion_details = null;
    /**
     * Generated from protobuf field <code>string cert_issuer_signer_key_name = 485575896 [json_name = "cert_issuer_signer_key_name"];</code>
     */
    protected $cert_issuer_signer_key_name = '';
    /**
     * Generated from protobuf field <code>.akeyless_grpc.CertificateIssueInfo certificate_issue_details = 485271502 [json_name = "certificate_issue_details"];</code>
     */
    protected $certificate_issue_details = null;
    /**
     * Generated from protobuf field <code>string certificates = 394850748 [json_name = "certificates"];</code>
     */
    protected $certificates = '';
    /**
     * Generated from protobuf field <code>repeated string client_permissions = 61074962 [json_name = "client_permissions"];</code>
     */
    private $client_permissions;
    /**
     * Generated from protobuf field <code>string creation_date = 321236241 [json_name = "creation_date"];</code>
     */
    protected $creation_date = '';
    /**
     * Generated from protobuf field <code>string customer_fragment_id = 110711159 [json_name = "customer_fragment_id"];</code>
     */
    protected $customer_fragment_id = '';
    /**
     * Generated from protobuf field <code>bool delete_protection = 517947888 [json_name = "delete_protection"];</code>
     */
    protected $delete_protection = false;
    /**
     * Generated from protobuf field <code>string deletion_date = 519441025 [json_name = "deletion_date"];</code>
     */
    protected $deletion_date = '';
    /**
     * Generated from protobuf field <code>string display_id = 377648713 [json_name = "display_id"];</code>
     */
    protected $display_id = '';
    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.GatewayBasicInfo gateway_details = 55944380 [json_name = "gateway_details"];</code>
     */
    private $gateway_details;
    /**
     * Generated from protobuf field <code>bool is_access_request_enabled = 426079384 [json_name = "is_access_request_enabled"];</code>
     */
    protected $is_access_request_enabled = false;
    /**
     * Generated from protobuf field <code>bool is_enabled = 109284052 [json_name = "is_enabled"];</code>
     */
    protected $is_enabled = false;
    /**
     * Generated from protobuf field <code>int64 item_accessibility = 308326691 [json_name = "item_accessibility"];</code>
     */
    protected $item_accessibility = 0;
    /**
     * Generated from protobuf field <code>.akeyless_grpc.ItemGeneralInfo item_general_info = 438293680 [json_name = "item_general_info"];</code>
     */
    protected $item_general_info = null;
    /**
     * Generated from protobuf field <code>int64 item_id = 505592266 [json_name = "item_id"];</code>
     */
    protected $item_id = 0;
    /**
     * Generated from protobuf field <code>string item_metadata = 61933861 [json_name = "item_metadata"];</code>
     */
    protected $item_metadata = '';
    /**
     * Generated from protobuf field <code>string item_name = 530731980 [json_name = "item_name"];</code>
     */
    protected $item_name = '';
    /**
     * Generated from protobuf field <code>int64 item_size = 530574934 [json_name = "item_size"];</code>
     */
    protected $item_size = 0;
    /**
     * ItemState defines the different states an Item can be in
     *
     * Generated from protobuf field <code>string item_state = 341391262 [json_name = "item_state"];</code>
     */
    protected $item_state = '';
    /**
     * Generated from protobuf field <code>string item_sub_type = 80876158 [json_name = "item_sub_type"];</code>
     */
    protected $item_sub_type = '';
    /**
     * Generated from protobuf field <code>repeated string item_tags = 530553406 [json_name = "item_tags"];</code>
     */
    private $item_tags;
    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.ItemTargetAssociation item_targets_assoc = 263866773 [json_name = "item_targets_assoc"];</code>
     */
    private $item_targets_assoc;
    /**
     * Generated from protobuf field <code>string item_type = 530530077 [json_name = "item_type"];</code>
     */
    protected $item_type = '';
    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.ItemVersion item_versions = 523240891 [json_name = "item_versions"];</code>
     */
    private $item_versions;
    /**
     * Generated from protobuf field <code>string last_rotation_date = 172867049 [json_name = "last_rotation_date"];</code>
     */
    protected $last_rotation_date = '';
    /**
     * Generated from protobuf field <code>int32 last_version = 387866672 [json_name = "last_version"];</code>
     */
    protected $last_version = 0;
    /**
     * Generated from protobuf field <code>.akeyless_grpc.LinkedDetails linked_details = 61336037 [json_name = "linked_details"];</code>
     */
    protected $linked_details = null;
    /**
     * Generated from protobuf field <code>string modification_date = 202999697 [json_name = "modification_date"];</code>
     */
    protected $modification_date = '';
    /**
     * Generated from protobuf field <code>string next_rotation_date = 34451584 [json_name = "next_rotation_date"];</code>
     */
    protected $next_rotation_date = '';
    /**
     * Generated from protobuf field <code>string protection_key_name = 80474900 [json_name = "protection_key_name"];</code>
     */
    protected $protection_key_name = '';
    /**
     * Generated from protobuf field <code>string protection_key_type = 80676803 [json_name = "protection_key_type"];</code>
     */
    protected $protection_key_type = '';
    /**
     * Generated from protobuf field <code>string public_value = 342324252 [json_name = "public_value"];</code>
     */
    protected $public_value = '';
    /**
     * Generated from protobuf field <code>int64 rotation_interval = 273509274 [json_name = "rotation_interval"];</code>
     */
    protected $rotation_interval = 0;
    /**
     * Generated from protobuf field <code>.akeyless_grpc.RuleAssigner shared_by = 507826577 [json_name = "shared_by"];</code>
     */
    protected $shared_by = null;
    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.TargetItemVersion target_versions = 102927994 [json_name = "target_versions"];</code>
     */
    private $target_versions;
    /**
     * Generated from protobuf field <code>bool with_customer_fragment = 40616536 [json_name = "with_customer_fragment"];</code>
     */
    protected $with_customer_fragment = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $access_date
     *     @type string $access_date_display
     *     @type string $access_request_status
     *     @type bool $auto_rotate
     *     @type \Akeyless\gRPC\BastionsList $bastion_details
     *     @type string $cert_issuer_signer_key_name
     *     @type \Akeyless\gRPC\CertificateIssueInfo $certificate_issue_details
     *     @type string $certificates
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $client_permissions
     *     @type string $creation_date
     *     @type string $customer_fragment_id
     *     @type bool $delete_protection
     *     @type string $deletion_date
     *     @type string $display_id
     *     @type array<\Akeyless\gRPC\GatewayBasicInfo>|\Google\Protobuf\Internal\RepeatedField $gateway_details
     *     @type bool $is_access_request_enabled
     *     @type bool $is_enabled
     *     @type int|string $item_accessibility
     *     @type \Akeyless\gRPC\ItemGeneralInfo $item_general_info
     *     @type int|string $item_id
     *     @type string $item_metadata
     *     @type string $item_name
     *     @type int|string $item_size
     *     @type string $item_state
     *           ItemState defines the different states an Item can be in
     *     @type string $item_sub_type
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $item_tags
     *     @type array<\Akeyless\gRPC\ItemTargetAssociation>|\Google\Protobuf\Internal\RepeatedField $item_targets_assoc
     *     @type string $item_type
     *     @type array<\Akeyless\gRPC\ItemVersion>|\Google\Protobuf\Internal\RepeatedField $item_versions
     *     @type string $last_rotation_date
     *     @type int $last_version
     *     @type \Akeyless\gRPC\LinkedDetails $linked_details
     *     @type string $modification_date
     *     @type string $next_rotation_date
     *     @type string $protection_key_name
     *     @type string $protection_key_type
     *     @type string $public_value
     *     @type int|string $rotation_interval
     *     @type \Akeyless\gRPC\RuleAssigner $shared_by
     *     @type array<\Akeyless\gRPC\TargetItemVersion>|\Google\Protobuf\Internal\RepeatedField $target_versions
     *     @type bool $with_customer_fragment
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\Item::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string access_date = 495996504 [json_name = "access_date"];</code>
     * @return string
     */
    public function getAccessDate()
    {
        return $this->access_date;
    }

    /**
     * Generated from protobuf field <code>string access_date = 495996504 [json_name = "access_date"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccessDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string access_date_display = 93370412 [json_name = "access_date_display"];</code>
     * @return string
     */
    public function getAccessDateDisplay()
    {
        return $this->access_date_display;
    }

    /**
     * Generated from protobuf field <code>string access_date_display = 93370412 [json_name = "access_date_display"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccessDateDisplay($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_date_display = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string access_request_status = 207523875 [json_name = "access_request_status"];</code>
     * @return string
     */
    public function getAccessRequestStatus()
    {
        return $this->access_request_status;
    }

    /**
     * Generated from protobuf field <code>string access_request_status = 207523875 [json_name = "access_request_status"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccessRequestStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_request_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool auto_rotate = 198702615 [json_name = "auto_rotate"];</code>
     * @return bool
     */
    public function getAutoRotate()
    {
        return $this->auto_rotate;
    }

    /**
     * Generated from protobuf field <code>bool auto_rotate = 198702615 [json_name = "auto_rotate"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAutoRotate($var)
    {
        GPBUtil::checkBool($var);
        $this->auto_rotate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.BastionsList bastion_details = 416847404 [json_name = "bastion_details"];</code>
     * @return \Akeyless\gRPC\BastionsList|null
     */
    public function getBastionDetails()
    {
        return $this->bastion_details;
    }

    public function hasBastionDetails()
    {
        return isset($this->bastion_details);
    }

    public function clearBastionDetails()
    {
        unset($this->bastion_details);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.BastionsList bastion_details = 416847404 [json_name = "bastion_details"];</code>
     * @param \Akeyless\gRPC\BastionsList $var
     * @return $this
     */
    public function setBastionDetails($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\BastionsList::class);
        $this->bastion_details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cert_issuer_signer_key_name = 485575896 [json_name = "cert_issuer_signer_key_name"];</code>
     * @return string
     */
    public function getCertIssuerSignerKeyName()
    {
        return $this->cert_issuer_signer_key_name;
    }

    /**
     * Generated from protobuf field <code>string cert_issuer_signer_key_name = 485575896 [json_name = "cert_issuer_signer_key_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setCertIssuerSignerKeyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->cert_issuer_signer_key_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.CertificateIssueInfo certificate_issue_details = 485271502 [json_name = "certificate_issue_details"];</code>
     * @return \Akeyless\gRPC\CertificateIssueInfo|null
     */
    public function getCertificateIssueDetails()
    {
        return $this->certificate_issue_details;
    }

    public function hasCertificateIssueDetails()
    {
        return isset($this->certificate_issue_details);
    }

    public function clearCertificateIssueDetails()
    {
        unset($this->certificate_issue_details);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.CertificateIssueInfo certificate_issue_details = 485271502 [json_name = "certificate_issue_details"];</code>
     * @param \Akeyless\gRPC\CertificateIssueInfo $var
     * @return $this
     */
    public function setCertificateIssueDetails($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\CertificateIssueInfo::class);
        $this->certificate_issue_details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string certificates = 394850748 [json_name = "certificates"];</code>
     * @return string
     */
    public function getCertificates()
    {
        return $this->certificates;
    }

    /**
     * Generated from protobuf field <code>string certificates = 394850748 [json_name = "certificates"];</code>
     * @param string $var
     * @return $this
     */
    public function setCertificates($var)
    {
        GPBUtil::checkString($var, True);
        $this->certificates = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string client_permissions = 61074962 [json_name = "client_permissions"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClientPermissions()
    {
        return $this->client_permissions;
    }

    /**
     * Generated from protobuf field <code>repeated string client_permissions = 61074962 [json_name = "client_permissions"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClientPermissions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->client_permissions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string creation_date = 321236241 [json_name = "creation_date"];</code>
     * @return string
     */
    public function getCreationDate()
    {
        return $this->creation_date;
    }

    /**
     * Generated from protobuf field <code>string creation_date = 321236241 [json_name = "creation_date"];</code>
     * @param string $var
     * @return $this
     */
    public function setCreationDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->creation_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customer_fragment_id = 110711159 [json_name = "customer_fragment_id"];</code>
     * @return string
     */
    public function getCustomerFragmentId()
    {
        return $this->customer_fragment_id;
    }

    /**
     * Generated from protobuf field <code>string customer_fragment_id = 110711159 [json_name = "customer_fragment_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerFragmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_fragment_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool delete_protection = 517947888 [json_name = "delete_protection"];</code>
     * @return bool
     */
    public function getDeleteProtection()
    {
        return $this->delete_protection;
    }

    /**
     * Generated from protobuf field <code>bool delete_protection = 517947888 [json_name = "delete_protection"];</code>
     * @param bool $var
     * @return $this
     */
    public function setDeleteProtection($var)
    {
        GPBUtil::checkBool($var);
        $this->delete_protection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string deletion_date = 519441025 [json_name = "deletion_date"];</code>
     * @return string
     */
    public function getDeletionDate()
    {
        return $this->deletion_date;
    }

    /**
     * Generated from protobuf field <code>string deletion_date = 519441025 [json_name = "deletion_date"];</code>
     * @param string $var
     * @return $this
     */
    public function setDeletionDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->deletion_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string display_id = 377648713 [json_name = "display_id"];</code>
     * @return string
     */
    public function getDisplayId()
    {
        return $this->display_id;
    }

    /**
     * Generated from protobuf field <code>string display_id = 377648713 [json_name = "display_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayId($var)
    {
        GPBUtil::checkString($var, True);
        $this->display_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.GatewayBasicInfo gateway_details = 55944380 [json_name = "gateway_details"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGatewayDetails()
    {
        return $this->gateway_details;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.GatewayBasicInfo gateway_details = 55944380 [json_name = "gateway_details"];</code>
     * @param array<\Akeyless\gRPC\GatewayBasicInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGatewayDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\GatewayBasicInfo::class);
        $this->gateway_details = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_access_request_enabled = 426079384 [json_name = "is_access_request_enabled"];</code>
     * @return bool
     */
    public function getIsAccessRequestEnabled()
    {
        return $this->is_access_request_enabled;
    }

    /**
     * Generated from protobuf field <code>bool is_access_request_enabled = 426079384 [json_name = "is_access_request_enabled"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAccessRequestEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->is_access_request_enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_enabled = 109284052 [json_name = "is_enabled"];</code>
     * @return bool
     */
    public function getIsEnabled()
    {
        return $this->is_enabled;
    }

    /**
     * Generated from protobuf field <code>bool is_enabled = 109284052 [json_name = "is_enabled"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->is_enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 item_accessibility = 308326691 [json_name = "item_accessibility"];</code>
     * @return int|string
     */
    public function getItemAccessibility()
    {
        return $this->item_accessibility;
    }

    /**
     * Generated from protobuf field <code>int64 item_accessibility = 308326691 [json_name = "item_accessibility"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setItemAccessibility($var)
    {
        GPBUtil::checkInt64($var);
        $this->item_accessibility = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.ItemGeneralInfo item_general_info = 438293680 [json_name = "item_general_info"];</code>
     * @return \Akeyless\gRPC\ItemGeneralInfo|null
     */
    public function getItemGeneralInfo()
    {
        return $this->item_general_info;
    }

    public function hasItemGeneralInfo()
    {
        return isset($this->item_general_info);
    }

    public function clearItemGeneralInfo()
    {
        unset($this->item_general_info);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.ItemGeneralInfo item_general_info = 438293680 [json_name = "item_general_info"];</code>
     * @param \Akeyless\gRPC\ItemGeneralInfo $var
     * @return $this
     */
    public function setItemGeneralInfo($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\ItemGeneralInfo::class);
        $this->item_general_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 item_id = 505592266 [json_name = "item_id"];</code>
     * @return int|string
     */
    public function getItemId()
    {
        return $this->item_id;
    }

    /**
     * Generated from protobuf field <code>int64 item_id = 505592266 [json_name = "item_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setItemId($var)
    {
        GPBUtil::checkInt64($var);
        $this->item_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string item_metadata = 61933861 [json_name = "item_metadata"];</code>
     * @return string
     */
    public function getItemMetadata()
    {
        return $this->item_metadata;
    }

    /**
     * Generated from protobuf field <code>string item_metadata = 61933861 [json_name = "item_metadata"];</code>
     * @param string $var
     * @return $this
     */
    public function setItemMetadata($var)
    {
        GPBUtil::checkString($var, True);
        $this->item_metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string item_name = 530731980 [json_name = "item_name"];</code>
     * @return string
     */
    public function getItemName()
    {
        return $this->item_name;
    }

    /**
     * Generated from protobuf field <code>string item_name = 530731980 [json_name = "item_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setItemName($var)
    {
        GPBUtil::checkString($var, True);
        $this->item_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 item_size = 530574934 [json_name = "item_size"];</code>
     * @return int|string
     */
    public function getItemSize()
    {
        return $this->item_size;
    }

    /**
     * Generated from protobuf field <code>int64 item_size = 530574934 [json_name = "item_size"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setItemSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->item_size = $var;

        return $this;
    }

    /**
     * ItemState defines the different states an Item can be in
     *
     * Generated from protobuf field <code>string item_state = 341391262 [json_name = "item_state"];</code>
     * @return string
     */
    public function getItemState()
    {
        return $this->item_state;
    }

    /**
     * ItemState defines the different states an Item can be in
     *
     * Generated from protobuf field <code>string item_state = 341391262 [json_name = "item_state"];</code>
     * @param string $var
     * @return $this
     */
    public function setItemState($var)
    {
        GPBUtil::checkString($var, True);
        $this->item_state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string item_sub_type = 80876158 [json_name = "item_sub_type"];</code>
     * @return string
     */
    public function getItemSubType()
    {
        return $this->item_sub_type;
    }

    /**
     * Generated from protobuf field <code>string item_sub_type = 80876158 [json_name = "item_sub_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setItemSubType($var)
    {
        GPBUtil::checkString($var, True);
        $this->item_sub_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string item_tags = 530553406 [json_name = "item_tags"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItemTags()
    {
        return $this->item_tags;
    }

    /**
     * Generated from protobuf field <code>repeated string item_tags = 530553406 [json_name = "item_tags"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItemTags($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->item_tags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.ItemTargetAssociation item_targets_assoc = 263866773 [json_name = "item_targets_assoc"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItemTargetsAssoc()
    {
        return $this->item_targets_assoc;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.ItemTargetAssociation item_targets_assoc = 263866773 [json_name = "item_targets_assoc"];</code>
     * @param array<\Akeyless\gRPC\ItemTargetAssociation>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItemTargetsAssoc($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\ItemTargetAssociation::class);
        $this->item_targets_assoc = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string item_type = 530530077 [json_name = "item_type"];</code>
     * @return string
     */
    public function getItemType()
    {
        return $this->item_type;
    }

    /**
     * Generated from protobuf field <code>string item_type = 530530077 [json_name = "item_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setItemType($var)
    {
        GPBUtil::checkString($var, True);
        $this->item_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.ItemVersion item_versions = 523240891 [json_name = "item_versions"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItemVersions()
    {
        return $this->item_versions;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.ItemVersion item_versions = 523240891 [json_name = "item_versions"];</code>
     * @param array<\Akeyless\gRPC\ItemVersion>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItemVersions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\ItemVersion::class);
        $this->item_versions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_rotation_date = 172867049 [json_name = "last_rotation_date"];</code>
     * @return string
     */
    public function getLastRotationDate()
    {
        return $this->last_rotation_date;
    }

    /**
     * Generated from protobuf field <code>string last_rotation_date = 172867049 [json_name = "last_rotation_date"];</code>
     * @param string $var
     * @return $this
     */
    public function setLastRotationDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_rotation_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 last_version = 387866672 [json_name = "last_version"];</code>
     * @return int
     */
    public function getLastVersion()
    {
        return $this->last_version;
    }

    /**
     * Generated from protobuf field <code>int32 last_version = 387866672 [json_name = "last_version"];</code>
     * @param int $var
     * @return $this
     */
    public function setLastVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->last_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.LinkedDetails linked_details = 61336037 [json_name = "linked_details"];</code>
     * @return \Akeyless\gRPC\LinkedDetails|null
     */
    public function getLinkedDetails()
    {
        return $this->linked_details;
    }

    public function hasLinkedDetails()
    {
        return isset($this->linked_details);
    }

    public function clearLinkedDetails()
    {
        unset($this->linked_details);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.LinkedDetails linked_details = 61336037 [json_name = "linked_details"];</code>
     * @param \Akeyless\gRPC\LinkedDetails $var
     * @return $this
     */
    public function setLinkedDetails($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\LinkedDetails::class);
        $this->linked_details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string modification_date = 202999697 [json_name = "modification_date"];</code>
     * @return string
     */
    public function getModificationDate()
    {
        return $this->modification_date;
    }

    /**
     * Generated from protobuf field <code>string modification_date = 202999697 [json_name = "modification_date"];</code>
     * @param string $var
     * @return $this
     */
    public function setModificationDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->modification_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string next_rotation_date = 34451584 [json_name = "next_rotation_date"];</code>
     * @return string
     */
    public function getNextRotationDate()
    {
        return $this->next_rotation_date;
    }

    /**
     * Generated from protobuf field <code>string next_rotation_date = 34451584 [json_name = "next_rotation_date"];</code>
     * @param string $var
     * @return $this
     */
    public function setNextRotationDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_rotation_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string protection_key_name = 80474900 [json_name = "protection_key_name"];</code>
     * @return string
     */
    public function getProtectionKeyName()
    {
        return $this->protection_key_name;
    }

    /**
     * Generated from protobuf field <code>string protection_key_name = 80474900 [json_name = "protection_key_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setProtectionKeyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->protection_key_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string protection_key_type = 80676803 [json_name = "protection_key_type"];</code>
     * @return string
     */
    public function getProtectionKeyType()
    {
        return $this->protection_key_type;
    }

    /**
     * Generated from protobuf field <code>string protection_key_type = 80676803 [json_name = "protection_key_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setProtectionKeyType($var)
    {
        GPBUtil::checkString($var, True);
        $this->protection_key_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string public_value = 342324252 [json_name = "public_value"];</code>
     * @return string
     */
    public function getPublicValue()
    {
        return $this->public_value;
    }

    /**
     * Generated from protobuf field <code>string public_value = 342324252 [json_name = "public_value"];</code>
     * @param string $var
     * @return $this
     */
    public function setPublicValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->public_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 rotation_interval = 273509274 [json_name = "rotation_interval"];</code>
     * @return int|string
     */
    public function getRotationInterval()
    {
        return $this->rotation_interval;
    }

    /**
     * Generated from protobuf field <code>int64 rotation_interval = 273509274 [json_name = "rotation_interval"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setRotationInterval($var)
    {
        GPBUtil::checkInt64($var);
        $this->rotation_interval = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.RuleAssigner shared_by = 507826577 [json_name = "shared_by"];</code>
     * @return \Akeyless\gRPC\RuleAssigner|null
     */
    public function getSharedBy()
    {
        return $this->shared_by;
    }

    public function hasSharedBy()
    {
        return isset($this->shared_by);
    }

    public function clearSharedBy()
    {
        unset($this->shared_by);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.RuleAssigner shared_by = 507826577 [json_name = "shared_by"];</code>
     * @param \Akeyless\gRPC\RuleAssigner $var
     * @return $this
     */
    public function setSharedBy($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\RuleAssigner::class);
        $this->shared_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.TargetItemVersion target_versions = 102927994 [json_name = "target_versions"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTargetVersions()
    {
        return $this->target_versions;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.TargetItemVersion target_versions = 102927994 [json_name = "target_versions"];</code>
     * @param array<\Akeyless\gRPC\TargetItemVersion>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTargetVersions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\TargetItemVersion::class);
        $this->target_versions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool with_customer_fragment = 40616536 [json_name = "with_customer_fragment"];</code>
     * @return bool
     */
    public function getWithCustomerFragment()
    {
        return $this->with_customer_fragment;
    }

    /**
     * Generated from protobuf field <code>bool with_customer_fragment = 40616536 [json_name = "with_customer_fragment"];</code>
     * @param bool $var
     * @return $this
     */
    public function setWithCustomerFragment($var)
    {
        GPBUtil::checkBool($var);
        $this->with_customer_fragment = $var;

        return $this;
    }

}

