<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/item_target_association.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.ItemTargetAssociation</code>
 */
class ItemTargetAssociation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string assoc_id = 364473979 [json_name = "assoc_id"];</code>
     */
    protected $assoc_id = '';
    /**
     * Generated from protobuf field <code>map<string, string> attributes = 405645655 [json_name = "attributes"];</code>
     */
    private $attributes;
    /**
     * Generated from protobuf field <code>int64 target_id = 278705528 [json_name = "target_id"];</code>
     */
    protected $target_id = 0;
    /**
     * Generated from protobuf field <code>string target_name = 474147722 [json_name = "target_name"];</code>
     */
    protected $target_name = '';
    /**
     * Generated from protobuf field <code>string target_type = 473945819 [json_name = "target_type"];</code>
     */
    protected $target_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $assoc_id
     *     @type array|\Google\Protobuf\Internal\MapField $attributes
     *     @type int|string $target_id
     *     @type string $target_name
     *     @type string $target_type
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\ItemTargetAssociation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string assoc_id = 364473979 [json_name = "assoc_id"];</code>
     * @return string
     */
    public function getAssocId()
    {
        return $this->assoc_id;
    }

    /**
     * Generated from protobuf field <code>string assoc_id = 364473979 [json_name = "assoc_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setAssocId($var)
    {
        GPBUtil::checkString($var, True);
        $this->assoc_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> attributes = 405645655 [json_name = "attributes"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * Generated from protobuf field <code>map<string, string> attributes = 405645655 [json_name = "attributes"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAttributes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 target_id = 278705528 [json_name = "target_id"];</code>
     * @return int|string
     */
    public function getTargetId()
    {
        return $this->target_id;
    }

    /**
     * Generated from protobuf field <code>int64 target_id = 278705528 [json_name = "target_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setTargetId($var)
    {
        GPBUtil::checkInt64($var);
        $this->target_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_name = 474147722 [json_name = "target_name"];</code>
     * @return string
     */
    public function getTargetName()
    {
        return $this->target_name;
    }

    /**
     * Generated from protobuf field <code>string target_name = 474147722 [json_name = "target_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setTargetName($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_type = 473945819 [json_name = "target_type"];</code>
     * @return string
     */
    public function getTargetType()
    {
        return $this->target_type;
    }

    /**
     * Generated from protobuf field <code>string target_type = 473945819 [json_name = "target_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setTargetType($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_type = $var;

        return $this;
    }

}

