<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/json_error.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.JSONError</code>
 */
class JSONError extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string error = 96784904 [json_name = "error"];</code>
     */
    protected $error = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $error
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\JsonError::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string error = 96784904 [json_name = "error"];</code>
     * @return string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>string error = 96784904 [json_name = "error"];</code>
     * @param string $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;

        return $this;
    }

}

