<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/linked_details.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.LinkedDetails</code>
 */
class LinkedDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, string> hosts = 99467211 [json_name = "hosts"];</code>
     */
    private $hosts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $hosts
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\LinkedDetails::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, string> hosts = 99467211 [json_name = "hosts"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getHosts()
    {
        return $this->hosts;
    }

    /**
     * Generated from protobuf field <code>map<string, string> hosts = 99467211 [json_name = "hosts"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setHosts($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->hosts = $arr;

        return $this;
    }

}

