<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/list_items.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.ListItems</code>
 */
class ListItems extends \Google\Protobuf\Internal\Message
{
    /**
     * for personal password manager
     *
     * Generated from protobuf field <code>string accessibility = 213139122 [json_name = "accessibility"];</code>
     */
    protected $accessibility = '';
    /**
     * Filter by item name/username/website or part of it
     *
     * Generated from protobuf field <code>string advanced_filter = 409156735 [json_name = "advanced-filter"];</code>
     */
    protected $advanced_filter = '';
    /**
     * Retrieve all items using pagination, when disabled retrieving only first 1000 items
     *
     * Generated from protobuf field <code>string auto_pagination = 158511737 [json_name = "auto-pagination"];</code>
     */
    protected $auto_pagination = '';
    /**
     * Filter by item name or part of it
     *
     * Generated from protobuf field <code>string filter = 200750218 [json_name = "filter"];</code>
     */
    protected $filter = '';
    /**
     * Set output format to JSON
     *
     * Generated from protobuf field <code>bool json = 3271912 [json_name = "json"];</code>
     */
    protected $json = false;
    /**
     * Show only basic information of the items
     *
     * Generated from protobuf field <code>bool minimal_view = 19540818 [json_name = "minimal-view"];</code>
     */
    protected $minimal_view = false;
    /**
     * List only secrets modified after specified date (in unix time)
     *
     * Generated from protobuf field <code>int64 modified_after = 421781033 [json_name = "modified-after"];</code>
     */
    protected $modified_after = 0;
    /**
     * Next page reference
     *
     * Generated from protobuf field <code>string pagination_token = 483104251 [json_name = "pagination-token"];</code>
     */
    protected $pagination_token = '';
    /**
     * Path to folder
     *
     * Generated from protobuf field <code>string path = 3433509 [json_name = "path"];</code>
     */
    protected $path = '';
    /**
     * Filter by items with SRA functionality enabled
     *
     * Generated from protobuf field <code>bool sra_only = 522067785 [json_name = "sra-only"];</code>
     */
    protected $sra_only = false;
    /**
     * Generated from protobuf field <code>repeated string sub_types = 41825862 [json_name = "sub_types"];</code>
     */
    private $sub_types;
    /**
     * Filter by item tag
     *
     * Generated from protobuf field <code>string tag = 114586 [json_name = "tag"];</code>
     */
    protected $tag = '';
    /**
     * Authentication token (see `/auth` and `/configure`)
     *
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     */
    protected $token = '';
    /**
     * The item types list of the requested items. In case it is empty, all types of items will be returned. options: [key, static-secret, dynamic-secret, classic-key]
     *
     * Generated from protobuf field <code>repeated string type = 3575610 [json_name = "type"];</code>
     */
    private $type;
    /**
     * The universal identity token, Required only for universal_identity authentication
     *
     * Generated from protobuf field <code>string uid_token = 468850238 [json_name = "uid-token"];</code>
     */
    protected $uid_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $accessibility
     *           for personal password manager
     *     @type string $advanced_filter
     *           Filter by item name/username/website or part of it
     *     @type string $auto_pagination
     *           Retrieve all items using pagination, when disabled retrieving only first 1000 items
     *     @type string $filter
     *           Filter by item name or part of it
     *     @type bool $json
     *           Set output format to JSON
     *     @type bool $minimal_view
     *           Show only basic information of the items
     *     @type int|string $modified_after
     *           List only secrets modified after specified date (in unix time)
     *     @type string $pagination_token
     *           Next page reference
     *     @type string $path
     *           Path to folder
     *     @type bool $sra_only
     *           Filter by items with SRA functionality enabled
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $sub_types
     *     @type string $tag
     *           Filter by item tag
     *     @type string $token
     *           Authentication token (see `/auth` and `/configure`)
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $type
     *           The item types list of the requested items. In case it is empty, all types of items will be returned. options: [key, static-secret, dynamic-secret, classic-key]
     *     @type string $uid_token
     *           The universal identity token, Required only for universal_identity authentication
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\ListItems::initOnce();
        parent::__construct($data);
    }

    /**
     * for personal password manager
     *
     * Generated from protobuf field <code>string accessibility = 213139122 [json_name = "accessibility"];</code>
     * @return string
     */
    public function getAccessibility()
    {
        return $this->accessibility;
    }

    /**
     * for personal password manager
     *
     * Generated from protobuf field <code>string accessibility = 213139122 [json_name = "accessibility"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccessibility($var)
    {
        GPBUtil::checkString($var, True);
        $this->accessibility = $var;

        return $this;
    }

    /**
     * Filter by item name/username/website or part of it
     *
     * Generated from protobuf field <code>string advanced_filter = 409156735 [json_name = "advanced-filter"];</code>
     * @return string
     */
    public function getAdvancedFilter()
    {
        return $this->advanced_filter;
    }

    /**
     * Filter by item name/username/website or part of it
     *
     * Generated from protobuf field <code>string advanced_filter = 409156735 [json_name = "advanced-filter"];</code>
     * @param string $var
     * @return $this
     */
    public function setAdvancedFilter($var)
    {
        GPBUtil::checkString($var, True);
        $this->advanced_filter = $var;

        return $this;
    }

    /**
     * Retrieve all items using pagination, when disabled retrieving only first 1000 items
     *
     * Generated from protobuf field <code>string auto_pagination = 158511737 [json_name = "auto-pagination"];</code>
     * @return string
     */
    public function getAutoPagination()
    {
        return $this->auto_pagination;
    }

    /**
     * Retrieve all items using pagination, when disabled retrieving only first 1000 items
     *
     * Generated from protobuf field <code>string auto_pagination = 158511737 [json_name = "auto-pagination"];</code>
     * @param string $var
     * @return $this
     */
    public function setAutoPagination($var)
    {
        GPBUtil::checkString($var, True);
        $this->auto_pagination = $var;

        return $this;
    }

    /**
     * Filter by item name or part of it
     *
     * Generated from protobuf field <code>string filter = 200750218 [json_name = "filter"];</code>
     * @return string
     */
    public function getFilter()
    {
        return $this->filter;
    }

    /**
     * Filter by item name or part of it
     *
     * Generated from protobuf field <code>string filter = 200750218 [json_name = "filter"];</code>
     * @param string $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkString($var, True);
        $this->filter = $var;

        return $this;
    }

    /**
     * Set output format to JSON
     *
     * Generated from protobuf field <code>bool json = 3271912 [json_name = "json"];</code>
     * @return bool
     */
    public function getJson()
    {
        return $this->json;
    }

    /**
     * Set output format to JSON
     *
     * Generated from protobuf field <code>bool json = 3271912 [json_name = "json"];</code>
     * @param bool $var
     * @return $this
     */
    public function setJson($var)
    {
        GPBUtil::checkBool($var);
        $this->json = $var;

        return $this;
    }

    /**
     * Show only basic information of the items
     *
     * Generated from protobuf field <code>bool minimal_view = 19540818 [json_name = "minimal-view"];</code>
     * @return bool
     */
    public function getMinimalView()
    {
        return $this->minimal_view;
    }

    /**
     * Show only basic information of the items
     *
     * Generated from protobuf field <code>bool minimal_view = 19540818 [json_name = "minimal-view"];</code>
     * @param bool $var
     * @return $this
     */
    public function setMinimalView($var)
    {
        GPBUtil::checkBool($var);
        $this->minimal_view = $var;

        return $this;
    }

    /**
     * List only secrets modified after specified date (in unix time)
     *
     * Generated from protobuf field <code>int64 modified_after = 421781033 [json_name = "modified-after"];</code>
     * @return int|string
     */
    public function getModifiedAfter()
    {
        return $this->modified_after;
    }

    /**
     * List only secrets modified after specified date (in unix time)
     *
     * Generated from protobuf field <code>int64 modified_after = 421781033 [json_name = "modified-after"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setModifiedAfter($var)
    {
        GPBUtil::checkInt64($var);
        $this->modified_after = $var;

        return $this;
    }

    /**
     * Next page reference
     *
     * Generated from protobuf field <code>string pagination_token = 483104251 [json_name = "pagination-token"];</code>
     * @return string
     */
    public function getPaginationToken()
    {
        return $this->pagination_token;
    }

    /**
     * Next page reference
     *
     * Generated from protobuf field <code>string pagination_token = 483104251 [json_name = "pagination-token"];</code>
     * @param string $var
     * @return $this
     */
    public function setPaginationToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->pagination_token = $var;

        return $this;
    }

    /**
     * Path to folder
     *
     * Generated from protobuf field <code>string path = 3433509 [json_name = "path"];</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Path to folder
     *
     * Generated from protobuf field <code>string path = 3433509 [json_name = "path"];</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Filter by items with SRA functionality enabled
     *
     * Generated from protobuf field <code>bool sra_only = 522067785 [json_name = "sra-only"];</code>
     * @return bool
     */
    public function getSraOnly()
    {
        return $this->sra_only;
    }

    /**
     * Filter by items with SRA functionality enabled
     *
     * Generated from protobuf field <code>bool sra_only = 522067785 [json_name = "sra-only"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSraOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->sra_only = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string sub_types = 41825862 [json_name = "sub_types"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSubTypes()
    {
        return $this->sub_types;
    }

    /**
     * Generated from protobuf field <code>repeated string sub_types = 41825862 [json_name = "sub_types"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSubTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->sub_types = $arr;

        return $this;
    }

    /**
     * Filter by item tag
     *
     * Generated from protobuf field <code>string tag = 114586 [json_name = "tag"];</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Filter by item tag
     *
     * Generated from protobuf field <code>string tag = 114586 [json_name = "tag"];</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;

        return $this;
    }

    /**
     * Authentication token (see `/auth` and `/configure`)
     *
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Authentication token (see `/auth` and `/configure`)
     *
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * The item types list of the requested items. In case it is empty, all types of items will be returned. options: [key, static-secret, dynamic-secret, classic-key]
     *
     * Generated from protobuf field <code>repeated string type = 3575610 [json_name = "type"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * The item types list of the requested items. In case it is empty, all types of items will be returned. options: [key, static-secret, dynamic-secret, classic-key]
     *
     * Generated from protobuf field <code>repeated string type = 3575610 [json_name = "type"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setType($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->type = $arr;

        return $this;
    }

    /**
     * The universal identity token, Required only for universal_identity authentication
     *
     * Generated from protobuf field <code>string uid_token = 468850238 [json_name = "uid-token"];</code>
     * @return string
     */
    public function getUidToken()
    {
        return $this->uid_token;
    }

    /**
     * The universal identity token, Required only for universal_identity authentication
     *
     * Generated from protobuf field <code>string uid_token = 468850238 [json_name = "uid-token"];</code>
     * @param string $var
     * @return $this
     */
    public function setUidToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->uid_token = $var;

        return $this;
    }

}

