<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/special_types.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.MapInt64</code>
 */
class MapInt64 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.akeyless_grpc.MapInt64 map = 1;</code>
     */
    protected $map = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Akeyless\gRPC\MapInt64 $map
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\SpecialTypes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.MapInt64 map = 1;</code>
     * @return \Akeyless\gRPC\MapInt64|null
     */
    public function getMap()
    {
        return $this->map;
    }

    public function hasMap()
    {
        return isset($this->map);
    }

    public function clearMap()
    {
        unset($this->map);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.MapInt64 map = 1;</code>
     * @param \Akeyless\gRPC\MapInt64 $var
     * @return $this
     */
    public function setMap($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\MapInt64::class);
        $this->map = $var;

        return $this;
    }

}

