<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/name.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.Name</code>
 */
class Name extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string country = 61870221 [json_name = "Country"];</code>
     */
    private $country;
    /**
     * ExtraNames contains attributes to be copied, raw, into any marshaled distinguished names. Values override any attributes with the same OID. The ExtraNames field is not populated when parsing, see Names.
     *
     * Generated from protobuf field <code>repeated .akeyless_grpc.AttributeTypeAndValue extra_names = 496158410 [json_name = "ExtraNames"];</code>
     */
    private $extra_names;
    /**
     * Generated from protobuf field <code>repeated string locality = 354836870 [json_name = "Locality"];</code>
     */
    private $locality;
    /**
     * Names contains all parsed attributes. When parsing distinguished names, this can be used to extract non-standard attributes that are not parsed by this package. When marshaling to RDNSequences, the Names field is ignored, see ExtraNames.
     *
     * Generated from protobuf field <code>repeated .akeyless_grpc.AttributeTypeAndValue names = 75032360 [json_name = "Names"];</code>
     */
    private $names;
    /**
     * Generated from protobuf field <code>string serial_number = 248107645 [json_name = "SerialNumber"];</code>
     */
    protected $serial_number = '';
    /**
     * Generated from protobuf field <code>repeated string street_address = 262380114 [json_name = "StreetAddress"];</code>
     */
    private $street_address;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $country
     *     @type array<\Akeyless\gRPC\AttributeTypeAndValue>|\Google\Protobuf\Internal\RepeatedField $extra_names
     *           ExtraNames contains attributes to be copied, raw, into any marshaled distinguished names. Values override any attributes with the same OID. The ExtraNames field is not populated when parsing, see Names.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $locality
     *     @type array<\Akeyless\gRPC\AttributeTypeAndValue>|\Google\Protobuf\Internal\RepeatedField $names
     *           Names contains all parsed attributes. When parsing distinguished names, this can be used to extract non-standard attributes that are not parsed by this package. When marshaling to RDNSequences, the Names field is ignored, see ExtraNames.
     *     @type string $serial_number
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $street_address
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\Name::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string country = 61870221 [json_name = "Country"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Generated from protobuf field <code>repeated string country = 61870221 [json_name = "Country"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCountry($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->country = $arr;

        return $this;
    }

    /**
     * ExtraNames contains attributes to be copied, raw, into any marshaled distinguished names. Values override any attributes with the same OID. The ExtraNames field is not populated when parsing, see Names.
     *
     * Generated from protobuf field <code>repeated .akeyless_grpc.AttributeTypeAndValue extra_names = 496158410 [json_name = "ExtraNames"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExtraNames()
    {
        return $this->extra_names;
    }

    /**
     * ExtraNames contains attributes to be copied, raw, into any marshaled distinguished names. Values override any attributes with the same OID. The ExtraNames field is not populated when parsing, see Names.
     *
     * Generated from protobuf field <code>repeated .akeyless_grpc.AttributeTypeAndValue extra_names = 496158410 [json_name = "ExtraNames"];</code>
     * @param array<\Akeyless\gRPC\AttributeTypeAndValue>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExtraNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\AttributeTypeAndValue::class);
        $this->extra_names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string locality = 354836870 [json_name = "Locality"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLocality()
    {
        return $this->locality;
    }

    /**
     * Generated from protobuf field <code>repeated string locality = 354836870 [json_name = "Locality"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLocality($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->locality = $arr;

        return $this;
    }

    /**
     * Names contains all parsed attributes. When parsing distinguished names, this can be used to extract non-standard attributes that are not parsed by this package. When marshaling to RDNSequences, the Names field is ignored, see ExtraNames.
     *
     * Generated from protobuf field <code>repeated .akeyless_grpc.AttributeTypeAndValue names = 75032360 [json_name = "Names"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNames()
    {
        return $this->names;
    }

    /**
     * Names contains all parsed attributes. When parsing distinguished names, this can be used to extract non-standard attributes that are not parsed by this package. When marshaling to RDNSequences, the Names field is ignored, see ExtraNames.
     *
     * Generated from protobuf field <code>repeated .akeyless_grpc.AttributeTypeAndValue names = 75032360 [json_name = "Names"];</code>
     * @param array<\Akeyless\gRPC\AttributeTypeAndValue>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNames($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\AttributeTypeAndValue::class);
        $this->names = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string serial_number = 248107645 [json_name = "SerialNumber"];</code>
     * @return string
     */
    public function getSerialNumber()
    {
        return $this->serial_number;
    }

    /**
     * Generated from protobuf field <code>string serial_number = 248107645 [json_name = "SerialNumber"];</code>
     * @param string $var
     * @return $this
     */
    public function setSerialNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->serial_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string street_address = 262380114 [json_name = "StreetAddress"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStreetAddress()
    {
        return $this->street_address;
    }

    /**
     * Generated from protobuf field <code>repeated string street_address = 262380114 [json_name = "StreetAddress"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStreetAddress($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->street_address = $arr;

        return $this;
    }

}

