<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/oidc_client_info.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.OidcClientInfo</code>
 */
class OidcClientInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.AccessOrGroupPermissionAssignment access_permission_assignment = 319962465 [json_name = "access_permission_assignment"];</code>
     */
    private $access_permission_assignment;
    /**
     * Generated from protobuf field <code>repeated string audience = 438757893 [json_name = "audience"];</code>
     */
    private $audience;
    /**
     * Generated from protobuf field <code>string client_id = 293476852 [json_name = "client_id"];</code>
     */
    protected $client_id = '';
    /**
     * Generated from protobuf field <code>repeated string grant_types = 41039767 [json_name = "grant_types"];</code>
     */
    private $grant_types;
    /**
     * Generated from protobuf field <code>string issuer_url = 386556651 [json_name = "issuer_url"];</code>
     */
    protected $issuer_url = '';
    /**
     * Generated from protobuf field <code>repeated string logout_uris = 119239199 [json_name = "logout_uris"];</code>
     */
    private $logout_uris;
    /**
     * Generated from protobuf field <code>bool public = 440552856 [json_name = "public"];</code>
     */
    protected $public = false;
    /**
     * Generated from protobuf field <code>repeated string redirect_uris = 39767287 [json_name = "redirect_uris"];</code>
     */
    private $redirect_uris;
    /**
     * Generated from protobuf field <code>repeated string response_types = 440720123 [json_name = "response_types"];</code>
     */
    private $response_types;
    /**
     * Generated from protobuf field <code>repeated string scopes = 370897762 [json_name = "scopes"];</code>
     */
    private $scopes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Akeyless\gRPC\AccessOrGroupPermissionAssignment>|\Google\Protobuf\Internal\RepeatedField $access_permission_assignment
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $audience
     *     @type string $client_id
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $grant_types
     *     @type string $issuer_url
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $logout_uris
     *     @type bool $public
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $redirect_uris
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $response_types
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $scopes
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\OidcClientInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.AccessOrGroupPermissionAssignment access_permission_assignment = 319962465 [json_name = "access_permission_assignment"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAccessPermissionAssignment()
    {
        return $this->access_permission_assignment;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.AccessOrGroupPermissionAssignment access_permission_assignment = 319962465 [json_name = "access_permission_assignment"];</code>
     * @param array<\Akeyless\gRPC\AccessOrGroupPermissionAssignment>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAccessPermissionAssignment($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\AccessOrGroupPermissionAssignment::class);
        $this->access_permission_assignment = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string audience = 438757893 [json_name = "audience"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAudience()
    {
        return $this->audience;
    }

    /**
     * Generated from protobuf field <code>repeated string audience = 438757893 [json_name = "audience"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAudience($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->audience = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_id = 293476852 [json_name = "client_id"];</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * Generated from protobuf field <code>string client_id = 293476852 [json_name = "client_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string grant_types = 41039767 [json_name = "grant_types"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGrantTypes()
    {
        return $this->grant_types;
    }

    /**
     * Generated from protobuf field <code>repeated string grant_types = 41039767 [json_name = "grant_types"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGrantTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->grant_types = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string issuer_url = 386556651 [json_name = "issuer_url"];</code>
     * @return string
     */
    public function getIssuerUrl()
    {
        return $this->issuer_url;
    }

    /**
     * Generated from protobuf field <code>string issuer_url = 386556651 [json_name = "issuer_url"];</code>
     * @param string $var
     * @return $this
     */
    public function setIssuerUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->issuer_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string logout_uris = 119239199 [json_name = "logout_uris"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLogoutUris()
    {
        return $this->logout_uris;
    }

    /**
     * Generated from protobuf field <code>repeated string logout_uris = 119239199 [json_name = "logout_uris"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLogoutUris($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->logout_uris = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool public = 440552856 [json_name = "public"];</code>
     * @return bool
     */
    public function getPublic()
    {
        return $this->public;
    }

    /**
     * Generated from protobuf field <code>bool public = 440552856 [json_name = "public"];</code>
     * @param bool $var
     * @return $this
     */
    public function setPublic($var)
    {
        GPBUtil::checkBool($var);
        $this->public = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string redirect_uris = 39767287 [json_name = "redirect_uris"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRedirectUris()
    {
        return $this->redirect_uris;
    }

    /**
     * Generated from protobuf field <code>repeated string redirect_uris = 39767287 [json_name = "redirect_uris"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRedirectUris($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->redirect_uris = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string response_types = 440720123 [json_name = "response_types"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResponseTypes()
    {
        return $this->response_types;
    }

    /**
     * Generated from protobuf field <code>repeated string response_types = 440720123 [json_name = "response_types"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResponseTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->response_types = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string scopes = 370897762 [json_name = "scopes"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getScopes()
    {
        return $this->scopes;
    }

    /**
     * Generated from protobuf field <code>repeated string scopes = 370897762 [json_name = "scopes"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setScopes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->scopes = $arr;

        return $this;
    }

}

