<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/password_policy_info.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.PasswordPolicyInfo</code>
 */
class PasswordPolicyInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 password_length = 87725817 [json_name = "password_length"];</code>
     */
    protected $password_length = 0;
    /**
     * Generated from protobuf field <code>bool use_capital_letters = 275313027 [json_name = "use_capital_letters"];</code>
     */
    protected $use_capital_letters = false;
    /**
     * Generated from protobuf field <code>bool use_lower_letters = 88440556 [json_name = "use_lower_letters"];</code>
     */
    protected $use_lower_letters = false;
    /**
     * Generated from protobuf field <code>bool use_numbers = 500532116 [json_name = "use_numbers"];</code>
     */
    protected $use_numbers = false;
    /**
     * Generated from protobuf field <code>bool use_special_characters = 53366936 [json_name = "use_special_characters"];</code>
     */
    protected $use_special_characters = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $password_length
     *     @type bool $use_capital_letters
     *     @type bool $use_lower_letters
     *     @type bool $use_numbers
     *     @type bool $use_special_characters
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\PasswordPolicyInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 password_length = 87725817 [json_name = "password_length"];</code>
     * @return int|string
     */
    public function getPasswordLength()
    {
        return $this->password_length;
    }

    /**
     * Generated from protobuf field <code>int64 password_length = 87725817 [json_name = "password_length"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setPasswordLength($var)
    {
        GPBUtil::checkInt64($var);
        $this->password_length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool use_capital_letters = 275313027 [json_name = "use_capital_letters"];</code>
     * @return bool
     */
    public function getUseCapitalLetters()
    {
        return $this->use_capital_letters;
    }

    /**
     * Generated from protobuf field <code>bool use_capital_letters = 275313027 [json_name = "use_capital_letters"];</code>
     * @param bool $var
     * @return $this
     */
    public function setUseCapitalLetters($var)
    {
        GPBUtil::checkBool($var);
        $this->use_capital_letters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool use_lower_letters = 88440556 [json_name = "use_lower_letters"];</code>
     * @return bool
     */
    public function getUseLowerLetters()
    {
        return $this->use_lower_letters;
    }

    /**
     * Generated from protobuf field <code>bool use_lower_letters = 88440556 [json_name = "use_lower_letters"];</code>
     * @param bool $var
     * @return $this
     */
    public function setUseLowerLetters($var)
    {
        GPBUtil::checkBool($var);
        $this->use_lower_letters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool use_numbers = 500532116 [json_name = "use_numbers"];</code>
     * @return bool
     */
    public function getUseNumbers()
    {
        return $this->use_numbers;
    }

    /**
     * Generated from protobuf field <code>bool use_numbers = 500532116 [json_name = "use_numbers"];</code>
     * @param bool $var
     * @return $this
     */
    public function setUseNumbers($var)
    {
        GPBUtil::checkBool($var);
        $this->use_numbers = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool use_special_characters = 53366936 [json_name = "use_special_characters"];</code>
     * @return bool
     */
    public function getUseSpecialCharacters()
    {
        return $this->use_special_characters;
    }

    /**
     * Generated from protobuf field <code>bool use_special_characters = 53366936 [json_name = "use_special_characters"];</code>
     * @param bool $var
     * @return $this
     */
    public function setUseSpecialCharacters($var)
    {
        GPBUtil::checkBool($var);
        $this->use_special_characters = $var;

        return $this;
    }

}

