<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/rotated_secret_details_info.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.RotatedSecretDetailsInfo</code>
 */
class RotatedSecretDetailsInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 delete_previous_version_in_days = 386273900 [json_name = "delete_previous_version_in_days"];</code>
     */
    protected $delete_previous_version_in_days = 0;
    /**
     * Generated from protobuf field <code>bool grace_rotation = 112349147 [json_name = "grace_rotation"];</code>
     */
    protected $grace_rotation = false;
    /**
     * Generated from protobuf field <code>int64 gw_cluster_id = 109299666 [json_name = "gw_cluster_id"];</code>
     */
    protected $gw_cluster_id = 0;
    /**
     * Generated from protobuf field <code>string last_rotation_error = 8402225 [json_name = "last_rotation_error"];</code>
     */
    protected $last_rotation_error = '';
    /**
     * Generated from protobuf field <code>int64 max_versions = 489956587 [json_name = "max_versions"];</code>
     */
    protected $max_versions = 0;
    /**
     * Generated from protobuf field <code>int32 number_of_versions_to_save = 225418611 [json_name = "number_of_versions_to_save"];</code>
     */
    protected $number_of_versions_to_save = 0;
    /**
     * Generated from protobuf field <code>int32 rotation_hour = 254189061 [json_name = "rotation_hour"];</code>
     */
    protected $rotation_hour = 0;
    /**
     * Generated from protobuf field <code>bool rotation_interval_min = 233650439 [json_name = "rotation_interval_min"];</code>
     */
    protected $rotation_interval_min = false;
    /**
     * Generated from protobuf field <code>string rotation_statement = 207252977 [json_name = "rotation_statement"];</code>
     */
    protected $rotation_statement = '';
    /**
     * Generated from protobuf field <code>string rotator_creds_type = 74941991 [json_name = "rotator_creds_type"];</code>
     */
    protected $rotator_creds_type = '';
    /**
     * RotationStatus defines types of rotation Status
     *
     * Generated from protobuf field <code>string rotator_status = 265195327 [json_name = "rotator_status"];</code>
     */
    protected $rotator_status = '';
    /**
     * Generated from protobuf field <code>string rotator_type = 447726454 [json_name = "rotator_type"];</code>
     */
    protected $rotator_type = '';
    /**
     * Generated from protobuf field <code>bool same_password = 57949781 [json_name = "same_password"];</code>
     */
    protected $same_password = false;
    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.WindowsService services_details = 290559135 [json_name = "services_details"];</code>
     */
    private $services_details;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $delete_previous_version_in_days
     *     @type bool $grace_rotation
     *     @type int|string $gw_cluster_id
     *     @type string $last_rotation_error
     *     @type int|string $max_versions
     *     @type int $number_of_versions_to_save
     *     @type int $rotation_hour
     *     @type bool $rotation_interval_min
     *     @type string $rotation_statement
     *     @type string $rotator_creds_type
     *     @type string $rotator_status
     *           RotationStatus defines types of rotation Status
     *     @type string $rotator_type
     *     @type bool $same_password
     *     @type array<\Akeyless\gRPC\WindowsService>|\Google\Protobuf\Internal\RepeatedField $services_details
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\RotatedSecretDetailsInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 delete_previous_version_in_days = 386273900 [json_name = "delete_previous_version_in_days"];</code>
     * @return int
     */
    public function getDeletePreviousVersionInDays()
    {
        return $this->delete_previous_version_in_days;
    }

    /**
     * Generated from protobuf field <code>int32 delete_previous_version_in_days = 386273900 [json_name = "delete_previous_version_in_days"];</code>
     * @param int $var
     * @return $this
     */
    public function setDeletePreviousVersionInDays($var)
    {
        GPBUtil::checkInt32($var);
        $this->delete_previous_version_in_days = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool grace_rotation = 112349147 [json_name = "grace_rotation"];</code>
     * @return bool
     */
    public function getGraceRotation()
    {
        return $this->grace_rotation;
    }

    /**
     * Generated from protobuf field <code>bool grace_rotation = 112349147 [json_name = "grace_rotation"];</code>
     * @param bool $var
     * @return $this
     */
    public function setGraceRotation($var)
    {
        GPBUtil::checkBool($var);
        $this->grace_rotation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 gw_cluster_id = 109299666 [json_name = "gw_cluster_id"];</code>
     * @return int|string
     */
    public function getGwClusterId()
    {
        return $this->gw_cluster_id;
    }

    /**
     * Generated from protobuf field <code>int64 gw_cluster_id = 109299666 [json_name = "gw_cluster_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setGwClusterId($var)
    {
        GPBUtil::checkInt64($var);
        $this->gw_cluster_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_rotation_error = 8402225 [json_name = "last_rotation_error"];</code>
     * @return string
     */
    public function getLastRotationError()
    {
        return $this->last_rotation_error;
    }

    /**
     * Generated from protobuf field <code>string last_rotation_error = 8402225 [json_name = "last_rotation_error"];</code>
     * @param string $var
     * @return $this
     */
    public function setLastRotationError($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_rotation_error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 max_versions = 489956587 [json_name = "max_versions"];</code>
     * @return int|string
     */
    public function getMaxVersions()
    {
        return $this->max_versions;
    }

    /**
     * Generated from protobuf field <code>int64 max_versions = 489956587 [json_name = "max_versions"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxVersions($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_versions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 number_of_versions_to_save = 225418611 [json_name = "number_of_versions_to_save"];</code>
     * @return int
     */
    public function getNumberOfVersionsToSave()
    {
        return $this->number_of_versions_to_save;
    }

    /**
     * Generated from protobuf field <code>int32 number_of_versions_to_save = 225418611 [json_name = "number_of_versions_to_save"];</code>
     * @param int $var
     * @return $this
     */
    public function setNumberOfVersionsToSave($var)
    {
        GPBUtil::checkInt32($var);
        $this->number_of_versions_to_save = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 rotation_hour = 254189061 [json_name = "rotation_hour"];</code>
     * @return int
     */
    public function getRotationHour()
    {
        return $this->rotation_hour;
    }

    /**
     * Generated from protobuf field <code>int32 rotation_hour = 254189061 [json_name = "rotation_hour"];</code>
     * @param int $var
     * @return $this
     */
    public function setRotationHour($var)
    {
        GPBUtil::checkInt32($var);
        $this->rotation_hour = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool rotation_interval_min = 233650439 [json_name = "rotation_interval_min"];</code>
     * @return bool
     */
    public function getRotationIntervalMin()
    {
        return $this->rotation_interval_min;
    }

    /**
     * Generated from protobuf field <code>bool rotation_interval_min = 233650439 [json_name = "rotation_interval_min"];</code>
     * @param bool $var
     * @return $this
     */
    public function setRotationIntervalMin($var)
    {
        GPBUtil::checkBool($var);
        $this->rotation_interval_min = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rotation_statement = 207252977 [json_name = "rotation_statement"];</code>
     * @return string
     */
    public function getRotationStatement()
    {
        return $this->rotation_statement;
    }

    /**
     * Generated from protobuf field <code>string rotation_statement = 207252977 [json_name = "rotation_statement"];</code>
     * @param string $var
     * @return $this
     */
    public function setRotationStatement($var)
    {
        GPBUtil::checkString($var, True);
        $this->rotation_statement = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rotator_creds_type = 74941991 [json_name = "rotator_creds_type"];</code>
     * @return string
     */
    public function getRotatorCredsType()
    {
        return $this->rotator_creds_type;
    }

    /**
     * Generated from protobuf field <code>string rotator_creds_type = 74941991 [json_name = "rotator_creds_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setRotatorCredsType($var)
    {
        GPBUtil::checkString($var, True);
        $this->rotator_creds_type = $var;

        return $this;
    }

    /**
     * RotationStatus defines types of rotation Status
     *
     * Generated from protobuf field <code>string rotator_status = 265195327 [json_name = "rotator_status"];</code>
     * @return string
     */
    public function getRotatorStatus()
    {
        return $this->rotator_status;
    }

    /**
     * RotationStatus defines types of rotation Status
     *
     * Generated from protobuf field <code>string rotator_status = 265195327 [json_name = "rotator_status"];</code>
     * @param string $var
     * @return $this
     */
    public function setRotatorStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->rotator_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rotator_type = 447726454 [json_name = "rotator_type"];</code>
     * @return string
     */
    public function getRotatorType()
    {
        return $this->rotator_type;
    }

    /**
     * Generated from protobuf field <code>string rotator_type = 447726454 [json_name = "rotator_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setRotatorType($var)
    {
        GPBUtil::checkString($var, True);
        $this->rotator_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool same_password = 57949781 [json_name = "same_password"];</code>
     * @return bool
     */
    public function getSamePassword()
    {
        return $this->same_password;
    }

    /**
     * Generated from protobuf field <code>bool same_password = 57949781 [json_name = "same_password"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSamePassword($var)
    {
        GPBUtil::checkBool($var);
        $this->same_password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.WindowsService services_details = 290559135 [json_name = "services_details"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServicesDetails()
    {
        return $this->services_details;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.WindowsService services_details = 290559135 [json_name = "services_details"];</code>
     * @param array<\Akeyless\gRPC\WindowsService>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServicesDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\WindowsService::class);
        $this->services_details = $arr;

        return $this;
    }

}

