<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/secure_remote_access.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.SecureRemoteAccess</code>
 */
class SecureRemoteAccess extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string account_id = 266462100 [json_name = "account_id"];</code>
     */
    protected $account_id = '';
    /**
     * Generated from protobuf field <code>bool allow_port_forwarding = 143305861 [json_name = "allow_port_forwarding"];</code>
     */
    protected $allow_port_forwarding = false;
    /**
     * Generated from protobuf field <code>bool allow_providing_external_username = 410658829 [json_name = "allow_providing_external_username"];</code>
     */
    protected $allow_providing_external_username = false;
    /**
     * Generated from protobuf field <code>string bastion_api = 231114111 [json_name = "bastion_api"];</code>
     */
    protected $bastion_api = '';
    /**
     * Generated from protobuf field <code>string bastion_issuer = 481242545 [json_name = "bastion_issuer"];</code>
     */
    protected $bastion_issuer = '';
    /**
     * Generated from protobuf field <code>int64 bastion_issuer_id = 440982006 [json_name = "bastion_issuer_id"];</code>
     */
    protected $bastion_issuer_id = 0;
    /**
     * Generated from protobuf field <code>string bastion_ssh = 231096721 [json_name = "bastion_ssh"];</code>
     */
    protected $bastion_ssh = '';
    /**
     * Generated from protobuf field <code>bool block_concurrent_connections = 18804035 [json_name = "block_concurrent_connections"];</code>
     */
    protected $block_concurrent_connections = false;
    /**
     * Generated from protobuf field <code>string block_concurrent_connections_level = 498088446 [json_name = "block_concurrent_connections_level"];</code>
     */
    protected $block_concurrent_connections_level = '';
    /**
     * Generated from protobuf field <code>string category = 50511102 [json_name = "category"];</code>
     */
    protected $category = '';
    /**
     * Generated from protobuf field <code>string dashboard_url = 161974973 [json_name = "dashboard_url"];</code>
     */
    protected $dashboard_url = '';
    /**
     * Generated from protobuf field <code>string db_name = 379078062 [json_name = "db_name"];</code>
     */
    protected $db_name = '';
    /**
     * Generated from protobuf field <code>string domain = 252455742 [json_name = "domain"];</code>
     */
    protected $domain = '';
    /**
     * Generated from protobuf field <code>bool enable = 225106559 [json_name = "enable"];</code>
     */
    protected $enable = false;
    /**
     * Generated from protobuf field <code>string endpoint = 130489752 [json_name = "endpoint"];</code>
     */
    protected $endpoint = '';
    /**
     * Generated from protobuf field <code>repeated string host = 3208616 [json_name = "host"];</code>
     */
    private $host;
    /**
     * Generated from protobuf field <code>string host_provider_type = 327937425 [json_name = "host_provider_type"];</code>
     */
    protected $host_provider_type = '';
    /**
     * Generated from protobuf field <code>bool is_cli = 106030967 [json_name = "is_cli"];</code>
     */
    protected $is_cli = false;
    /**
     * Generated from protobuf field <code>bool is_web = 106011971 [json_name = "is_web"];</code>
     */
    protected $is_web = false;
    /**
     * Generated from protobuf field <code>bool isolated = 38909210 [json_name = "isolated"];</code>
     */
    protected $isolated = false;
    /**
     * Generated from protobuf field <code>bool native = 515747818 [json_name = "native"];</code>
     */
    protected $native = false;
    /**
     * Generated from protobuf field <code>string rd_gateway_server = 479790923 [json_name = "rd_gateway_server"];</code>
     */
    protected $rd_gateway_server = '';
    /**
     * Generated from protobuf field <code>string rdp_user = 255489302 [json_name = "rdp_user"];</code>
     */
    protected $rdp_user = '';
    /**
     * Generated from protobuf field <code>string region = 397924621 [json_name = "region"];</code>
     */
    protected $region = '';
    /**
     * Generated from protobuf field <code>bool rotate_after_disconnect = 184102211 [json_name = "rotate_after_disconnect"];</code>
     */
    protected $rotate_after_disconnect = false;
    /**
     * Generated from protobuf field <code>string schema = 371116640 [json_name = "schema"];</code>
     */
    protected $schema = '';
    /**
     * Generated from protobuf field <code>bool ssh_password = 481397006 [json_name = "ssh_password"];</code>
     */
    protected $ssh_password = false;
    /**
     * Generated from protobuf field <code>bool ssh_private_key = 165857772 [json_name = "ssh_private_key"];</code>
     */
    protected $ssh_private_key = false;
    /**
     * Generated from protobuf field <code>string ssh_user = 75328419 [json_name = "ssh_user"];</code>
     */
    protected $ssh_user = '';
    /**
     * Generated from protobuf field <code>.akeyless_grpc.ItemSraStatus status_info = 354650918 [json_name = "status_info"];</code>
     */
    protected $status_info = null;
    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.TargetNameWithHosts target_hosts = 208182371 [json_name = "target_hosts"];</code>
     */
    private $target_hosts;
    /**
     * Generated from protobuf field <code>repeated string targets = 464535296 [json_name = "targets"];</code>
     */
    private $targets;
    /**
     * Generated from protobuf field <code>string url = 116079 [json_name = "url"];</code>
     */
    protected $url = '';
    /**
     * Generated from protobuf field <code>bool use_internal_bastion = 222003552 [json_name = "use_internal_bastion"];</code>
     */
    protected $use_internal_bastion = false;
    /**
     * Generated from protobuf field <code>bool web_proxy = 263902782 [json_name = "web_proxy"];</code>
     */
    protected $web_proxy = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $account_id
     *     @type bool $allow_port_forwarding
     *     @type bool $allow_providing_external_username
     *     @type string $bastion_api
     *     @type string $bastion_issuer
     *     @type int|string $bastion_issuer_id
     *     @type string $bastion_ssh
     *     @type bool $block_concurrent_connections
     *     @type string $block_concurrent_connections_level
     *     @type string $category
     *     @type string $dashboard_url
     *     @type string $db_name
     *     @type string $domain
     *     @type bool $enable
     *     @type string $endpoint
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $host
     *     @type string $host_provider_type
     *     @type bool $is_cli
     *     @type bool $is_web
     *     @type bool $isolated
     *     @type bool $native
     *     @type string $rd_gateway_server
     *     @type string $rdp_user
     *     @type string $region
     *     @type bool $rotate_after_disconnect
     *     @type string $schema
     *     @type bool $ssh_password
     *     @type bool $ssh_private_key
     *     @type string $ssh_user
     *     @type \Akeyless\gRPC\ItemSraStatus $status_info
     *     @type array<\Akeyless\gRPC\TargetNameWithHosts>|\Google\Protobuf\Internal\RepeatedField $target_hosts
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $targets
     *     @type string $url
     *     @type bool $use_internal_bastion
     *     @type bool $web_proxy
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\SecureRemoteAccess::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string account_id = 266462100 [json_name = "account_id"];</code>
     * @return string
     */
    public function getAccountId()
    {
        return $this->account_id;
    }

    /**
     * Generated from protobuf field <code>string account_id = 266462100 [json_name = "account_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccountId($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool allow_port_forwarding = 143305861 [json_name = "allow_port_forwarding"];</code>
     * @return bool
     */
    public function getAllowPortForwarding()
    {
        return $this->allow_port_forwarding;
    }

    /**
     * Generated from protobuf field <code>bool allow_port_forwarding = 143305861 [json_name = "allow_port_forwarding"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAllowPortForwarding($var)
    {
        GPBUtil::checkBool($var);
        $this->allow_port_forwarding = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool allow_providing_external_username = 410658829 [json_name = "allow_providing_external_username"];</code>
     * @return bool
     */
    public function getAllowProvidingExternalUsername()
    {
        return $this->allow_providing_external_username;
    }

    /**
     * Generated from protobuf field <code>bool allow_providing_external_username = 410658829 [json_name = "allow_providing_external_username"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAllowProvidingExternalUsername($var)
    {
        GPBUtil::checkBool($var);
        $this->allow_providing_external_username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bastion_api = 231114111 [json_name = "bastion_api"];</code>
     * @return string
     */
    public function getBastionApi()
    {
        return $this->bastion_api;
    }

    /**
     * Generated from protobuf field <code>string bastion_api = 231114111 [json_name = "bastion_api"];</code>
     * @param string $var
     * @return $this
     */
    public function setBastionApi($var)
    {
        GPBUtil::checkString($var, True);
        $this->bastion_api = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bastion_issuer = 481242545 [json_name = "bastion_issuer"];</code>
     * @return string
     */
    public function getBastionIssuer()
    {
        return $this->bastion_issuer;
    }

    /**
     * Generated from protobuf field <code>string bastion_issuer = 481242545 [json_name = "bastion_issuer"];</code>
     * @param string $var
     * @return $this
     */
    public function setBastionIssuer($var)
    {
        GPBUtil::checkString($var, True);
        $this->bastion_issuer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 bastion_issuer_id = 440982006 [json_name = "bastion_issuer_id"];</code>
     * @return int|string
     */
    public function getBastionIssuerId()
    {
        return $this->bastion_issuer_id;
    }

    /**
     * Generated from protobuf field <code>int64 bastion_issuer_id = 440982006 [json_name = "bastion_issuer_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setBastionIssuerId($var)
    {
        GPBUtil::checkInt64($var);
        $this->bastion_issuer_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bastion_ssh = 231096721 [json_name = "bastion_ssh"];</code>
     * @return string
     */
    public function getBastionSsh()
    {
        return $this->bastion_ssh;
    }

    /**
     * Generated from protobuf field <code>string bastion_ssh = 231096721 [json_name = "bastion_ssh"];</code>
     * @param string $var
     * @return $this
     */
    public function setBastionSsh($var)
    {
        GPBUtil::checkString($var, True);
        $this->bastion_ssh = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool block_concurrent_connections = 18804035 [json_name = "block_concurrent_connections"];</code>
     * @return bool
     */
    public function getBlockConcurrentConnections()
    {
        return $this->block_concurrent_connections;
    }

    /**
     * Generated from protobuf field <code>bool block_concurrent_connections = 18804035 [json_name = "block_concurrent_connections"];</code>
     * @param bool $var
     * @return $this
     */
    public function setBlockConcurrentConnections($var)
    {
        GPBUtil::checkBool($var);
        $this->block_concurrent_connections = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string block_concurrent_connections_level = 498088446 [json_name = "block_concurrent_connections_level"];</code>
     * @return string
     */
    public function getBlockConcurrentConnectionsLevel()
    {
        return $this->block_concurrent_connections_level;
    }

    /**
     * Generated from protobuf field <code>string block_concurrent_connections_level = 498088446 [json_name = "block_concurrent_connections_level"];</code>
     * @param string $var
     * @return $this
     */
    public function setBlockConcurrentConnectionsLevel($var)
    {
        GPBUtil::checkString($var, True);
        $this->block_concurrent_connections_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string category = 50511102 [json_name = "category"];</code>
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Generated from protobuf field <code>string category = 50511102 [json_name = "category"];</code>
     * @param string $var
     * @return $this
     */
    public function setCategory($var)
    {
        GPBUtil::checkString($var, True);
        $this->category = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dashboard_url = 161974973 [json_name = "dashboard_url"];</code>
     * @return string
     */
    public function getDashboardUrl()
    {
        return $this->dashboard_url;
    }

    /**
     * Generated from protobuf field <code>string dashboard_url = 161974973 [json_name = "dashboard_url"];</code>
     * @param string $var
     * @return $this
     */
    public function setDashboardUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->dashboard_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string db_name = 379078062 [json_name = "db_name"];</code>
     * @return string
     */
    public function getDbName()
    {
        return $this->db_name;
    }

    /**
     * Generated from protobuf field <code>string db_name = 379078062 [json_name = "db_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setDbName($var)
    {
        GPBUtil::checkString($var, True);
        $this->db_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string domain = 252455742 [json_name = "domain"];</code>
     * @return string
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * Generated from protobuf field <code>string domain = 252455742 [json_name = "domain"];</code>
     * @param string $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->domain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enable = 225106559 [json_name = "enable"];</code>
     * @return bool
     */
    public function getEnable()
    {
        return $this->enable;
    }

    /**
     * Generated from protobuf field <code>bool enable = 225106559 [json_name = "enable"];</code>
     * @param bool $var
     * @return $this
     */
    public function setEnable($var)
    {
        GPBUtil::checkBool($var);
        $this->enable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string endpoint = 130489752 [json_name = "endpoint"];</code>
     * @return string
     */
    public function getEndpoint()
    {
        return $this->endpoint;
    }

    /**
     * Generated from protobuf field <code>string endpoint = 130489752 [json_name = "endpoint"];</code>
     * @param string $var
     * @return $this
     */
    public function setEndpoint($var)
    {
        GPBUtil::checkString($var, True);
        $this->endpoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string host = 3208616 [json_name = "host"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Generated from protobuf field <code>repeated string host = 3208616 [json_name = "host"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHost($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->host = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string host_provider_type = 327937425 [json_name = "host_provider_type"];</code>
     * @return string
     */
    public function getHostProviderType()
    {
        return $this->host_provider_type;
    }

    /**
     * Generated from protobuf field <code>string host_provider_type = 327937425 [json_name = "host_provider_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setHostProviderType($var)
    {
        GPBUtil::checkString($var, True);
        $this->host_provider_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_cli = 106030967 [json_name = "is_cli"];</code>
     * @return bool
     */
    public function getIsCli()
    {
        return $this->is_cli;
    }

    /**
     * Generated from protobuf field <code>bool is_cli = 106030967 [json_name = "is_cli"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsCli($var)
    {
        GPBUtil::checkBool($var);
        $this->is_cli = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_web = 106011971 [json_name = "is_web"];</code>
     * @return bool
     */
    public function getIsWeb()
    {
        return $this->is_web;
    }

    /**
     * Generated from protobuf field <code>bool is_web = 106011971 [json_name = "is_web"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsWeb($var)
    {
        GPBUtil::checkBool($var);
        $this->is_web = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool isolated = 38909210 [json_name = "isolated"];</code>
     * @return bool
     */
    public function getIsolated()
    {
        return $this->isolated;
    }

    /**
     * Generated from protobuf field <code>bool isolated = 38909210 [json_name = "isolated"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsolated($var)
    {
        GPBUtil::checkBool($var);
        $this->isolated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool native = 515747818 [json_name = "native"];</code>
     * @return bool
     */
    public function getNative()
    {
        return $this->native;
    }

    /**
     * Generated from protobuf field <code>bool native = 515747818 [json_name = "native"];</code>
     * @param bool $var
     * @return $this
     */
    public function setNative($var)
    {
        GPBUtil::checkBool($var);
        $this->native = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rd_gateway_server = 479790923 [json_name = "rd_gateway_server"];</code>
     * @return string
     */
    public function getRdGatewayServer()
    {
        return $this->rd_gateway_server;
    }

    /**
     * Generated from protobuf field <code>string rd_gateway_server = 479790923 [json_name = "rd_gateway_server"];</code>
     * @param string $var
     * @return $this
     */
    public function setRdGatewayServer($var)
    {
        GPBUtil::checkString($var, True);
        $this->rd_gateway_server = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string rdp_user = 255489302 [json_name = "rdp_user"];</code>
     * @return string
     */
    public function getRdpUser()
    {
        return $this->rdp_user;
    }

    /**
     * Generated from protobuf field <code>string rdp_user = 255489302 [json_name = "rdp_user"];</code>
     * @param string $var
     * @return $this
     */
    public function setRdpUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->rdp_user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string region = 397924621 [json_name = "region"];</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * Generated from protobuf field <code>string region = 397924621 [json_name = "region"];</code>
     * @param string $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkString($var, True);
        $this->region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool rotate_after_disconnect = 184102211 [json_name = "rotate_after_disconnect"];</code>
     * @return bool
     */
    public function getRotateAfterDisconnect()
    {
        return $this->rotate_after_disconnect;
    }

    /**
     * Generated from protobuf field <code>bool rotate_after_disconnect = 184102211 [json_name = "rotate_after_disconnect"];</code>
     * @param bool $var
     * @return $this
     */
    public function setRotateAfterDisconnect($var)
    {
        GPBUtil::checkBool($var);
        $this->rotate_after_disconnect = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string schema = 371116640 [json_name = "schema"];</code>
     * @return string
     */
    public function getSchema()
    {
        return $this->schema;
    }

    /**
     * Generated from protobuf field <code>string schema = 371116640 [json_name = "schema"];</code>
     * @param string $var
     * @return $this
     */
    public function setSchema($var)
    {
        GPBUtil::checkString($var, True);
        $this->schema = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ssh_password = 481397006 [json_name = "ssh_password"];</code>
     * @return bool
     */
    public function getSshPassword()
    {
        return $this->ssh_password;
    }

    /**
     * Generated from protobuf field <code>bool ssh_password = 481397006 [json_name = "ssh_password"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSshPassword($var)
    {
        GPBUtil::checkBool($var);
        $this->ssh_password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool ssh_private_key = 165857772 [json_name = "ssh_private_key"];</code>
     * @return bool
     */
    public function getSshPrivateKey()
    {
        return $this->ssh_private_key;
    }

    /**
     * Generated from protobuf field <code>bool ssh_private_key = 165857772 [json_name = "ssh_private_key"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSshPrivateKey($var)
    {
        GPBUtil::checkBool($var);
        $this->ssh_private_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ssh_user = 75328419 [json_name = "ssh_user"];</code>
     * @return string
     */
    public function getSshUser()
    {
        return $this->ssh_user;
    }

    /**
     * Generated from protobuf field <code>string ssh_user = 75328419 [json_name = "ssh_user"];</code>
     * @param string $var
     * @return $this
     */
    public function setSshUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->ssh_user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.ItemSraStatus status_info = 354650918 [json_name = "status_info"];</code>
     * @return \Akeyless\gRPC\ItemSraStatus|null
     */
    public function getStatusInfo()
    {
        return $this->status_info;
    }

    public function hasStatusInfo()
    {
        return isset($this->status_info);
    }

    public function clearStatusInfo()
    {
        unset($this->status_info);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.ItemSraStatus status_info = 354650918 [json_name = "status_info"];</code>
     * @param \Akeyless\gRPC\ItemSraStatus $var
     * @return $this
     */
    public function setStatusInfo($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\ItemSraStatus::class);
        $this->status_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.TargetNameWithHosts target_hosts = 208182371 [json_name = "target_hosts"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTargetHosts()
    {
        return $this->target_hosts;
    }

    /**
     * Generated from protobuf field <code>repeated .akeyless_grpc.TargetNameWithHosts target_hosts = 208182371 [json_name = "target_hosts"];</code>
     * @param array<\Akeyless\gRPC\TargetNameWithHosts>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTargetHosts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Akeyless\gRPC\TargetNameWithHosts::class);
        $this->target_hosts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string targets = 464535296 [json_name = "targets"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTargets()
    {
        return $this->targets;
    }

    /**
     * Generated from protobuf field <code>repeated string targets = 464535296 [json_name = "targets"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTargets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->targets = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 116079 [json_name = "url"];</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 116079 [json_name = "url"];</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool use_internal_bastion = 222003552 [json_name = "use_internal_bastion"];</code>
     * @return bool
     */
    public function getUseInternalBastion()
    {
        return $this->use_internal_bastion;
    }

    /**
     * Generated from protobuf field <code>bool use_internal_bastion = 222003552 [json_name = "use_internal_bastion"];</code>
     * @param bool $var
     * @return $this
     */
    public function setUseInternalBastion($var)
    {
        GPBUtil::checkBool($var);
        $this->use_internal_bastion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool web_proxy = 263902782 [json_name = "web_proxy"];</code>
     * @return bool
     */
    public function getWebProxy()
    {
        return $this->web_proxy;
    }

    /**
     * Generated from protobuf field <code>bool web_proxy = 263902782 [json_name = "web_proxy"];</code>
     * @param bool $var
     * @return $this
     */
    public function setWebProxy($var)
    {
        GPBUtil::checkBool($var);
        $this->web_proxy = $var;

        return $this;
    }

}

