<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/ssh_certificate_issue_details.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.SshCertificateIssueDetails</code>
 */
class SshCertificateIssueDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * Relevant for host certificate
     *
     * Generated from protobuf field <code>repeated string allowed_domains = 417577833 [json_name = "allowed_domains"];</code>
     */
    private $allowed_domains;
    /**
     * Generated from protobuf field <code>.akeyless_grpc.MapInt64 allowed_user_key_lengths = 216821683 [json_name = "allowed_user_key_lengths"];</code>
     */
    protected $allowed_user_key_lengths = null;
    /**
     * Relevant for user certificate
     *
     * Generated from protobuf field <code>repeated string allowed_users = 180153170 [json_name = "allowed_users"];</code>
     */
    private $allowed_users;
    /**
     * Generated from protobuf field <code>int32 cert_type = 331910029 [json_name = "cert_type"];</code>
     */
    protected $cert_type = 0;
    /**
     * Generated from protobuf field <code>map<string, string> critical_options = 294360574 [json_name = "critical_options"];</code>
     */
    private $critical_options;
    /**
     * Generated from protobuf field <code>map<string, string> extensions = 198808559 [json_name = "extensions"];</code>
     */
    private $extensions;
    /**
     * Generated from protobuf field <code>repeated string principals = 338717179 [json_name = "principals"];</code>
     */
    private $principals;
    /**
     * In case it is empty, the key ID will be combination of user identifiers and a random string
     *
     * Generated from protobuf field <code>string static_key_id = 389937644 [json_name = "static_key_id"];</code>
     */
    protected $static_key_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $allowed_domains
     *           Relevant for host certificate
     *     @type \Akeyless\gRPC\MapInt64 $allowed_user_key_lengths
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $allowed_users
     *           Relevant for user certificate
     *     @type int $cert_type
     *     @type array|\Google\Protobuf\Internal\MapField $critical_options
     *     @type array|\Google\Protobuf\Internal\MapField $extensions
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $principals
     *     @type string $static_key_id
     *           In case it is empty, the key ID will be combination of user identifiers and a random string
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\SshCertificateIssueDetails::initOnce();
        parent::__construct($data);
    }

    /**
     * Relevant for host certificate
     *
     * Generated from protobuf field <code>repeated string allowed_domains = 417577833 [json_name = "allowed_domains"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllowedDomains()
    {
        return $this->allowed_domains;
    }

    /**
     * Relevant for host certificate
     *
     * Generated from protobuf field <code>repeated string allowed_domains = 417577833 [json_name = "allowed_domains"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllowedDomains($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->allowed_domains = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.MapInt64 allowed_user_key_lengths = 216821683 [json_name = "allowed_user_key_lengths"];</code>
     * @return \Akeyless\gRPC\MapInt64|null
     */
    public function getAllowedUserKeyLengths()
    {
        return $this->allowed_user_key_lengths;
    }

    public function hasAllowedUserKeyLengths()
    {
        return isset($this->allowed_user_key_lengths);
    }

    public function clearAllowedUserKeyLengths()
    {
        unset($this->allowed_user_key_lengths);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.MapInt64 allowed_user_key_lengths = 216821683 [json_name = "allowed_user_key_lengths"];</code>
     * @param \Akeyless\gRPC\MapInt64 $var
     * @return $this
     */
    public function setAllowedUserKeyLengths($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\MapInt64::class);
        $this->allowed_user_key_lengths = $var;

        return $this;
    }

    /**
     * Relevant for user certificate
     *
     * Generated from protobuf field <code>repeated string allowed_users = 180153170 [json_name = "allowed_users"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllowedUsers()
    {
        return $this->allowed_users;
    }

    /**
     * Relevant for user certificate
     *
     * Generated from protobuf field <code>repeated string allowed_users = 180153170 [json_name = "allowed_users"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllowedUsers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->allowed_users = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 cert_type = 331910029 [json_name = "cert_type"];</code>
     * @return int
     */
    public function getCertType()
    {
        return $this->cert_type;
    }

    /**
     * Generated from protobuf field <code>int32 cert_type = 331910029 [json_name = "cert_type"];</code>
     * @param int $var
     * @return $this
     */
    public function setCertType($var)
    {
        GPBUtil::checkInt32($var);
        $this->cert_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> critical_options = 294360574 [json_name = "critical_options"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCriticalOptions()
    {
        return $this->critical_options;
    }

    /**
     * Generated from protobuf field <code>map<string, string> critical_options = 294360574 [json_name = "critical_options"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCriticalOptions($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->critical_options = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> extensions = 198808559 [json_name = "extensions"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    /**
     * Generated from protobuf field <code>map<string, string> extensions = 198808559 [json_name = "extensions"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setExtensions($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->extensions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string principals = 338717179 [json_name = "principals"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrincipals()
    {
        return $this->principals;
    }

    /**
     * Generated from protobuf field <code>repeated string principals = 338717179 [json_name = "principals"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrincipals($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->principals = $arr;

        return $this;
    }

    /**
     * In case it is empty, the key ID will be combination of user identifiers and a random string
     *
     * Generated from protobuf field <code>string static_key_id = 389937644 [json_name = "static_key_id"];</code>
     * @return string
     */
    public function getStaticKeyId()
    {
        return $this->static_key_id;
    }

    /**
     * In case it is empty, the key ID will be combination of user identifiers and a random string
     *
     * Generated from protobuf field <code>string static_key_id = 389937644 [json_name = "static_key_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setStaticKeyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->static_key_id = $var;

        return $this;
    }

}

