<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/system_access_credentials_reply_obj.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.SystemAccessCredentialsReplyObj</code>
 */
class SystemAccessCredentialsReplyObj extends \Google\Protobuf\Internal\Message
{
    /**
     * Temporary credentials for accessing Auth
     *
     * Generated from protobuf field <code>string auth_creds = 361770101 [json_name = "auth_creds"];</code>
     */
    protected $auth_creds = '';
    /**
     * Credentials expiration date
     *
     * Generated from protobuf field <code>int64 expiry = 215417551 [json_name = "expiry"];</code>
     */
    protected $expiry = 0;
    /**
     * Temporary credentials for accessing the KFMs instances
     *
     * Generated from protobuf field <code>string kfm_creds = 367110955 [json_name = "kfm_creds"];</code>
     */
    protected $kfm_creds = '';
    /**
     * Generated from protobuf field <code>string required_mfa = 17753787 [json_name = "required_mfa"];</code>
     */
    protected $required_mfa = '';
    /**
     * Credentials tmp token
     *
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     */
    protected $token = '';
    /**
     * Temporary credentials for accessing the UAM service
     *
     * Generated from protobuf field <code>string uam_creds = 224709257 [json_name = "uam_creds"];</code>
     */
    protected $uam_creds = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $auth_creds
     *           Temporary credentials for accessing Auth
     *     @type int|string $expiry
     *           Credentials expiration date
     *     @type string $kfm_creds
     *           Temporary credentials for accessing the KFMs instances
     *     @type string $required_mfa
     *     @type string $token
     *           Credentials tmp token
     *     @type string $uam_creds
     *           Temporary credentials for accessing the UAM service
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\SystemAccessCredentialsReplyObj::initOnce();
        parent::__construct($data);
    }

    /**
     * Temporary credentials for accessing Auth
     *
     * Generated from protobuf field <code>string auth_creds = 361770101 [json_name = "auth_creds"];</code>
     * @return string
     */
    public function getAuthCreds()
    {
        return $this->auth_creds;
    }

    /**
     * Temporary credentials for accessing Auth
     *
     * Generated from protobuf field <code>string auth_creds = 361770101 [json_name = "auth_creds"];</code>
     * @param string $var
     * @return $this
     */
    public function setAuthCreds($var)
    {
        GPBUtil::checkString($var, True);
        $this->auth_creds = $var;

        return $this;
    }

    /**
     * Credentials expiration date
     *
     * Generated from protobuf field <code>int64 expiry = 215417551 [json_name = "expiry"];</code>
     * @return int|string
     */
    public function getExpiry()
    {
        return $this->expiry;
    }

    /**
     * Credentials expiration date
     *
     * Generated from protobuf field <code>int64 expiry = 215417551 [json_name = "expiry"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiry($var)
    {
        GPBUtil::checkInt64($var);
        $this->expiry = $var;

        return $this;
    }

    /**
     * Temporary credentials for accessing the KFMs instances
     *
     * Generated from protobuf field <code>string kfm_creds = 367110955 [json_name = "kfm_creds"];</code>
     * @return string
     */
    public function getKfmCreds()
    {
        return $this->kfm_creds;
    }

    /**
     * Temporary credentials for accessing the KFMs instances
     *
     * Generated from protobuf field <code>string kfm_creds = 367110955 [json_name = "kfm_creds"];</code>
     * @param string $var
     * @return $this
     */
    public function setKfmCreds($var)
    {
        GPBUtil::checkString($var, True);
        $this->kfm_creds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string required_mfa = 17753787 [json_name = "required_mfa"];</code>
     * @return string
     */
    public function getRequiredMfa()
    {
        return $this->required_mfa;
    }

    /**
     * Generated from protobuf field <code>string required_mfa = 17753787 [json_name = "required_mfa"];</code>
     * @param string $var
     * @return $this
     */
    public function setRequiredMfa($var)
    {
        GPBUtil::checkString($var, True);
        $this->required_mfa = $var;

        return $this;
    }

    /**
     * Credentials tmp token
     *
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Credentials tmp token
     *
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * Temporary credentials for accessing the UAM service
     *
     * Generated from protobuf field <code>string uam_creds = 224709257 [json_name = "uam_creds"];</code>
     * @return string
     */
    public function getUamCreds()
    {
        return $this->uam_creds;
    }

    /**
     * Temporary credentials for accessing the UAM service
     *
     * Generated from protobuf field <code>string uam_creds = 224709257 [json_name = "uam_creds"];</code>
     * @param string $var
     * @return $this
     */
    public function setUamCreds($var)
    {
        GPBUtil::checkString($var, True);
        $this->uam_creds = $var;

        return $this;
    }

}

