<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/target_item_version.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.TargetItemVersion</code>
 */
class TargetItemVersion extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string access_date = 495996504 [json_name = "access_date"];</code>
     */
    protected $access_date = '';
    /**
     * Generated from protobuf field <code>string access_date_display = 93370412 [json_name = "access_date_display"];</code>
     */
    protected $access_date_display = '';
    /**
     * Generated from protobuf field <code>.akeyless_grpc.CertificateVersionInfo certificate_version_info = 461177507 [json_name = "certificate_version_info"];</code>
     */
    protected $certificate_version_info = null;
    /**
     * Generated from protobuf field <code>string creation_date = 321236241 [json_name = "creation_date"];</code>
     */
    protected $creation_date = '';
    /**
     * Generated from protobuf field <code>string customer_fragment_id = 110711159 [json_name = "customer_fragment_id"];</code>
     */
    protected $customer_fragment_id = '';
    /**
     * Generated from protobuf field <code>string deletion_date = 519441025 [json_name = "deletion_date"];</code>
     */
    protected $deletion_date = '';
    /**
     * ItemState defines the different states an Item can be in
     *
     * Generated from protobuf field <code>string item_version_state = 508677573 [json_name = "item_version_state"];</code>
     */
    protected $item_version_state = '';
    /**
     * Generated from protobuf field <code>bool latest_version = 292871203 [json_name = "latest_version"];</code>
     */
    protected $latest_version = false;
    /**
     * Generated from protobuf field <code>string modification_date = 202999697 [json_name = "modification_date"];</code>
     */
    protected $modification_date = '';
    /**
     * Generated from protobuf field <code>string protection_key_name = 80474900 [json_name = "protection_key_name"];</code>
     */
    protected $protection_key_name = '';
    /**
     * Generated from protobuf field <code>string target_name = 474147722 [json_name = "target_name"];</code>
     */
    protected $target_name = '';
    /**
     * Generated from protobuf field <code>int32 version = 351608024 [json_name = "version"];</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>bool with_customer_fragment = 40616536 [json_name = "with_customer_fragment"];</code>
     */
    protected $with_customer_fragment = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $access_date
     *     @type string $access_date_display
     *     @type \Akeyless\gRPC\CertificateVersionInfo $certificate_version_info
     *     @type string $creation_date
     *     @type string $customer_fragment_id
     *     @type string $deletion_date
     *     @type string $item_version_state
     *           ItemState defines the different states an Item can be in
     *     @type bool $latest_version
     *     @type string $modification_date
     *     @type string $protection_key_name
     *     @type string $target_name
     *     @type int $version
     *     @type bool $with_customer_fragment
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\TargetItemVersion::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string access_date = 495996504 [json_name = "access_date"];</code>
     * @return string
     */
    public function getAccessDate()
    {
        return $this->access_date;
    }

    /**
     * Generated from protobuf field <code>string access_date = 495996504 [json_name = "access_date"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccessDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string access_date_display = 93370412 [json_name = "access_date_display"];</code>
     * @return string
     */
    public function getAccessDateDisplay()
    {
        return $this->access_date_display;
    }

    /**
     * Generated from protobuf field <code>string access_date_display = 93370412 [json_name = "access_date_display"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccessDateDisplay($var)
    {
        GPBUtil::checkString($var, True);
        $this->access_date_display = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.CertificateVersionInfo certificate_version_info = 461177507 [json_name = "certificate_version_info"];</code>
     * @return \Akeyless\gRPC\CertificateVersionInfo|null
     */
    public function getCertificateVersionInfo()
    {
        return $this->certificate_version_info;
    }

    public function hasCertificateVersionInfo()
    {
        return isset($this->certificate_version_info);
    }

    public function clearCertificateVersionInfo()
    {
        unset($this->certificate_version_info);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.CertificateVersionInfo certificate_version_info = 461177507 [json_name = "certificate_version_info"];</code>
     * @param \Akeyless\gRPC\CertificateVersionInfo $var
     * @return $this
     */
    public function setCertificateVersionInfo($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\CertificateVersionInfo::class);
        $this->certificate_version_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string creation_date = 321236241 [json_name = "creation_date"];</code>
     * @return string
     */
    public function getCreationDate()
    {
        return $this->creation_date;
    }

    /**
     * Generated from protobuf field <code>string creation_date = 321236241 [json_name = "creation_date"];</code>
     * @param string $var
     * @return $this
     */
    public function setCreationDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->creation_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string customer_fragment_id = 110711159 [json_name = "customer_fragment_id"];</code>
     * @return string
     */
    public function getCustomerFragmentId()
    {
        return $this->customer_fragment_id;
    }

    /**
     * Generated from protobuf field <code>string customer_fragment_id = 110711159 [json_name = "customer_fragment_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setCustomerFragmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->customer_fragment_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string deletion_date = 519441025 [json_name = "deletion_date"];</code>
     * @return string
     */
    public function getDeletionDate()
    {
        return $this->deletion_date;
    }

    /**
     * Generated from protobuf field <code>string deletion_date = 519441025 [json_name = "deletion_date"];</code>
     * @param string $var
     * @return $this
     */
    public function setDeletionDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->deletion_date = $var;

        return $this;
    }

    /**
     * ItemState defines the different states an Item can be in
     *
     * Generated from protobuf field <code>string item_version_state = 508677573 [json_name = "item_version_state"];</code>
     * @return string
     */
    public function getItemVersionState()
    {
        return $this->item_version_state;
    }

    /**
     * ItemState defines the different states an Item can be in
     *
     * Generated from protobuf field <code>string item_version_state = 508677573 [json_name = "item_version_state"];</code>
     * @param string $var
     * @return $this
     */
    public function setItemVersionState($var)
    {
        GPBUtil::checkString($var, True);
        $this->item_version_state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool latest_version = 292871203 [json_name = "latest_version"];</code>
     * @return bool
     */
    public function getLatestVersion()
    {
        return $this->latest_version;
    }

    /**
     * Generated from protobuf field <code>bool latest_version = 292871203 [json_name = "latest_version"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLatestVersion($var)
    {
        GPBUtil::checkBool($var);
        $this->latest_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string modification_date = 202999697 [json_name = "modification_date"];</code>
     * @return string
     */
    public function getModificationDate()
    {
        return $this->modification_date;
    }

    /**
     * Generated from protobuf field <code>string modification_date = 202999697 [json_name = "modification_date"];</code>
     * @param string $var
     * @return $this
     */
    public function setModificationDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->modification_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string protection_key_name = 80474900 [json_name = "protection_key_name"];</code>
     * @return string
     */
    public function getProtectionKeyName()
    {
        return $this->protection_key_name;
    }

    /**
     * Generated from protobuf field <code>string protection_key_name = 80474900 [json_name = "protection_key_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setProtectionKeyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->protection_key_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_name = 474147722 [json_name = "target_name"];</code>
     * @return string
     */
    public function getTargetName()
    {
        return $this->target_name;
    }

    /**
     * Generated from protobuf field <code>string target_name = 474147722 [json_name = "target_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setTargetName($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 version = 351608024 [json_name = "version"];</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int32 version = 351608024 [json_name = "version"];</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool with_customer_fragment = 40616536 [json_name = "with_customer_fragment"];</code>
     * @return bool
     */
    public function getWithCustomerFragment()
    {
        return $this->with_customer_fragment;
    }

    /**
     * Generated from protobuf field <code>bool with_customer_fragment = 40616536 [json_name = "with_customer_fragment"];</code>
     * @param bool $var
     * @return $this
     */
    public function setWithCustomerFragment($var)
    {
        GPBUtil::checkBool($var);
        $this->with_customer_fragment = $var;

        return $this;
    }

}

