<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/target_name_with_hosts.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.TargetNameWithHosts</code>
 */
class TargetNameWithHosts extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string hosts = 99467211 [json_name = "hosts"];</code>
     */
    private $hosts;
    /**
     * Generated from protobuf field <code>string target_name = 474147722 [json_name = "target_name"];</code>
     */
    protected $target_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $hosts
     *     @type string $target_name
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\TargetNameWithHosts::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string hosts = 99467211 [json_name = "hosts"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHosts()
    {
        return $this->hosts;
    }

    /**
     * Generated from protobuf field <code>repeated string hosts = 99467211 [json_name = "hosts"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHosts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->hosts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_name = 474147722 [json_name = "target_name"];</code>
     * @return string
     */
    public function getTargetName()
    {
        return $this->target_name;
    }

    /**
     * Generated from protobuf field <code>string target_name = 474147722 [json_name = "target_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setTargetName($var)
    {
        GPBUtil::checkString($var, True);
        $this->target_name = $var;

        return $this;
    }

}

