<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/update_secret_val.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.UpdateSecretVal</code>
 */
class UpdateSecretVal extends \Google\Protobuf\Internal\Message
{
    /**
     * for personal password manager
     *
     * Generated from protobuf field <code>string accessibility = 213139122 [json_name = "accessibility"];</code>
     */
    protected $accessibility = '';
    /**
     * For Password Management use, additional fields
     *
     * Generated from protobuf field <code>map<string, string> custom_field = 176478307 [json_name = "custom-field"];</code>
     */
    private $custom_field;
    /**
     * Secret format [text/json] (relevant only for type 'generic')
     *
     * Generated from protobuf field <code>string format = 195037195 [json_name = "format"];</code>
     */
    protected $format = '';
    /**
     * For Password Management use, reflect the website context
     *
     * Generated from protobuf field <code>repeated string inject_url = 419541814 [json_name = "inject-url"];</code>
     */
    private $inject_url;
    /**
     * Set output format to JSON
     *
     * Generated from protobuf field <code>bool json = 3271912 [json_name = "json"];</code>
     */
    protected $json = false;
    /**
     * Whether to keep previous version [true/false]. If not set, use default according to account settings
     *
     * Generated from protobuf field <code>string keep_prev_version = 489924476 [json_name = "keep-prev-version"];</code>
     */
    protected $keep_prev_version = '';
    /**
     * The name of a key that used to encrypt the secret value (if empty, the account default protectionKey key will be used)
     *
     * Generated from protobuf field <code>string key = 106079 [json_name = "key"];</code>
     */
    protected $key = '';
    /**
     * The last version number before the update
     *
     * Generated from protobuf field <code>int32 last_version = 316433247 [json_name = "last-version"];</code>
     */
    protected $last_version = 0;
    /**
     * The provided value is a multiline value (separated by '\\n')
     *
     * Generated from protobuf field <code>bool multiline = 132497237 [json_name = "multiline"];</code>
     */
    protected $multiline = false;
    /**
     * Secret name
     *
     * Generated from protobuf field <code>string name = 3373707 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Deprecated
     *
     * Generated from protobuf field <code>bool new_version = 23590488 [json_name = "new-version"];</code>
     */
    protected $new_version = false;
    /**
     * For Password Management use, additional fields
     *
     * Generated from protobuf field <code>string password = 143243933 [json_name = "password"];</code>
     */
    protected $password = '';
    /**
     * Authentication token (see `/auth` and `/configure`)
     *
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     */
    protected $token = '';
    /**
     * The universal identity token, Required only for universal_identity authentication
     *
     * Generated from protobuf field <code>string uid_token = 468850238 [json_name = "uid-token"];</code>
     */
    protected $uid_token = '';
    /**
     * For Password Management use
     *
     * Generated from protobuf field <code>string username = 265713450 [json_name = "username"];</code>
     */
    protected $username = '';
    /**
     * The secret value (relevant only for type 'generic')
     *
     * Generated from protobuf field <code>string value = 111972721 [json_name = "value"];</code>
     */
    protected $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $accessibility
     *           for personal password manager
     *     @type array|\Google\Protobuf\Internal\MapField $custom_field
     *           For Password Management use, additional fields
     *     @type string $format
     *           Secret format [text/json] (relevant only for type 'generic')
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $inject_url
     *           For Password Management use, reflect the website context
     *     @type bool $json
     *           Set output format to JSON
     *     @type string $keep_prev_version
     *           Whether to keep previous version [true/false]. If not set, use default according to account settings
     *     @type string $key
     *           The name of a key that used to encrypt the secret value (if empty, the account default protectionKey key will be used)
     *     @type int $last_version
     *           The last version number before the update
     *     @type bool $multiline
     *           The provided value is a multiline value (separated by '\\n')
     *     @type string $name
     *           Secret name
     *     @type bool $new_version
     *           Deprecated
     *     @type string $password
     *           For Password Management use, additional fields
     *     @type string $token
     *           Authentication token (see `/auth` and `/configure`)
     *     @type string $uid_token
     *           The universal identity token, Required only for universal_identity authentication
     *     @type string $username
     *           For Password Management use
     *     @type string $value
     *           The secret value (relevant only for type 'generic')
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\UpdateSecretVal::initOnce();
        parent::__construct($data);
    }

    /**
     * for personal password manager
     *
     * Generated from protobuf field <code>string accessibility = 213139122 [json_name = "accessibility"];</code>
     * @return string
     */
    public function getAccessibility()
    {
        return $this->accessibility;
    }

    /**
     * for personal password manager
     *
     * Generated from protobuf field <code>string accessibility = 213139122 [json_name = "accessibility"];</code>
     * @param string $var
     * @return $this
     */
    public function setAccessibility($var)
    {
        GPBUtil::checkString($var, True);
        $this->accessibility = $var;

        return $this;
    }

    /**
     * For Password Management use, additional fields
     *
     * Generated from protobuf field <code>map<string, string> custom_field = 176478307 [json_name = "custom-field"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCustomField()
    {
        return $this->custom_field;
    }

    /**
     * For Password Management use, additional fields
     *
     * Generated from protobuf field <code>map<string, string> custom_field = 176478307 [json_name = "custom-field"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCustomField($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->custom_field = $arr;

        return $this;
    }

    /**
     * Secret format [text/json] (relevant only for type 'generic')
     *
     * Generated from protobuf field <code>string format = 195037195 [json_name = "format"];</code>
     * @return string
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * Secret format [text/json] (relevant only for type 'generic')
     *
     * Generated from protobuf field <code>string format = 195037195 [json_name = "format"];</code>
     * @param string $var
     * @return $this
     */
    public function setFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->format = $var;

        return $this;
    }

    /**
     * For Password Management use, reflect the website context
     *
     * Generated from protobuf field <code>repeated string inject_url = 419541814 [json_name = "inject-url"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInjectUrl()
    {
        return $this->inject_url;
    }

    /**
     * For Password Management use, reflect the website context
     *
     * Generated from protobuf field <code>repeated string inject_url = 419541814 [json_name = "inject-url"];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInjectUrl($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->inject_url = $arr;

        return $this;
    }

    /**
     * Set output format to JSON
     *
     * Generated from protobuf field <code>bool json = 3271912 [json_name = "json"];</code>
     * @return bool
     */
    public function getJson()
    {
        return $this->json;
    }

    /**
     * Set output format to JSON
     *
     * Generated from protobuf field <code>bool json = 3271912 [json_name = "json"];</code>
     * @param bool $var
     * @return $this
     */
    public function setJson($var)
    {
        GPBUtil::checkBool($var);
        $this->json = $var;

        return $this;
    }

    /**
     * Whether to keep previous version [true/false]. If not set, use default according to account settings
     *
     * Generated from protobuf field <code>string keep_prev_version = 489924476 [json_name = "keep-prev-version"];</code>
     * @return string
     */
    public function getKeepPrevVersion()
    {
        return $this->keep_prev_version;
    }

    /**
     * Whether to keep previous version [true/false]. If not set, use default according to account settings
     *
     * Generated from protobuf field <code>string keep_prev_version = 489924476 [json_name = "keep-prev-version"];</code>
     * @param string $var
     * @return $this
     */
    public function setKeepPrevVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->keep_prev_version = $var;

        return $this;
    }

    /**
     * The name of a key that used to encrypt the secret value (if empty, the account default protectionKey key will be used)
     *
     * Generated from protobuf field <code>string key = 106079 [json_name = "key"];</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * The name of a key that used to encrypt the secret value (if empty, the account default protectionKey key will be used)
     *
     * Generated from protobuf field <code>string key = 106079 [json_name = "key"];</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * The last version number before the update
     *
     * Generated from protobuf field <code>int32 last_version = 316433247 [json_name = "last-version"];</code>
     * @return int
     */
    public function getLastVersion()
    {
        return $this->last_version;
    }

    /**
     * The last version number before the update
     *
     * Generated from protobuf field <code>int32 last_version = 316433247 [json_name = "last-version"];</code>
     * @param int $var
     * @return $this
     */
    public function setLastVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->last_version = $var;

        return $this;
    }

    /**
     * The provided value is a multiline value (separated by '\\n')
     *
     * Generated from protobuf field <code>bool multiline = 132497237 [json_name = "multiline"];</code>
     * @return bool
     */
    public function getMultiline()
    {
        return $this->multiline;
    }

    /**
     * The provided value is a multiline value (separated by '\\n')
     *
     * Generated from protobuf field <code>bool multiline = 132497237 [json_name = "multiline"];</code>
     * @param bool $var
     * @return $this
     */
    public function setMultiline($var)
    {
        GPBUtil::checkBool($var);
        $this->multiline = $var;

        return $this;
    }

    /**
     * Secret name
     *
     * Generated from protobuf field <code>string name = 3373707 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Secret name
     *
     * Generated from protobuf field <code>string name = 3373707 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Deprecated
     *
     * Generated from protobuf field <code>bool new_version = 23590488 [json_name = "new-version"];</code>
     * @return bool
     */
    public function getNewVersion()
    {
        return $this->new_version;
    }

    /**
     * Deprecated
     *
     * Generated from protobuf field <code>bool new_version = 23590488 [json_name = "new-version"];</code>
     * @param bool $var
     * @return $this
     */
    public function setNewVersion($var)
    {
        GPBUtil::checkBool($var);
        $this->new_version = $var;

        return $this;
    }

    /**
     * For Password Management use, additional fields
     *
     * Generated from protobuf field <code>string password = 143243933 [json_name = "password"];</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * For Password Management use, additional fields
     *
     * Generated from protobuf field <code>string password = 143243933 [json_name = "password"];</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Authentication token (see `/auth` and `/configure`)
     *
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Authentication token (see `/auth` and `/configure`)
     *
     * Generated from protobuf field <code>string token = 110541305 [json_name = "token"];</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     * The universal identity token, Required only for universal_identity authentication
     *
     * Generated from protobuf field <code>string uid_token = 468850238 [json_name = "uid-token"];</code>
     * @return string
     */
    public function getUidToken()
    {
        return $this->uid_token;
    }

    /**
     * The universal identity token, Required only for universal_identity authentication
     *
     * Generated from protobuf field <code>string uid_token = 468850238 [json_name = "uid-token"];</code>
     * @param string $var
     * @return $this
     */
    public function setUidToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->uid_token = $var;

        return $this;
    }

    /**
     * For Password Management use
     *
     * Generated from protobuf field <code>string username = 265713450 [json_name = "username"];</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * For Password Management use
     *
     * Generated from protobuf field <code>string username = 265713450 [json_name = "username"];</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * The secret value (relevant only for type 'generic')
     *
     * Generated from protobuf field <code>string value = 111972721 [json_name = "value"];</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * The secret value (relevant only for type 'generic')
     *
     * Generated from protobuf field <code>string value = 111972721 [json_name = "value"];</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

}

