<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/vaultless_tokenizer_info.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.VaultlessTokenizerInfo</code>
 */
class VaultlessTokenizerInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.akeyless_grpc.EmailTokenizerInfo email_tokenizer_info = 271498281 [json_name = "email_tokenizer_info"];</code>
     */
    protected $email_tokenizer_info = null;
    /**
     * Generated from protobuf field <code>string key_name = 500938859 [json_name = "key_name"];</code>
     */
    protected $key_name = '';
    /**
     * Generated from protobuf field <code>.akeyless_grpc.RegexpTokenizerInfo regexp_tokenizer_info = 327987509 [json_name = "regexp_tokenizer_info"];</code>
     */
    protected $regexp_tokenizer_info = null;
    /**
     * Generated from protobuf field <code>string template_type = 180013089 [json_name = "template_type"];</code>
     */
    protected $template_type = '';
    /**
     * Tweak used in the case of internal tweak type
     *
     * Generated from protobuf field <code>string tweak = 110773740 [json_name = "tweak"];</code>
     */
    protected $tweak = '';
    /**
     * Generated from protobuf field <code>string tweak_type = 3265968 [json_name = "tweak_type"];</code>
     */
    protected $tweak_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Akeyless\gRPC\EmailTokenizerInfo $email_tokenizer_info
     *     @type string $key_name
     *     @type \Akeyless\gRPC\RegexpTokenizerInfo $regexp_tokenizer_info
     *     @type string $template_type
     *     @type string $tweak
     *           Tweak used in the case of internal tweak type
     *     @type string $tweak_type
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\VaultlessTokenizerInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.EmailTokenizerInfo email_tokenizer_info = 271498281 [json_name = "email_tokenizer_info"];</code>
     * @return \Akeyless\gRPC\EmailTokenizerInfo|null
     */
    public function getEmailTokenizerInfo()
    {
        return $this->email_tokenizer_info;
    }

    public function hasEmailTokenizerInfo()
    {
        return isset($this->email_tokenizer_info);
    }

    public function clearEmailTokenizerInfo()
    {
        unset($this->email_tokenizer_info);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.EmailTokenizerInfo email_tokenizer_info = 271498281 [json_name = "email_tokenizer_info"];</code>
     * @param \Akeyless\gRPC\EmailTokenizerInfo $var
     * @return $this
     */
    public function setEmailTokenizerInfo($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\EmailTokenizerInfo::class);
        $this->email_tokenizer_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key_name = 500938859 [json_name = "key_name"];</code>
     * @return string
     */
    public function getKeyName()
    {
        return $this->key_name;
    }

    /**
     * Generated from protobuf field <code>string key_name = 500938859 [json_name = "key_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setKeyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->key_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.RegexpTokenizerInfo regexp_tokenizer_info = 327987509 [json_name = "regexp_tokenizer_info"];</code>
     * @return \Akeyless\gRPC\RegexpTokenizerInfo|null
     */
    public function getRegexpTokenizerInfo()
    {
        return $this->regexp_tokenizer_info;
    }

    public function hasRegexpTokenizerInfo()
    {
        return isset($this->regexp_tokenizer_info);
    }

    public function clearRegexpTokenizerInfo()
    {
        unset($this->regexp_tokenizer_info);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.RegexpTokenizerInfo regexp_tokenizer_info = 327987509 [json_name = "regexp_tokenizer_info"];</code>
     * @param \Akeyless\gRPC\RegexpTokenizerInfo $var
     * @return $this
     */
    public function setRegexpTokenizerInfo($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\RegexpTokenizerInfo::class);
        $this->regexp_tokenizer_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string template_type = 180013089 [json_name = "template_type"];</code>
     * @return string
     */
    public function getTemplateType()
    {
        return $this->template_type;
    }

    /**
     * Generated from protobuf field <code>string template_type = 180013089 [json_name = "template_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setTemplateType($var)
    {
        GPBUtil::checkString($var, True);
        $this->template_type = $var;

        return $this;
    }

    /**
     * Tweak used in the case of internal tweak type
     *
     * Generated from protobuf field <code>string tweak = 110773740 [json_name = "tweak"];</code>
     * @return string
     */
    public function getTweak()
    {
        return $this->tweak;
    }

    /**
     * Tweak used in the case of internal tweak type
     *
     * Generated from protobuf field <code>string tweak = 110773740 [json_name = "tweak"];</code>
     * @param string $var
     * @return $this
     */
    public function setTweak($var)
    {
        GPBUtil::checkString($var, True);
        $this->tweak = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tweak_type = 3265968 [json_name = "tweak_type"];</code>
     * @return string
     */
    public function getTweakType()
    {
        return $this->tweak_type;
    }

    /**
     * Generated from protobuf field <code>string tweak_type = 3265968 [json_name = "tweak_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setTweakType($var)
    {
        GPBUtil::checkString($var, True);
        $this->tweak_type = $var;

        return $this;
    }

}

