<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/windows_service_attributes.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.WindowsServiceAttributes</code>
 */
class WindowsServiceAttributes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string connection_type = 194995196 [json_name = "connection_type"];</code>
     */
    protected $connection_type = '';
    /**
     * Generated from protobuf field <code>string port = 3446913 [json_name = "port"];</code>
     */
    protected $port = '';
    /**
     * Generated from protobuf field <code>bool use_tls = 147678653 [json_name = "use_tls"];</code>
     */
    protected $use_tls = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $connection_type
     *     @type string $port
     *     @type bool $use_tls
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\WindowsServiceAttributes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string connection_type = 194995196 [json_name = "connection_type"];</code>
     * @return string
     */
    public function getConnectionType()
    {
        return $this->connection_type;
    }

    /**
     * Generated from protobuf field <code>string connection_type = 194995196 [json_name = "connection_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setConnectionType($var)
    {
        GPBUtil::checkString($var, True);
        $this->connection_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string port = 3446913 [json_name = "port"];</code>
     * @return string
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>string port = 3446913 [json_name = "port"];</code>
     * @param string $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkString($var, True);
        $this->port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool use_tls = 147678653 [json_name = "use_tls"];</code>
     * @return bool
     */
    public function getUseTls()
    {
        return $this->use_tls;
    }

    /**
     * Generated from protobuf field <code>bool use_tls = 147678653 [json_name = "use_tls"];</code>
     * @param bool $var
     * @return $this
     */
    public function setUseTls($var)
    {
        GPBUtil::checkBool($var);
        $this->use_tls = $var;

        return $this;
    }

}

