<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/windows_service.proto

namespace Akeyless\gRPC;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>akeyless_grpc.WindowsService</code>
 */
class WindowsService extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.akeyless_grpc.WindowsServiceAttributes attributes = 405645655 [json_name = "attributes"];</code>
     */
    protected $attributes = null;
    /**
     * Generated from protobuf field <code>string host = 3208616 [json_name = "host"];</code>
     */
    protected $host = '';
    /**
     * Generated from protobuf field <code>string name = 3373707 [json_name = "name"];</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Akeyless\gRPC\WindowsServiceAttributes $attributes
     *     @type string $host
     *     @type string $name
     * }
     */
    public function __construct($data = NULL) {
        \Metadata\WindowsService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.WindowsServiceAttributes attributes = 405645655 [json_name = "attributes"];</code>
     * @return \Akeyless\gRPC\WindowsServiceAttributes|null
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    public function hasAttributes()
    {
        return isset($this->attributes);
    }

    public function clearAttributes()
    {
        unset($this->attributes);
    }

    /**
     * Generated from protobuf field <code>.akeyless_grpc.WindowsServiceAttributes attributes = 405645655 [json_name = "attributes"];</code>
     * @param \Akeyless\gRPC\WindowsServiceAttributes $var
     * @return $this
     */
    public function setAttributes($var)
    {
        GPBUtil::checkMessage($var, \Akeyless\gRPC\WindowsServiceAttributes::class);
        $this->attributes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string host = 3208616 [json_name = "host"];</code>
     * @return string
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Generated from protobuf field <code>string host = 3208616 [json_name = "host"];</code>
     * @param string $var
     * @return $this
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3373707 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3373707 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

