<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models/special_types.proto

namespace Metadata;

class SpecialTypes
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
×
models/special_types.protoakeyless_grpc"
StringArray
values (	"0
MapInt64$
map (2.akeyless_grpc.MapInt64BQ
com.akeyless.grpcPZ.;akeyless_grpcªAkeyless.GrpcÊAkeyless\\gRPCâMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

